In [1]:
import pandas as pd

In [2]:
vat = pd.read_csv("Sales_register_aug_2020.csv")
vat.head(3)

,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,Company Name,...,Maximum of Coupa Tax Code,Maximum of External System Tax Code,Maximum of Tax Code (Consolidated),FOP Type,Sum of Assets,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT
0,- None -,31298815,BL-DK0409713,,Bill,11/6/2019,Aug-20,Due on receipt,11/6/2019,- None -,...,NaN,NaN,DK-Z,- None -,0.0,-2480.0,NaN,NaN,2480.0,NaN
1,- None -,31307391,BL-DK0409710,,Bill,11/30/2019,Aug-20,Due on receipt,11/30/2019,- None -,...,NaN,NaN,DK-Z,- None -,0.0,-135.0,NaN,NaN,135.0,NaN
2,- None -,31315780,BL-DK0409711,,Bill,12/31/2019,Aug-20,Due on receipt,12/31/2019,- None -,...,NaN,NaN,DK-Z,- None -,0.0,-135.0,NaN,NaN,135.0,NaN

In [3]:
vat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14556 entries, 0 to 14555
Data columns (total 35 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   External ID                          14556 non-null  object
 1   Document Number                      14555 non-null  object
 2   Transaction Number                   14555 non-null  object
 3   Maximum of Linked Invoice            14555 non-null  object
 4   Type                                 14555 non-null  object
 5   Date                                 14555 non-null  object
 6   Period                               14555 non-null  object
 7   Terms                                14555 non-null  object
 8   Maximum of Due Date/Receive By       9706 non-null   object
 9   Company Name                         14555 non-null  object
 10  Customer VAT Registration Number     14555 non-null  object
 11  Bill to City                         14555 non-null  object
 12  Bill to State                        14555 non-null  object
 13  Bill to Country                      14555 non-null  object
 14  Bill to Zip                          14555 non-null  object
 15  Source System                        14555 non-null  object
 16  Source System Identifier             14555 non-null  object
 17  City                                 14555 non-null  object
 18  State/Province                       14555 non-null  object
 19  Country                              14555 non-null  object
 20  Zip                                  14555 non-null  object
 21  Currency                             14555 non-null  object
 22  Memo (Main)                          14555 non-null  object
 23  Maximum of GMAX Tax Code             9 non-null      object
 24  Maximum of NetSuite Tax Item         13246 non-null  object
 25  Maximum of Coupa Tax Code            0 non-null      float64
 26  Maximum of External System Tax Code  0 non-null      float64
 27  Maximum of Tax Code (Consolidated)   13246 non-null  object
 28  FOP Type                             14555 non-null  object
 29  Sum of Assets                        13808 non-null  float64
 30  Sum of Accounts Payable              256 non-null    float64
 31  Sum of Other Liabilities             13319 non-null  float64
 32  Sum of Income                        13070 non-null  float64
 33  Sum of Expense                       254 non-null    float64
 34  Sum of VAT                           13087 non-null  float64
dtypes: float64(8), object(27)
memory usage: 3.9+ MB

In [4]:
#vat['xxx'].fillna(0, inplace=True) if you want to replace null values with 0 for a certain colmn

In [5]:
#vat[vat['Sum of VAT'] == 0] if you want to filter in a column

In [6]:
del1 = vat[vat["External ID"].str.contains("clearing")].index

In [7]:
del1

Int64Index([14517], dtype='int64')

In [8]:
vat.drop(del1, inplace = True)

In [9]:
del2 = vat[vat["External ID"].str.contains("Cross")].index

In [10]:
del2

Int64Index([13277, 14472, 14507, 14508, 14509, 14510, 14511, 14512], dtype='int64')

In [11]:
vat.drop(del2, inplace=True)

In [12]:
#vat.drop(index = 62066, inplace = True) 'you can also remove line like this

In [13]:
vat.index

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            14546, 14547, 14548, 14549, 14550, 14551, 14552, 14553, 14554,
            14555],
           dtype='int64', length=14547)

In [14]:
14517 in vat.index

False

In [15]:
mask1 = vat[vat["Type"] == "Currency Revaluation"].index

In [16]:
mask1

Int64Index([   88,    89,    90,    91,   104,   105,   106,   107,   108,
              109,   110,   111,   112,   113,   114,   115,   116,   117,
              118,   119,   120,   121,   122,   123,   124,   125,   126,
             2421,  2422,  2423,  2424,  6468,  6469,  6470,  6471,  7202,
             7203,  7204,  7205,  7892,  7893,  7894,  7895,  7896,  7897,
             9196,  9197,  9198,  9199,  9979,  9980, 12128, 12129, 12713,
            12714, 13683, 13684, 13685, 13686, 13687],
           dtype='int64')

In [17]:
vat.drop(mask1, inplace = True)

In [18]:
87 in vat.index

True

In [19]:
vat.index

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            14546, 14547, 14548, 14549, 14550, 14551, 14552, 14553, 14554,
            14555],
           dtype='int64', length=14487)

In [20]:
vat.loc[87]

External ID                                                             - None -
Document Number                                                           140652
Transaction Number                                                  BL-DK0409693
Maximum of Linked Invoice
Type                                                                        Bill
Date                                                                   7/31/2020
Period                                                                    Aug-20
Terms                                                                     Net 60
Maximum of Due Date/Receive By                                         9/29/2020
Company Name                                                            - None -
Customer VAT Registration Number                                        - None -
Bill to City                                                          COPENHAGEN
Bill to State                                                           - None -
Bill to Country                                                          Denmark
Bill to Zip                                                                 1366
Source System                                                        Procurement
Source System Identifier                                                - None -
City                                                                Copenhagen K
State/Province                                                          - None -
Country                                                                  Denmark
Zip                                                                      DK-1366
Currency                                                            Danish Krone
Memo (Main)                            Courier service, Denmark Copenhagen, 2020
Maximum of GMAX Tax Code                                                     NaN
Maximum of NetSuite Tax Item                                                DK-S
Maximum of Coupa Tax Code                                                    NaN
Maximum of External System Tax Code                                          NaN
Maximum of Tax Code (Consolidated)                                          DK-S
FOP Type                                                                - None -
Sum of Assets                                                             265.63
Sum of Accounts Payable                                                 -1328.13
Sum of Other Liabilities                                                     NaN
Sum of Income                                                                NaN
Sum of Expense                                                            1062.5
Sum of VAT                                                                   NaN
Name: 87, dtype: object

In [21]:
#after the rows that have been droped, the old rows have same index label as before, but a different index number, but in essance we have 61952 entries
vat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14487 entries, 0 to 14555
Data columns (total 35 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   External ID                          14487 non-null  object
 1   Document Number                      14486 non-null  object
 2   Transaction Number                   14486 non-null  object
 3   Maximum of Linked Invoice            14486 non-null  object
 4   Type                                 14486 non-null  object
 5   Date                                 14486 non-null  object
 6   Period                               14486 non-null  object
 7   Terms                                14486 non-null  object
 8   Maximum of Due Date/Receive By       9706 non-null   object
 9   Company Name                         14486 non-null  object
 10  Customer VAT Registration Number     14486 non-null  object
 11  Bill to City                         14486 non-null  object
 12  Bill to State                        14486 non-null  object
 13  Bill to Country                      14486 non-null  object
 14  Bill to Zip                          14486 non-null  object
 15  Source System                        14486 non-null  object
 16  Source System Identifier             14486 non-null  object
 17  City                                 14486 non-null  object
 18  State/Province                       14486 non-null  object
 19  Country                              14486 non-null  object
 20  Zip                                  14486 non-null  object
 21  Currency                             14486 non-null  object
 22  Memo (Main)                          14486 non-null  object
 23  Maximum of GMAX Tax Code             9 non-null      object
 24  Maximum of NetSuite Tax Item         13246 non-null  object
 25  Maximum of Coupa Tax Code            0 non-null      float64
 26  Maximum of External System Tax Code  0 non-null      float64
 27  Maximum of Tax Code (Consolidated)   13246 non-null  object
 28  FOP Type                             14486 non-null  object
 29  Sum of Assets                        13792 non-null  float64
 30  Sum of Accounts Payable              230 non-null    float64
 31  Sum of Other Liabilities             13309 non-null  float64
 32  Sum of Income                        13069 non-null  float64
 33  Sum of Expense                       221 non-null    float64
 34  Sum of VAT                           13086 non-null  float64
dtypes: float64(8), object(27)
memory usage: 4.6+ MB

In [22]:
#excel_file = pd.ExcelWriter("Darko VAT.xlsx")

In [23]:
#vat.to_excel(excel_file, sheet_name = "vat", index = False)

In [24]:
#excel_file.save()

In [25]:
#vat.loc[61962] #check the row in data frame

In [26]:
vat.tail()

,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,Company Name,...,Maximum of Coupa Tax Code,Maximum of External System Tax Code,Maximum of Tax Code (Consolidated),FOP Type,Sum of Assets,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT
14551,GBTICJE-IDENTIFIERB-ID2304878,JE-NL1279388,TJE-NL0169312,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,NaN,NaN,DK-S : DK-ESSP,- None -,558.14,-2232.54,0.00,NaN,2232.54,-558.14
14552,GBTICJE-IDENTIFIERB-ID2304896,JE-NL1279405,TJE-NL0169329,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,NaN,NaN,DK-S : DK-ESSP,- None -,419.26,-1677.03,0.00,NaN,1677.03,-419.26
14553,GBTICJE-IDENTIFIERH-ID2305279,JE-NL1279455,TJE-NL0169379,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,NaN,NaN,DK-S : DK-ESSP,- None -,2308.48,NaN,0.00,NaN,-3077.97,769.49
14554,GBTICJE-IDENTIFIERH-ID2305297,JE-NL1279473,TJE-NL0169397,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,NaN,NaN,DK-S : DK-ESSP,- None -,1548.07,NaN,0.00,NaN,-2064.09,516.02
14555,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8490560.84,-4080201.64,-9873875.81,-4267858.25,9731374.86,0.00

In [27]:
vat.drop(index = 14555, inplace = True)

In [28]:
vat.tail(3)

,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,Company Name,...,Maximum of Coupa Tax Code,Maximum of External System Tax Code,Maximum of Tax Code (Consolidated),FOP Type,Sum of Assets,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT
14552,GBTICJE-IDENTIFIERB-ID2304896,JE-NL1279405,TJE-NL0169329,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,NaN,NaN,DK-S : DK-ESSP,- None -,419.26,-1677.03,0.0,NaN,1677.03,-419.26
14553,GBTICJE-IDENTIFIERH-ID2305279,JE-NL1279455,TJE-NL0169379,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,NaN,NaN,DK-S : DK-ESSP,- None -,2308.48,NaN,0.0,NaN,-3077.97,769.49
14554,GBTICJE-IDENTIFIERH-ID2305297,JE-NL1279473,TJE-NL0169397,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,NaN,NaN,DK-S : DK-ESSP,- None -,1548.07,NaN,0.0,NaN,-2064.09,516.02

In [29]:
vat[["Sum of Assets","Sum of Accounts Payable","Sum of Other Liabilities","Sum of Income","Sum of Expense","Sum of VAT"]].sum(axis= "rows")

Sum of Assets               8422366.16
Sum of Accounts Payable    -3988692.36
Sum of Other Liabilities   -9561233.92
Sum of Income              -4035309.78
Sum of Expense              9700101.10
Sum of VAT                  -537231.20
dtype: float64

In [30]:
#remember Rows axis means that the values go down the rows/columns, and columns means they go across the columns, 
#in this case sum of assets etc goes down the rows!!!!

In [31]:
vat.iloc[:, -6:].sum()

Sum of Assets               8422366.16
Sum of Accounts Payable    -3988692.36
Sum of Other Liabilities   -9561233.92
Sum of Income              -4035309.78
Sum of Expense              9700101.10
Sum of VAT                  -537231.20
dtype: float64

In [32]:
#Summerize the last row
#vat.loc["Totals"] = pd.Series(vat[["Sum of Assets","Sum of Accounts Payable","Sum of Other Liabilities","Sum of Income","Sum of Expense","Sum of VAT"]].sum(), index = ["Sum of Assets","Sum of Accounts Payable","Sum of Other Liabilities","Sum of Income","Sum of Expense","Sum of VAT"])

In [33]:
vat["VAT rate"] = vat["Sum of VAT"] / (vat["Sum of Other Liabilities"] + vat["Sum of Income"])

In [34]:
vat.tail(3)

,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,Company Name,...,Maximum of External System Tax Code,Maximum of Tax Code (Consolidated),FOP Type,Sum of Assets,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,VAT rate
14552,GBTICJE-IDENTIFIERB-ID2304896,JE-NL1279405,TJE-NL0169329,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,NaN,DK-S : DK-ESSP,- None -,419.26,-1677.03,0.0,NaN,1677.03,-419.26,NaN
14553,GBTICJE-IDENTIFIERH-ID2305279,JE-NL1279455,TJE-NL0169379,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,NaN,DK-S : DK-ESSP,- None -,2308.48,NaN,0.0,NaN,-3077.97,769.49,NaN
14554,GBTICJE-IDENTIFIERH-ID2305297,JE-NL1279473,TJE-NL0169397,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,NaN,DK-S : DK-ESSP,- None -,1548.07,NaN,0.0,NaN,-2064.09,516.02,NaN

In [35]:
vat["Liab+Net Inc"] = vat["Sum of Other Liabilities"] + vat["Sum of Income"]

In [36]:
vat.head(100)

,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,Company Name,...,Maximum of Tax Code (Consolidated),FOP Type,Sum of Assets,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc
0,- None -,31298815,BL-DK0409713,,Bill,11/6/2019,Aug-20,Due on receipt,11/6/2019,- None -,...,DK-Z,- None -,0.00,-2480.00,NaN,NaN,2480.00,NaN,NaN,NaN
1,- None -,31307391,BL-DK0409710,,Bill,11/30/2019,Aug-20,Due on receipt,11/30/2019,- None -,...,DK-Z,- None -,0.00,-135.00,NaN,NaN,135.00,NaN,NaN,NaN
2,- None -,31315780,BL-DK0409711,,Bill,12/31/2019,Aug-20,Due on receipt,12/31/2019,- None -,...,DK-Z,- None -,0.00,-135.00,NaN,NaN,135.00,NaN,NaN,NaN
3,- None -,640012345,BL-DK0409836,,Bill,2/4/2020,Aug-20,Net 15,2/19/2020,- None -,...,DK-S,- None -,1683.78,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN
4,- None -,31331755,BL-DK0409712,,Bill,2/29/2020,Aug-20,Due on receipt,2/29/2020,- None -,...,DK-Z,- None -,0.00,-90.00,NaN,NaN,90.00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,- None -,508818,BL-DK0409777,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,- None -,...,DK-Z,- None -,0.00,-33563.31,NaN,NaN,33563.31,NaN,NaN,NaN
100,- None -,53702,BL-DK0409760,,Bill,7/31/2020,Aug-20,Net 20,8/20/2020,- None -,...,DK-S,- None -,506.25,-2531.25,NaN,NaN,2025.00,NaN,NaN,NaN
101,- None -,8037108,BL-DK0409744,,Bill,7/31/2020,Aug-20,Net 15,8/15/2020,- None -,...,DK-S,- None -,67.76,-338.78,NaN,NaN,271.02,NaN,NaN,NaN
102,- None -,202008001,BL-DK0409709,,Bill,8/1/2020,Aug-20,NET 8,8/1/2020,- None -,...,DK-Z,- None -,0.00,-323741.82,NaN,NaN,323741.82,NaN,NaN,NaN
103,- None -,202008002,BL-DK0409708,,Bill,8/1/2020,Aug-20,NET 8,8/1/2020,- None -,...,DK-Z,- None -,0.00,-64748.36,NaN,NaN,64748.36,NaN,NaN,NaN

In [37]:
vat["Correct revenue"] = vat["Sum of VAT"] / 0.25

In [38]:
vat.head(50)

,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,Company Name,...,FOP Type,Sum of Assets,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue
0,- None -,31298815,BL-DK0409713,,Bill,11/6/2019,Aug-20,Due on receipt,11/6/2019,- None -,...,- None -,0.00,-2480.00,NaN,NaN,2480.00,NaN,NaN,NaN,NaN
1,- None -,31307391,BL-DK0409710,,Bill,11/30/2019,Aug-20,Due on receipt,11/30/2019,- None -,...,- None -,0.00,-135.00,NaN,NaN,135.00,NaN,NaN,NaN,NaN
2,- None -,31315780,BL-DK0409711,,Bill,12/31/2019,Aug-20,Due on receipt,12/31/2019,- None -,...,- None -,0.00,-135.00,NaN,NaN,135.00,NaN,NaN,NaN,NaN
3,- None -,640012345,BL-DK0409836,,Bill,2/4/2020,Aug-20,Net 15,2/19/2020,- None -,...,- None -,1683.78,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,- None -,31331755,BL-DK0409712,,Bill,2/29/2020,Aug-20,Due on receipt,2/29/2020,- None -,...,- None -,0.00,-90.00,NaN,NaN,90.00,NaN,NaN,NaN,NaN
5,- None -,31898105,BL-DK0409840,,Bill,2/29/2020,Aug-20,Net 30,3/30/2020,- None -,...,- None -,69625.00,-348125.00,NaN,NaN,278500.00,NaN,NaN,NaN,NaN
6,- None -,640012494,BL-DK0409835,,Bill,3/3/2020,Aug-20,Net 15,3/18/2020,- None -,...,- None -,1683.78,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,- None -,640012755,BL-DK0409832,,Bill,4/2/2020,Aug-20,Net 15,4/17/2020,- None -,...,- None -,1683.78,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,- None -,640012916,BL-DK0409833,,Bill,5/5/2020,Aug-20,Net 15,5/20/2020,- None -,...,- None -,1683.78,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,584168307-VOID,IN-DK4779863,TIN-DK4779863,Credit Memo #CM-DK0311839,Invoice,5/5/2020,Aug-20,Due on receipt,5/5/2020,SG 8300 IT AND S,...,- None -,4638.09,NaN,-4638.09,0.00,NaN,0.0,-0.0,-4638.09,0.0
10,584186447-VOID,IN-DK4779864,TIN-DK4779864,Credit Memo #CM-DK0311849,Invoice,5/5/2020,Aug-20,Due on receipt,5/5/2020,AMERICAN EXPRESS BUSINESS T.,...,- None -,235.12,NaN,-235.12,0.00,NaN,0.0,-0.0,-235.12,0.0
11,- None -,602988936,BL-DK0409843,,Bill,5/6/2020,Aug-20,Net 15,5/21/2020,- None -,...,- None -,471.04,-2355.18,NaN,NaN,1884.14,NaN,NaN,NaN,NaN
12,- None -,152,BL-DK0409828,,Bill,5/11/2020,Aug-20,Net 15,5/26/2020,- None -,...,- None -,25.13,-125.65,NaN,NaN,100.52,NaN,NaN,NaN,NaN
13,584429618-VOID,IN-DK4779865,TIN-DK4779865,Credit Memo #CM-DK0311909,Invoice,5/11/2020,Aug-20,Net 30,6/10/2020,MEDTRONIC DANMARK A/S,...,- None -,1140.00,NaN,-1140.00,0.00,NaN,0.0,-0.0,-1140.00,0.0
14,584431188-VOID,IN-DK4779866,TIN-DK4779866,Credit Memo #CM-DK0311910,Invoice,5/11/2020,Aug-20,- None -,5/11/2020,MAERSK VIKING OFFSHORE,...,- None -,764.00,NaN,-756.14,-7.86,NaN,0.0,-0.0,-764.00,0.0
15,584431196-VOID,IN-DK4779867,TIN-DK4779867,Credit Memo #CM-DK0311911,Invoice,5/11/2020,Aug-20,- None -,5/11/2020,BASF A/S,...,- None -,2838.00,NaN,-2838.00,0.00,NaN,0.0,-0.0,-2838.00,0.0
16,584869074-VOID,IN-DK4779868,TIN-DK4779868,Credit Memo #CM-DK0312047,Invoice,5/11/2020,Aug-20,Net 45,6/25/2020,GARTNER DANMARK APS,...,- None -,295.00,NaN,-295.00,0.00,NaN,0.0,-0.0,-295.00,0.0
17,584869081-VOID,IN-DK4779869,TIN-DK4779869,Credit Memo #CM-DK0312048,Invoice,5/11/2020,Aug-20,Due on receipt,5/11/2020,BOSTON CONSULTING GROUP,...,- None -,168.00,NaN,-168.00,0.00,NaN,0.0,-0.0,-168.00,0.0
18,584869087-VOID,IN-DK4779870,TIN-DK4779870,Credit Memo #CM-DK0312049,Invoice,5/11/2020,Aug-20,- None -,5/11/2020,LEO PHARMA A/S DENMARK,...,- None -,1517.00,NaN,-1517.00,0.00,NaN,0.0,-0.0,-1517.00,0.0
19,584869096-VOID,IN-DK4779871,TIN-DK4779871,Credit Memo #CM-DK0312050,Invoice,5/11/2020,Aug-20,Due on receipt,5/11/2020,SCHLUMBERGER DANMARK,...,- None -,3456.00,NaN,-3456.00,0.00,NaN,0.0,-0.0,-3456.00,0.0
20,584869105-VOID,IN-DK4779872,TIN-DK4779872,Credit Memo #CM-DK0312051,Invoice,5/11/2020,Aug-20,Due on receipt,5/11/2020,BOSTON CONSULTING GROUP,...,- None -,2754.00,NaN,-2754.00,0.00,NaN,0.0,-0.0,-2754.00,0.0
21,584869113-VOID,IN-DK4779873,TIN-DK4779873,Credit Memo #CM-DK0312052,Invoice,5/11/2020,Aug-20,Due on receipt,5/11/2020,BOSTON CONSULTING GROUP,...,- None -,2754.00,NaN,-2754.00,0.00,NaN,0.0,-0.0,-2754.00,0.0
22,584869131-VOID,IN-DK4779874,TIN-DK4779874,Credit Memo #CM-DK0312054,Invoice,5/11/2020,Aug-20,Due on receipt,5/11/2020,BOSTON CONSULTING GROUP,...,- None -,168.00,NaN,-168.00,0.00,NaN,0.0,-0.0,-168.00,0.0
23,584704794-VOID,IN-DK4779875,TIN-DK4779875,Credit Memo #CM-DK0311962,Invoice,5/18/2020,Aug-20,Net 30,6/17/2020,GMA - GRUNDFOS HOLDING A/S,...,- None -,58.22,NaN,-58.22,0.00,NaN,0.0,-0.0,-58.22,0.0
24,- None -,640013059,BL-DK0409834,,Bill,6/2/2020,Aug-20,Net 15,6/17/2020,- None -,...,- None -,1683.78,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,- None -,151,BL-DK0409829,,Bill,6/8/2020,Aug-20,Net 15,6/23/2020,- None -,...,- None -,23.89,-119.45,NaN,NaN,95.56,NaN,NaN,NaN,NaN
26,585844499-VOID,IN-DK4779876,TIN-DK4779876,Credit Memo #CM-DK0312237,Invoice,6/10/2020,Aug-20,Due on receipt,6/10/2020,MAERSK LAVRAS,...,- None -,2078.00,NaN,-2040.96,-37.04,NaN,0.0,-0.0,-2078.00,0.0
27,585844501-VOID,IN-DK4779877,TIN-DK4779877,Credit Memo #CM-DK0312238,Invoice,6/10/2020,Aug-20,- None -,6/10/2020,MAERSK EVORA,...,- None -,3549.00,NaN,-3549.00,0.00,NaN,0.0,-0.0,-3549.00,0.0
28,585844502-VOID,IN-DK4779878,TIN-DK4779878,Credit Memo #CM-DK0312241,Invoice,6/10/2020,Aug-20,Due on receipt,6/10/2020,CORNELIA MAERSK,...,- None -,3006.00,NaN,-2947.36,-58.64,NaN,0.0,-0.0,-3006.00,0.0
29,585850401-VOID,IN-DK4779879,TIN-DK4779879,Credit Memo #CM-DK0312245,Invoice,6/10/2020,Aug-20,Due on receipt,6/10/2020,GERDA MAERSK,...,- None -,3940.00,NaN,-3940.00,0.00,NaN,0.0,-0.0,-3940.00,0.0
30,585909250-VOID,IN-DK4779880,TIN-DK4779880,Credit Memo #CM-DK0312277,Invoice,6/11/2020,Aug-20,Net 30,7/11/2020,MT HOJGAARD A/S,...,- None -,17657.00,NaN,-17657.00,0.00,NaN,0.0,-0.0,-17657.00,0.0
31,586398050-VOID,IN-DK4779881,TIN-DK4779881,Credit Memo #CM-DK0312324,Invoice,6/17/2020,Aug-20,Due on receipt,6/17/2020,SOVEREIGN MAERSK,...,- None -,1338.00,NaN,-1338.00,0.00,NaN,0.0,-0.0,-1338.00,0.0
32,586454439-VOID,IN-DK4779882,TIN-DK4779882,Credit Memo #CM-DK0312332,Invoice,6/18/2020,Aug-20,Net 30,7/18/2020,KREDITKORTSALG DINERS,...,- None -,875.00,NaN,-875.00,0.00,NaN,0.0,-0.0,-875.00,0.0
33,586721166-VOID,IN-DK4779883,TIN-DK4779883,Credit Memo #CM-DK0312406,Invoice,6/24/2020,Aug-20,Due on receipt,6/24/2020,GJERTRUD MAERSK,...,- None -,3048.00,NaN,-2982.00,-66.00,NaN,0.0,-0.0,-3048.00,0.0
34,586723219-VOID,IN-DK4779884,TIN-DK4779884,Credit Memo #CM-DK0312428,Invoice,6/24/2020,Aug-20,- None -,6/24/2020,P234 MAERSK RESILIENT OFFSHORE,...,- None -,1132.00,NaN,-1132.00,0.00,NaN,0.0,-0.0,-1132.00,0.0
35,21538_ID-549901_COGSADJ,JE-DK0303432,TJE-DK0303432,,Journal,6/26/2020,Aug-20,- None -,NaN,- None -,...,- None -,NaN,NaN,71.74,-71.74,NaN,NaN,NaN,0.00,NaN
36,586943538-VOID,IN-DK4779885,TIN-DK4779885,Credit Memo #CM-DK0312498,Invoice,6/29/2020,Aug-20,- None -,6/29/2020,HOWDEN TURBO,...,- None -,1371.00,NaN,-1371.00,0.00,NaN,0.0,-0.0,-1371.00,0.0
37,586954039-VOID,IN-DK4779886,TIN-DK4779886,Credit Memo #CM-DK0312502,Invoice,6/29/2020,Aug-20,- None -,6/29/2020,MAERSK DANUBE,...,- None -,2245.00,NaN,-2245.00,0.00,NaN,0.0,-0.0,-2245.00,0.0
38,- None -,150,BL-DK0409830,,Bill,7/1/2020,Aug-20,Net 15,7/16/2020,- None -,...,- None -,55.68,-278.42,NaN,NaN,222.74,NaN,NaN,NaN,NaN
39,587097837-VOID,IN-DK4779887,TIN-DK4779887,Credit Memo #CM-DK0312530,Invoice,7/1/2020,Aug-20,Due on receipt,7/1/2020,MAERSK SEMAKAU,...,- None -,1287.00,NaN,-1287.00,0.00,NaN,0.0,-0.0,-1287.00,0.0
40,- None -,640013309,BL-DK0409704,,Bill,7/2/2020,Aug-20,Net 15,7/17/2020,- None -,...,- None -,1683.78,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,587408293-VOID,IN-DK4779888,TIN-DK4779888,Credit Memo #CM-DK0312615,Invoice,7/7/2020,Aug-20,Due on receipt,7/7/2020,ELEONORA MAERSK,...,- None -,816.25,NaN,-816.25,0.00,NaN,0.0,-0.0,-816.25,0.0
42,587432075-VOID,IN-DK4779889,TIN-DK4779889,Credit Memo #CM-DK0312626,Invoice,7/7/2020,Aug-20,Due on receipt,7/7/2020,MAERSK LIMA,...,- None -,1084.00,NaN,-1084.00,0.00,NaN,0.0,-0.0,-1084.00,0.0
43,587541664-VOID,IN-DK4779890,TIN-DK4779890,Credit Memo #CM-DK0312661,Invoice,7/9/2020,Aug-20,- None -,7/9/2020,SANTA INES,...,- None -,1981.00,NaN,-1981.00,0.00,NaN,0.0,-0.0,-1981.00,0.0
44,587599518-VOID,IN-DK4779891,TIN-DK4779891,Credit Memo #CM-DK0312679,Invoice,7/10/2020,Aug-20,- None -,7/10/2020,MAERSK HERRERA,...,- None -,3456.00,NaN,-3456.00,0.00,NaN,0.0,-0.0,-3456.00,0.0
45,587603429-VOID,IN-DK4779892,TIN-DK4779892,Credit Memo #CM-DK0312681,Invoice,7/10/2020,Aug-20,- None -,7/10/2020,SANTA INES,...,- None -,2019.00,NaN,-2019.00,0.00,NaN,0.0,-0.0,-2019.00,0.0
46,587631781-VOID,IN-DK4779893,TIN-DK4779893,Credit Memo #CM-DK0312695,Invoice,7/10/2020,Aug-20,- None -,7/10/2020,MAERSK EMDEN,...,- None -,798.00,NaN,-798.00,0.00,NaN,0.0,-0.0,-798.00,0.0
47,- None -,584423507,BL-DK0409647,,Bill,7/13/2020,Aug-20,Net 15,7/28/2020,- None -,...,- None -,2106.74,-10533.68,NaN,NaN,8426.94,NaN,NaN,NaN,NaN
48,587738692-VOID,IN-DK4779894,TIN-DK4779894,Credit Memo #CM-DK0312717,Invoice,7/13/2020,Aug-20,Due on receipt,7/13/2020,EDITH MAERSK,...,- None -,2358.00,NaN,-2358.00,0.00,NaN,0.0,-0.0,-2358.00,0.0
49,587738701-VOID,IN-DK4779895,TIN-DK4779895,Credit Memo #CM-DK0312718,Invoice,7/13/2020,Aug-20,Due on receipt,7/13/2020,EDITH MAERSK,...,- None -,2355.00,NaN,-2355.00,0.00,NaN,0.0,-0.0,-2355.00,0.0

In [39]:
#excel_file = pd.ExcelWriter("Darko VAT3.xlsx")

#vat.to_excel(excel_file, sheet_name = "vat", index = False)

#excel_file.save()

In [40]:
def vat_amount(row):

    vat_yes = row[34]

    if vat_yes > 0:
        return "VAT"
    elif vat_yes < 0 :
        return "VAT"
    else:
        return "Transactions 0DKK"
    
vat["Comment"] = vat.apply(vat_amount, axis= "columns")

In [41]:
#pd.options.display.max_rows = 4000
vat.head(20)

,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,Company Name,...,Sum of Assets,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment
0,- None -,31298815,BL-DK0409713,,Bill,11/6/2019,Aug-20,Due on receipt,11/6/2019,- None -,...,0.00,-2480.00,NaN,NaN,2480.00,NaN,NaN,NaN,NaN,Transactions 0DKK
1,- None -,31307391,BL-DK0409710,,Bill,11/30/2019,Aug-20,Due on receipt,11/30/2019,- None -,...,0.00,-135.00,NaN,NaN,135.00,NaN,NaN,NaN,NaN,Transactions 0DKK
2,- None -,31315780,BL-DK0409711,,Bill,12/31/2019,Aug-20,Due on receipt,12/31/2019,- None -,...,0.00,-135.00,NaN,NaN,135.00,NaN,NaN,NaN,NaN,Transactions 0DKK
3,- None -,640012345,BL-DK0409836,,Bill,2/4/2020,Aug-20,Net 15,2/19/2020,- None -,...,1683.78,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transactions 0DKK
4,- None -,31331755,BL-DK0409712,,Bill,2/29/2020,Aug-20,Due on receipt,2/29/2020,- None -,...,0.00,-90.00,NaN,NaN,90.00,NaN,NaN,NaN,NaN,Transactions 0DKK
5,- None -,31898105,BL-DK0409840,,Bill,2/29/2020,Aug-20,Net 30,3/30/2020,- None -,...,69625.00,-348125.00,NaN,NaN,278500.00,NaN,NaN,NaN,NaN,Transactions 0DKK
6,- None -,640012494,BL-DK0409835,,Bill,3/3/2020,Aug-20,Net 15,3/18/2020,- None -,...,1683.78,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transactions 0DKK
7,- None -,640012755,BL-DK0409832,,Bill,4/2/2020,Aug-20,Net 15,4/17/2020,- None -,...,1683.78,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transactions 0DKK
8,- None -,640012916,BL-DK0409833,,Bill,5/5/2020,Aug-20,Net 15,5/20/2020,- None -,...,1683.78,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transactions 0DKK
9,584168307-VOID,IN-DK4779863,TIN-DK4779863,Credit Memo #CM-DK0311839,Invoice,5/5/2020,Aug-20,Due on receipt,5/5/2020,SG 8300 IT AND S,...,4638.09,NaN,-4638.09,0.00,NaN,0.0,-0.0,-4638.09,0.0,Transactions 0DKK
10,584186447-VOID,IN-DK4779864,TIN-DK4779864,Credit Memo #CM-DK0311849,Invoice,5/5/2020,Aug-20,Due on receipt,5/5/2020,AMERICAN EXPRESS BUSINESS T.,...,235.12,NaN,-235.12,0.00,NaN,0.0,-0.0,-235.12,0.0,Transactions 0DKK
11,- None -,602988936,BL-DK0409843,,Bill,5/6/2020,Aug-20,Net 15,5/21/2020,- None -,...,471.04,-2355.18,NaN,NaN,1884.14,NaN,NaN,NaN,NaN,Transactions 0DKK
12,- None -,152,BL-DK0409828,,Bill,5/11/2020,Aug-20,Net 15,5/26/2020,- None -,...,25.13,-125.65,NaN,NaN,100.52,NaN,NaN,NaN,NaN,Transactions 0DKK
13,584429618-VOID,IN-DK4779865,TIN-DK4779865,Credit Memo #CM-DK0311909,Invoice,5/11/2020,Aug-20,Net 30,6/10/2020,MEDTRONIC DANMARK A/S,...,1140.00,NaN,-1140.00,0.00,NaN,0.0,-0.0,-1140.00,0.0,Transactions 0DKK
14,584431188-VOID,IN-DK4779866,TIN-DK4779866,Credit Memo #CM-DK0311910,Invoice,5/11/2020,Aug-20,- None -,5/11/2020,MAERSK VIKING OFFSHORE,...,764.00,NaN,-756.14,-7.86,NaN,0.0,-0.0,-764.00,0.0,Transactions 0DKK
15,584431196-VOID,IN-DK4779867,TIN-DK4779867,Credit Memo #CM-DK0311911,Invoice,5/11/2020,Aug-20,- None -,5/11/2020,BASF A/S,...,2838.00,NaN,-2838.00,0.00,NaN,0.0,-0.0,-2838.00,0.0,Transactions 0DKK
16,584869074-VOID,IN-DK4779868,TIN-DK4779868,Credit Memo #CM-DK0312047,Invoice,5/11/2020,Aug-20,Net 45,6/25/2020,GARTNER DANMARK APS,...,295.00,NaN,-295.00,0.00,NaN,0.0,-0.0,-295.00,0.0,Transactions 0DKK
17,584869081-VOID,IN-DK4779869,TIN-DK4779869,Credit Memo #CM-DK0312048,Invoice,5/11/2020,Aug-20,Due on receipt,5/11/2020,BOSTON CONSULTING GROUP,...,168.00,NaN,-168.00,0.00,NaN,0.0,-0.0,-168.00,0.0,Transactions 0DKK
18,584869087-VOID,IN-DK4779870,TIN-DK4779870,Credit Memo #CM-DK0312049,Invoice,5/11/2020,Aug-20,- None -,5/11/2020,LEO PHARMA A/S DENMARK,...,1517.00,NaN,-1517.00,0.00,NaN,0.0,-0.0,-1517.00,0.0,Transactions 0DKK
19,584869096-VOID,IN-DK4779871,TIN-DK4779871,Credit Memo #CM-DK0312050,Invoice,5/11/2020,Aug-20,Due on receipt,5/11/2020,SCHLUMBERGER DANMARK,...,3456.00,NaN,-3456.00,0.00,NaN,0.0,-0.0,-3456.00,0.0,Transactions 0DKK

In [42]:
def applyFunc(s):
    if s == "VAT":
        return "Domestic 25%"
    

vat["Transaction type"] = vat["Comment"].apply(applyFunc)

In [43]:
#excel_file = pd.ExcelWriter("Darko VAT3.xlsx")

#vat.to_excel(excel_file, sheet_name = "vat", index = False)

#excel_file.save()

In [44]:
vat.tail(5)

,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,Company Name,...,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type
14550,GBTICJE-IDENTIFIERB-ID2304859,JE-NL1279367,TJE-NL0169291,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,-13626.93,0.0,NaN,13626.93,-3406.73,NaN,NaN,-13626.92,VAT,Domestic 25%
14551,GBTICJE-IDENTIFIERB-ID2304878,JE-NL1279388,TJE-NL0169312,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,-2232.54,0.0,NaN,2232.54,-558.14,NaN,NaN,-2232.56,VAT,Domestic 25%
14552,GBTICJE-IDENTIFIERB-ID2304896,JE-NL1279405,TJE-NL0169329,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,-1677.03,0.0,NaN,1677.03,-419.26,NaN,NaN,-1677.04,VAT,Domestic 25%
14553,GBTICJE-IDENTIFIERH-ID2305279,JE-NL1279455,TJE-NL0169379,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,NaN,0.0,NaN,-3077.97,769.49,NaN,NaN,3077.96,VAT,Domestic 25%
14554,GBTICJE-IDENTIFIERH-ID2305297,JE-NL1279473,TJE-NL0169397,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,NaN,0.0,NaN,-2064.09,516.02,NaN,NaN,2064.08,VAT,Domestic 25%

In [45]:
import numpy as np

In [46]:
#mask3 = vat['External ID'].str.match("GBTICJE")
#vat['Comment'] = np.where(vat['External ID'] == 'GBTICJE','pp',vat['Comment'] )
#vat.iloc[4:]

In [47]:
vat['External ID'].str.match("GBTICJE")

0        False
1        False
2        False
3        False
4        False
         ...
14550     True
14551     True
14552     True
14553     True
14554     True
Name: External ID, Length: 14486, dtype: bool

In [48]:
14550 in vat.index

True

In [49]:
vat.insert(0, column = "External name", value = vat['External ID'].str.extract('([A-Z]\w{0,})', expand=True))

In [50]:
#store = vat['Sum of VAT'].notnull()
#store1 = vat['Comment'] == "VAT"
#vat[store & store1]
#vat['Comment'] = np.where(vat['External name'] == 'GBTICJE','Reverse charge + IC',vat['Comment'] )
#vat.iloc[4:]
#vat[vat["Comment"] == "Reverse charge + IC"]

In [51]:
vat.loc[#(vat['Sum of VAT'].notnull()) &
        #(vat['Sum of VAT'] != 0) & You can use the above mentioned condition with AND when same column because they !=
        ((vat['Sum of VAT'].notnull()) | (vat['Sum of VAT'] != 0)) &
        (vat['Comment'] == "VAT") &
        (vat['External name'] == 'GBTICJE'), "Comment"] = 'Reverse charge booked automatically in Netsuite'
vat[vat["Comment"] == "Reverse charge booked automatically in Netsuite"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type
7195,GBTICJE,GBTICJE-IDENTIFIERB-ID2280561,JE-NL1276976,TJE-NL0166900,,Journal,8/17/2020,Aug-20,- None -,NaN,...,-65982.75,0.0,NaN,65982.75,-16495.69,NaN,NaN,-65982.76,Reverse charge booked automatically in Netsuite,Domestic 25%
7196,GBTICJE,GBTICJE-IDENTIFIERB-ID2280559,JE-NL1276978,TJE-NL0166902,,Journal,8/17/2020,Aug-20,- None -,NaN,...,-16006.67,0.0,NaN,16006.67,-4001.67,NaN,NaN,-16006.68,Reverse charge booked automatically in Netsuite,Domestic 25%
7197,GBTICJE,GBTICJE-IDENTIFIERB-ID2280748,JE-NL1276989,TJE-NL0166913,,Journal,8/17/2020,Aug-20,- None -,NaN,...,-20497.25,0.0,NaN,20497.25,-5124.31,NaN,NaN,-20497.24,Reverse charge booked automatically in Netsuite,Domestic 25%
7198,GBTICJE,GBTICJE-IDENTIFIERB-ID2280749,JE-NL1276990,TJE-NL0166915,,Journal,8/17/2020,Aug-20,- None -,NaN,...,-20497.25,0.0,NaN,20497.25,-5124.31,NaN,NaN,-20497.24,Reverse charge booked automatically in Netsuite,Domestic 25%
7199,GBTICJE,GBTICJE-IDENTIFIERB-ID2280755,JE-NL1276991,TJE-NL0166914,,Journal,8/17/2020,Aug-20,- None -,NaN,...,-20577.00,0.0,NaN,20577.00,-5144.25,NaN,NaN,-20577.00,Reverse charge booked automatically in Netsuite,Domestic 25%
7200,GBTICJE,GBTICJE-IDENTIFIERH-ID2281056,JE-NL1277042,TJE-NL0166966,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,NaN,NaN,-113.30,NaN,NaN,-453.20,Reverse charge booked automatically in Netsuite,Domestic 25%
14307,GBTICJE,GBTICJE-IDENTIFIERG-ID2295056,JE-DK0302539,TJE-DK0302539,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-7931.73,0.0,NaN,7931.73,-1982.93,NaN,NaN,-7931.72,Reverse charge booked automatically in Netsuite,Domestic 25%
14518,GBTICJE,GBTICJE-IDENTIFIERB-ID2291560,JE-NL1277451,TJE-NL0167375,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-10459.31,0.0,NaN,10459.31,-2614.83,NaN,NaN,-10459.32,Reverse charge booked automatically in Netsuite,Domestic 25%
14519,GBTICJE,GBTICJE-IDENTIFIERB-ID2291557,JE-NL1277454,TJE-NL0167378,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-12604.36,0.0,NaN,12604.36,-3151.09,NaN,NaN,-12604.36,Reverse charge booked automatically in Netsuite,Domestic 25%
14520,GBTICJE,GBTICJE-IDENTIFIERB-ID2291621,JE-NL1277512,TJE-NL0167436,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-732.16,0.0,NaN,732.16,-183.04,NaN,NaN,-732.16,Reverse charge booked automatically in Netsuite,Domestic 25%
14521,GBTICJE,GBTICJE-IDENTIFIERB-ID2291622,JE-NL1277514,TJE-NL0167438,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-882.31,0.0,NaN,882.31,-220.58,NaN,NaN,-882.32,Reverse charge booked automatically in Netsuite,Domestic 25%
14528,GBTICJE,GBTICJE-IDENTIFIERB-ID2294757,JE-NL1277948,TJE-NL0167872,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-6625.72,0.0,NaN,6625.72,-1656.43,NaN,NaN,-6625.72,Reverse charge booked automatically in Netsuite,Domestic 25%
14529,GBTICJE,GBTICJE-IDENTIFIERB-ID2299077,JE-NL1278631,TJE-NL0168555,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-3077.97,0.0,NaN,3077.97,-769.49,NaN,NaN,-3077.96,Reverse charge booked automatically in Netsuite,Domestic 25%
14530,GBTICJE,GBTICJE-IDENTIFIERB-ID2299094,JE-NL1278648,TJE-NL0168572,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-2064.09,0.0,NaN,2064.09,-516.02,NaN,NaN,-2064.08,Reverse charge booked automatically in Netsuite,Domestic 25%
14545,GBTICJE,GBTICJE-IDENTIFIERB-ID2301160,JE-NL1279027,TJE-NL0168951,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-1443.82,0.0,NaN,1443.82,-360.96,NaN,NaN,-1443.84,Reverse charge booked automatically in Netsuite,Domestic 25%
14546,GBTICJE,GBTICJE-IDENTIFIERB-ID2301171,JE-NL1279032,TJE-NL0168956,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-504.52,0.0,NaN,504.52,-126.13,NaN,NaN,-504.52,Reverse charge booked automatically in Netsuite,Domestic 25%
14547,GBTICJE,GBTICJE-IDENTIFIERB-ID2301200,JE-NL1279065,TJE-NL0168989,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-33362.69,0.0,NaN,33362.69,-8340.67,NaN,NaN,-33362.68,Reverse charge booked automatically in Netsuite,Domestic 25%
14548,GBTICJE,GBTICJE-IDENTIFIERB-ID2301201,JE-NL1279066,TJE-NL0168990,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-17131.49,0.0,NaN,17131.49,-4282.87,NaN,NaN,-17131.48,Reverse charge booked automatically in Netsuite,Domestic 25%
14549,GBTICJE,GBTICJE-IDENTIFIERB-ID2301202,JE-NL1279068,TJE-NL0168992,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-3864.38,0.0,NaN,3864.38,-966.10,NaN,NaN,-3864.40,Reverse charge booked automatically in Netsuite,Domestic 25%
14550,GBTICJE,GBTICJE-IDENTIFIERB-ID2304859,JE-NL1279367,TJE-NL0169291,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-13626.93,0.0,NaN,13626.93,-3406.73,NaN,NaN,-13626.92,Reverse charge booked automatically in Netsuite,Domestic 25%
14551,GBTICJE,GBTICJE-IDENTIFIERB-ID2304878,JE-NL1279388,TJE-NL0169312,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-2232.54,0.0,NaN,2232.54,-558.14,NaN,NaN,-2232.56,Reverse charge booked automatically in Netsuite,Domestic 25%
14552,GBTICJE,GBTICJE-IDENTIFIERB-ID2304896,JE-NL1279405,TJE-NL0169329,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-1677.03,0.0,NaN,1677.03,-419.26,NaN,NaN,-1677.04,Reverse charge booked automatically in Netsuite,Domestic 25%
14553,GBTICJE,GBTICJE-IDENTIFIERH-ID2305279,JE-NL1279455,TJE-NL0169379,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,0.0,NaN,-3077.97,769.49,NaN,NaN,3077.96,Reverse charge booked automatically in Netsuite,Domestic 25%
14554,GBTICJE,GBTICJE-IDENTIFIERH-ID2305297,JE-NL1279473,TJE-NL0169397,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,0.0,NaN,-2064.09,516.02,NaN,NaN,2064.08,Reverse charge booked automatically in Netsuite,Domestic 25%

In [52]:
vat.loc[#(vat['Sum of VAT'].notnull()) &
        #(vat['Sum of VAT'] != 0) &
        ((vat['Sum of VAT'].notnull()) | (vat['Sum of VAT'] != 0)) &
        (vat['Comment'] == 'Reverse charge booked automatically in Netsuite') &
        (vat['External name'] == 'GBTICJE'), "Transaction type"] = 'Reverse charge'
vat[vat["Comment"] == "Reverse charge booked automatically in Netsuite"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type
7195,GBTICJE,GBTICJE-IDENTIFIERB-ID2280561,JE-NL1276976,TJE-NL0166900,,Journal,8/17/2020,Aug-20,- None -,NaN,...,-65982.75,0.0,NaN,65982.75,-16495.69,NaN,NaN,-65982.76,Reverse charge booked automatically in Netsuite,Reverse charge
7196,GBTICJE,GBTICJE-IDENTIFIERB-ID2280559,JE-NL1276978,TJE-NL0166902,,Journal,8/17/2020,Aug-20,- None -,NaN,...,-16006.67,0.0,NaN,16006.67,-4001.67,NaN,NaN,-16006.68,Reverse charge booked automatically in Netsuite,Reverse charge
7197,GBTICJE,GBTICJE-IDENTIFIERB-ID2280748,JE-NL1276989,TJE-NL0166913,,Journal,8/17/2020,Aug-20,- None -,NaN,...,-20497.25,0.0,NaN,20497.25,-5124.31,NaN,NaN,-20497.24,Reverse charge booked automatically in Netsuite,Reverse charge
7198,GBTICJE,GBTICJE-IDENTIFIERB-ID2280749,JE-NL1276990,TJE-NL0166915,,Journal,8/17/2020,Aug-20,- None -,NaN,...,-20497.25,0.0,NaN,20497.25,-5124.31,NaN,NaN,-20497.24,Reverse charge booked automatically in Netsuite,Reverse charge
7199,GBTICJE,GBTICJE-IDENTIFIERB-ID2280755,JE-NL1276991,TJE-NL0166914,,Journal,8/17/2020,Aug-20,- None -,NaN,...,-20577.00,0.0,NaN,20577.00,-5144.25,NaN,NaN,-20577.00,Reverse charge booked automatically in Netsuite,Reverse charge
7200,GBTICJE,GBTICJE-IDENTIFIERH-ID2281056,JE-NL1277042,TJE-NL0166966,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,NaN,NaN,-113.30,NaN,NaN,-453.20,Reverse charge booked automatically in Netsuite,Reverse charge
14307,GBTICJE,GBTICJE-IDENTIFIERG-ID2295056,JE-DK0302539,TJE-DK0302539,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-7931.73,0.0,NaN,7931.73,-1982.93,NaN,NaN,-7931.72,Reverse charge booked automatically in Netsuite,Reverse charge
14518,GBTICJE,GBTICJE-IDENTIFIERB-ID2291560,JE-NL1277451,TJE-NL0167375,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-10459.31,0.0,NaN,10459.31,-2614.83,NaN,NaN,-10459.32,Reverse charge booked automatically in Netsuite,Reverse charge
14519,GBTICJE,GBTICJE-IDENTIFIERB-ID2291557,JE-NL1277454,TJE-NL0167378,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-12604.36,0.0,NaN,12604.36,-3151.09,NaN,NaN,-12604.36,Reverse charge booked automatically in Netsuite,Reverse charge
14520,GBTICJE,GBTICJE-IDENTIFIERB-ID2291621,JE-NL1277512,TJE-NL0167436,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-732.16,0.0,NaN,732.16,-183.04,NaN,NaN,-732.16,Reverse charge booked automatically in Netsuite,Reverse charge
14521,GBTICJE,GBTICJE-IDENTIFIERB-ID2291622,JE-NL1277514,TJE-NL0167438,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-882.31,0.0,NaN,882.31,-220.58,NaN,NaN,-882.32,Reverse charge booked automatically in Netsuite,Reverse charge
14528,GBTICJE,GBTICJE-IDENTIFIERB-ID2294757,JE-NL1277948,TJE-NL0167872,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-6625.72,0.0,NaN,6625.72,-1656.43,NaN,NaN,-6625.72,Reverse charge booked automatically in Netsuite,Reverse charge
14529,GBTICJE,GBTICJE-IDENTIFIERB-ID2299077,JE-NL1278631,TJE-NL0168555,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-3077.97,0.0,NaN,3077.97,-769.49,NaN,NaN,-3077.96,Reverse charge booked automatically in Netsuite,Reverse charge
14530,GBTICJE,GBTICJE-IDENTIFIERB-ID2299094,JE-NL1278648,TJE-NL0168572,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-2064.09,0.0,NaN,2064.09,-516.02,NaN,NaN,-2064.08,Reverse charge booked automatically in Netsuite,Reverse charge
14545,GBTICJE,GBTICJE-IDENTIFIERB-ID2301160,JE-NL1279027,TJE-NL0168951,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-1443.82,0.0,NaN,1443.82,-360.96,NaN,NaN,-1443.84,Reverse charge booked automatically in Netsuite,Reverse charge
14546,GBTICJE,GBTICJE-IDENTIFIERB-ID2301171,JE-NL1279032,TJE-NL0168956,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-504.52,0.0,NaN,504.52,-126.13,NaN,NaN,-504.52,Reverse charge booked automatically in Netsuite,Reverse charge
14547,GBTICJE,GBTICJE-IDENTIFIERB-ID2301200,JE-NL1279065,TJE-NL0168989,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-33362.69,0.0,NaN,33362.69,-8340.67,NaN,NaN,-33362.68,Reverse charge booked automatically in Netsuite,Reverse charge
14548,GBTICJE,GBTICJE-IDENTIFIERB-ID2301201,JE-NL1279066,TJE-NL0168990,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-17131.49,0.0,NaN,17131.49,-4282.87,NaN,NaN,-17131.48,Reverse charge booked automatically in Netsuite,Reverse charge
14549,GBTICJE,GBTICJE-IDENTIFIERB-ID2301202,JE-NL1279068,TJE-NL0168992,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-3864.38,0.0,NaN,3864.38,-966.10,NaN,NaN,-3864.40,Reverse charge booked automatically in Netsuite,Reverse charge
14550,GBTICJE,GBTICJE-IDENTIFIERB-ID2304859,JE-NL1279367,TJE-NL0169291,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-13626.93,0.0,NaN,13626.93,-3406.73,NaN,NaN,-13626.92,Reverse charge booked automatically in Netsuite,Reverse charge
14551,GBTICJE,GBTICJE-IDENTIFIERB-ID2304878,JE-NL1279388,TJE-NL0169312,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-2232.54,0.0,NaN,2232.54,-558.14,NaN,NaN,-2232.56,Reverse charge booked automatically in Netsuite,Reverse charge
14552,GBTICJE,GBTICJE-IDENTIFIERB-ID2304896,JE-NL1279405,TJE-NL0169329,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-1677.03,0.0,NaN,1677.03,-419.26,NaN,NaN,-1677.04,Reverse charge booked automatically in Netsuite,Reverse charge
14553,GBTICJE,GBTICJE-IDENTIFIERH-ID2305279,JE-NL1279455,TJE-NL0169379,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,0.0,NaN,-3077.97,769.49,NaN,NaN,3077.96,Reverse charge booked automatically in Netsuite,Reverse charge
14554,GBTICJE,GBTICJE-IDENTIFIERH-ID2305297,JE-NL1279473,TJE-NL0169397,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,0.0,NaN,-2064.09,516.02,NaN,NaN,2064.08,Reverse charge booked automatically in Netsuite,Reverse charge

In [53]:
vat.loc[#(vat['Sum of VAT'].notnull()) &
        #(vat['Sum of VAT'] != 0) &
        ((vat['Sum of VAT'].notnull()) | (vat['Sum of VAT'] != 0)) &
        (vat['Comment'] == "VAT") &
        (vat['Source System'] == 'Hotel Comm'), "Comment"] = 'Hotel Commission'
vat[vat["Comment"] == "Hotel Commission"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type
1609,None,- None -,JE-DK0299366,TJE-DK0299366,,Journal,8/5/2020,Aug-20,- None -,NaN,...,NaN,0.0,-29063.23,NaN,-3096.60,0.106547,-29063.23,-12386.40,Hotel Commission,Domestic 25%
4832,None,- None -,JE-DK0300160,TJE-DK0300160,,Journal,8/12/2020,Aug-20,- None -,NaN,...,NaN,0.0,-9437.29,NaN,-767.75,0.081353,-9437.29,-3071.00,Hotel Commission,Domestic 25%
8426,None,- None -,JE-DK0300890,TJE-DK0300890,,Journal,8/19/2020,Aug-20,- None -,NaN,...,NaN,0.0,-5302.00,NaN,-576.42,0.108717,-5302.00,-2305.68,Hotel Commission,Domestic 25%
11912,None,- None -,JE-DK0301761,TJE-DK0301761,,Journal,8/26/2020,Aug-20,- None -,NaN,...,NaN,0.0,-6875.15,NaN,-364.20,0.052973,-6875.15,-1456.80,Hotel Commission,Domestic 25%

In [54]:
vat.iloc[4:]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type
4,None,- None -,31331755,BL-DK0409712,,Bill,2/29/2020,Aug-20,Due on receipt,2/29/2020,...,-90.00,NaN,NaN,90.00,NaN,NaN,NaN,NaN,Transactions 0DKK,None
5,None,- None -,31898105,BL-DK0409840,,Bill,2/29/2020,Aug-20,Net 30,3/30/2020,...,-348125.00,NaN,NaN,278500.00,NaN,NaN,NaN,NaN,Transactions 0DKK,None
6,None,- None -,640012494,BL-DK0409835,,Bill,3/3/2020,Aug-20,Net 15,3/18/2020,...,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transactions 0DKK,None
7,None,- None -,640012755,BL-DK0409832,,Bill,4/2/2020,Aug-20,Net 15,4/17/2020,...,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transactions 0DKK,None
8,None,- None -,640012916,BL-DK0409833,,Bill,5/5/2020,Aug-20,Net 15,5/20/2020,...,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transactions 0DKK,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14550,GBTICJE,GBTICJE-IDENTIFIERB-ID2304859,JE-NL1279367,TJE-NL0169291,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-13626.93,0.0,NaN,13626.93,-3406.73,NaN,NaN,-13626.92,Reverse charge booked automatically in Netsuite,Reverse charge
14551,GBTICJE,GBTICJE-IDENTIFIERB-ID2304878,JE-NL1279388,TJE-NL0169312,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-2232.54,0.0,NaN,2232.54,-558.14,NaN,NaN,-2232.56,Reverse charge booked automatically in Netsuite,Reverse charge
14552,GBTICJE,GBTICJE-IDENTIFIERB-ID2304896,JE-NL1279405,TJE-NL0169329,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-1677.03,0.0,NaN,1677.03,-419.26,NaN,NaN,-1677.04,Reverse charge booked automatically in Netsuite,Reverse charge
14553,GBTICJE,GBTICJE-IDENTIFIERH-ID2305279,JE-NL1279455,TJE-NL0169379,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,0.0,NaN,-3077.97,769.49,NaN,NaN,3077.96,Reverse charge booked automatically in Netsuite,Reverse charge
14554,GBTICJE,GBTICJE-IDENTIFIERH-ID2305297,JE-NL1279473,TJE-NL0169397,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,0.0,NaN,-2064.09,516.02,NaN,NaN,2064.08,Reverse charge booked automatically in Netsuite,Reverse charge

In [55]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        #(vat['Sum of VAT'].isnull()) &
        #(vat['Sum of VAT'] == 0) & you cannot use AND for 0 and null values in same column when you both condition are equal to
        (vat['Comment'] == "Transactions 0DKK") &
        (vat['Source System'] == 'Procurement'), "Comment"] = 'Procurement inv'
vat[vat["Comment"] == "Procurement inv"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type
0,None,- None -,31298815,BL-DK0409713,,Bill,11/6/2019,Aug-20,Due on receipt,11/6/2019,...,-2480.00,NaN,NaN,2480.00,NaN,NaN,NaN,NaN,Procurement inv,None
1,None,- None -,31307391,BL-DK0409710,,Bill,11/30/2019,Aug-20,Due on receipt,11/30/2019,...,-135.00,NaN,NaN,135.00,NaN,NaN,NaN,NaN,Procurement inv,None
2,None,- None -,31315780,BL-DK0409711,,Bill,12/31/2019,Aug-20,Due on receipt,12/31/2019,...,-135.00,NaN,NaN,135.00,NaN,NaN,NaN,NaN,Procurement inv,None
3,None,- None -,640012345,BL-DK0409836,,Bill,2/4/2020,Aug-20,Net 15,2/19/2020,...,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Procurement inv,None
4,None,- None -,31331755,BL-DK0409712,,Bill,2/29/2020,Aug-20,Due on receipt,2/29/2020,...,-90.00,NaN,NaN,90.00,NaN,NaN,NaN,NaN,Procurement inv,None
5,None,- None -,31898105,BL-DK0409840,,Bill,2/29/2020,Aug-20,Net 30,3/30/2020,...,-348125.00,NaN,NaN,278500.00,NaN,NaN,NaN,NaN,Procurement inv,None
6,None,- None -,640012494,BL-DK0409835,,Bill,3/3/2020,Aug-20,Net 15,3/18/2020,...,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Procurement inv,None
7,None,- None -,640012755,BL-DK0409832,,Bill,4/2/2020,Aug-20,Net 15,4/17/2020,...,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Procurement inv,None
8,None,- None -,640012916,BL-DK0409833,,Bill,5/5/2020,Aug-20,Net 15,5/20/2020,...,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Procurement inv,None
11,None,- None -,602988936,BL-DK0409843,,Bill,5/6/2020,Aug-20,Net 15,5/21/2020,...,-2355.18,NaN,NaN,1884.14,NaN,NaN,NaN,NaN,Procurement inv,None
12,None,- None -,152,BL-DK0409828,,Bill,5/11/2020,Aug-20,Net 15,5/26/2020,...,-125.65,NaN,NaN,100.52,NaN,NaN,NaN,NaN,Procurement inv,None
24,None,- None -,640013059,BL-DK0409834,,Bill,6/2/2020,Aug-20,Net 15,6/17/2020,...,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Procurement inv,None
25,None,- None -,151,BL-DK0409829,,Bill,6/8/2020,Aug-20,Net 15,6/23/2020,...,-119.45,NaN,NaN,95.56,NaN,NaN,NaN,NaN,Procurement inv,None
38,None,- None -,150,BL-DK0409830,,Bill,7/1/2020,Aug-20,Net 15,7/16/2020,...,-278.42,NaN,NaN,222.74,NaN,NaN,NaN,NaN,Procurement inv,None
40,None,- None -,640013309,BL-DK0409704,,Bill,7/2/2020,Aug-20,Net 15,7/17/2020,...,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Procurement inv,None
47,None,- None -,584423507,BL-DK0409647,,Bill,7/13/2020,Aug-20,Net 15,7/28/2020,...,-10533.68,NaN,NaN,8426.94,NaN,NaN,NaN,NaN,Procurement inv,None
56,None,- None -,199159,BL-DK0409692,,Bill,7/17/2020,Aug-20,Net 15,8/1/2020,...,-8392.50,NaN,NaN,6714.00,NaN,NaN,NaN,NaN,Procurement inv,None
59,None,- None -,CPH1853433,BL-DK0409658,,Bill,7/20/2020,Aug-20,Net 15,8/4/2020,...,-271.66,NaN,NaN,217.33,NaN,NaN,NaN,NaN,Procurement inv,None
68,None,- None -,273475,BL-DK0409648,,Bill,7/24/2020,Aug-20,Net 14,8/7/2020,...,-1525.00,NaN,NaN,1220.00,NaN,NaN,NaN,NaN,Procurement inv,None
69,None,- None -,6710014665,BL-DK0409841,,Bill,7/24/2020,Aug-20,Due on receipt,7/24/2020,...,-7950.99,NaN,NaN,7950.99,NaN,NaN,NaN,NaN,Procurement inv,None
87,None,- None -,140652,BL-DK0409693,,Bill,7/31/2020,Aug-20,Net 60,9/29/2020,...,-1328.13,NaN,NaN,1062.50,NaN,NaN,NaN,NaN,Procurement inv,None
92,None,- None -,26245,BL-DK0409781,,Bill,7/31/2020,Aug-20,Net 10,8/10/2020,...,-649.69,NaN,NaN,519.75,NaN,NaN,NaN,NaN,Procurement inv,None
93,None,- None -,508812,BL-DK0409780,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,-17166.21,NaN,NaN,17166.21,NaN,NaN,NaN,NaN,Procurement inv,None
94,None,- None -,508813,BL-DK0409779,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,-7369.55,NaN,NaN,7369.55,NaN,NaN,NaN,NaN,Procurement inv,None
95,None,- None -,508814,BL-DK0409776,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,-9877.43,NaN,NaN,9877.43,NaN,NaN,NaN,NaN,Procurement inv,None
96,None,- None -,508815,BL-DK0409775,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,-1902.68,NaN,NaN,1902.68,NaN,NaN,NaN,NaN,Procurement inv,None
97,None,- None -,508816,BL-DK0409774,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,-61.41,NaN,NaN,61.41,NaN,NaN,NaN,NaN,Procurement inv,None
98,None,- None -,508817,BL-DK0409778,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,-20896.77,NaN,NaN,20896.77,NaN,NaN,NaN,NaN,Procurement inv,None
99,None,- None -,508818,BL-DK0409777,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,-33563.31,NaN,NaN,33563.31,NaN,NaN,NaN,NaN,Procurement inv,None
100,None,- None -,53702,BL-DK0409760,,Bill,7/31/2020,Aug-20,Net 20,8/20/2020,...,-2531.25,NaN,NaN,2025.00,NaN,NaN,NaN,NaN,Procurement inv,None
101,None,- None -,8037108,BL-DK0409744,,Bill,7/31/2020,Aug-20,Net 15,8/15/2020,...,-338.78,NaN,NaN,271.02,NaN,NaN,NaN,NaN,Procurement inv,None
102,None,- None -,202008001,BL-DK0409709,,Bill,8/1/2020,Aug-20,NET 8,8/1/2020,...,-323741.82,NaN,NaN,323741.82,NaN,NaN,NaN,NaN,Procurement inv,None
103,None,- None -,202008002,BL-DK0409708,,Bill,8/1/2020,Aug-20,NET 8,8/1/2020,...,-64748.36,NaN,NaN,64748.36,NaN,NaN,NaN,NaN,Procurement inv,None
372,None,- None -,4727,BL-DK0409691,,Bill,8/3/2020,Aug-20,Net 30,9/2/2020,...,-5786.41,NaN,NaN,5786.41,NaN,NaN,NaN,NaN,Procurement inv,None
749,None,- None -,4.46598E+12,BL-DK0409786,,Bill,8/4/2020,Aug-20,Net 15,8/19/2020,...,-260.76,NaN,NaN,208.60,NaN,NaN,NaN,NaN,Procurement inv,None
750,None,- None -,4.57498E+12,BL-DK0409785,,Bill,8/4/2020,Aug-20,Net 15,8/19/2020,...,-392.00,NaN,NaN,313.60,NaN,NaN,NaN,NaN,Procurement inv,None
751,None,- None -,4.58498E+12,BL-DK0409784,,Bill,8/4/2020,Aug-20,Net 15,8/19/2020,...,-548.00,NaN,NaN,458.40,NaN,NaN,NaN,NaN,Procurement inv,None
752,None,- None -,4.64498E+12,BL-DK0409783,,Bill,8/4/2020,Aug-20,Net 15,8/19/2020,...,-2527.74,NaN,NaN,2042.19,NaN,NaN,NaN,NaN,Procurement inv,None
754,None,- None -,4.95598E+12,BL-DK0409787,,Bill,8/4/2020,Aug-20,Net 15,8/19/2020,...,-662.88,NaN,NaN,530.30,NaN,NaN,NaN,NaN,Procurement inv,None
755,None,- None -,603167699,BL-DK0409831,,Bill,8/4/2020,Aug-20,Net 15,8/19/2020,...,-2246.25,NaN,NaN,1797.00,NaN,NaN,NaN,NaN,Procurement inv,None
1775,None,- None -,20173,BL-DK0409745,,Bill,8/6/2020,Aug-20,Net 30,9/5/2020,...,-882.00,NaN,NaN,705.69,NaN,NaN,NaN,NaN,Procurement inv,None
3760,None,- None -,613015752,BL-DK0409806,,Bill,8/11/2020,Aug-20,Net 15,8/26/2020,...,-3587.39,NaN,NaN,2869.91,NaN,NaN,NaN,NaN,Procurement inv,None
3761,None,- None -,613016059,BL-DK0409772,,Bill,8/11/2020,Aug-20,Net 15,8/26/2020,...,-7995.40,NaN,NaN,6396.32,NaN,NaN,NaN,NaN,Procurement inv,None
5561,None,- None -,47140,BL-DK0409807,,Bill,8/14/2020,Aug-20,Net 30,9/13/2020,...,-4643.75,NaN,NaN,3715.00,NaN,NaN,NaN,NaN,Procurement inv,None
7206,None,- None -,4376944,BL-DK0409815,,Bill,8/18/2020,Aug-20,Net 14,9/1/2020,...,-28389.16,NaN,NaN,22711.32,NaN,NaN,NaN,NaN,Procurement inv,None
7207,None,- None -,4376945,BL-DK0409816,,Bill,8/18/2020,Aug-20,Net 14,9/1/2020,...,-2882.10,NaN,NaN,2882.10,NaN,NaN,NaN,NaN,Procurement inv,None
7208,None,- None -,4376946,BL-DK0409817,,Bill,8/18/2020,Aug-20,Net 14,9/1/2020,...,-19003.89,NaN,NaN,15203.11,NaN,NaN,NaN,NaN,Procurement inv,None
7209,None,- None -,4376947,BL-DK0409818,,Bill,8/18/2020,Aug-20,Net 14,9/1/2020,...,-3461.16,NaN,NaN,3461.16,NaN,NaN,NaN,NaN,Procurement inv,None
8589,None,- None -,8037338,BL-DK0409844,,Bill,8/20/2020,Aug-20,Net 15,9/4/2020,...,-22851.25,NaN,NaN,22851.25,NaN,NaN,NaN,NaN,Procurement inv,None

In [56]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        #(vat['Sum of VAT'] == 0.00) &
        (vat['Comment'] == "Transactions 0DKK") &
        (vat['Source System'] == 'NEO'), "Comment"] = 'Neo Travel Expense no vat'
vat[vat["Comment"] == "Neo Travel Expense no vat"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type
1249,KDS_Exp_VB_369630,KDS_Exp_VB_369630,369630,BL-DK0409702,,Bill,8/5/2020,Aug-20,Due on receipt,8/5/2020,...,-373.00,NaN,NaN,335.70,NaN,NaN,NaN,NaN,Neo Travel Expense no vat,None
1777,KDS_Exp_VB_370683,KDS_Exp_VB_370683,370683,BL-DK0409707,,Bill,8/6/2020,Aug-20,Due on receipt,8/6/2020,...,-738.75,NaN,NaN,591.00,NaN,NaN,NaN,NaN,Neo Travel Expense no vat,None
3759,KDS_Exp_VB_371144,KDS_Exp_VB_371144,371144,BL-DK0409765,,Bill,8/11/2020,Aug-20,Due on receipt,8/11/2020,...,-36.25,NaN,NaN,36.25,NaN,NaN,NaN,NaN,Neo Travel Expense no vat,None
4954,KDS_Exp_VB_371602,KDS_Exp_VB_371602,371602,BL-DK0409771,,Bill,8/13/2020,Aug-20,Due on receipt,8/13/2020,...,-649.33,NaN,NaN,649.33,NaN,NaN,NaN,NaN,Neo Travel Expense no vat,None
8419,KDS_Exp_JE_372220__OOP,KDS_Exp_JE_372220__OOP,JE-DK0300742,TJE-DK0300742,,Journal,8/19/2020,Aug-20,- None -,NaN,...,NaN,-1448.90,NaN,1447.50,NaN,NaN,NaN,NaN,Neo Travel Expense no vat,None
9669,KDS_Exp_JE_372176__OOP,KDS_Exp_JE_372176__OOP,JE-DK0301047,TJE-DK0301047,,Journal,8/21/2020,Aug-20,- None -,NaN,...,NaN,-300.00,NaN,300.00,NaN,NaN,NaN,NaN,Neo Travel Expense no vat,None
11161,KDS_Exp_JE_372557__OOP,KDS_Exp_JE_372557__OOP,JE-DK0301428,TJE-DK0301428,,Journal,8/25/2020,Aug-20,- None -,NaN,...,NaN,-360.00,NaN,360.00,NaN,NaN,NaN,NaN,Neo Travel Expense no vat,None
11162,KDS_Exp_JE_372583__OOP,KDS_Exp_JE_372583__OOP,JE-DK0301429,TJE-DK0301429,,Journal,8/25/2020,Aug-20,- None -,NaN,...,NaN,-49.69,NaN,49.69,NaN,NaN,NaN,NaN,Neo Travel Expense no vat,None
11907,KDS_Exp_JE_372743__OOP,KDS_Exp_JE_372743__OOP,JE-DK0301535,TJE-DK0301535,,Journal,8/26/2020,Aug-20,- None -,NaN,...,NaN,-900.00,NaN,900.00,NaN,NaN,NaN,NaN,Neo Travel Expense no vat,None
13437,KDS_Exp_VB_371755,KDS_Exp_VB_371755,371755,BL-DK0409845,,Bill,8/29/2020,Aug-20,Due on receipt,8/29/2020,...,-627.74,NaN,NaN,627.74,NaN,NaN,NaN,NaN,Neo Travel Expense no vat,None
13528,KDS_Exp_JE_371755__OOP,KDS_Exp_JE_371755__OOP,JE-DK0302145,TJE-DK0302145,,Journal,8/29/2020,Aug-20,- None -,NaN,...,NaN,-3809.00,NaN,3745.20,NaN,NaN,NaN,NaN,Neo Travel Expense no vat,None

In [57]:
#excel_file = pd.ExcelWriter("Darko VAT3.xlsx")

#vat.to_excel(excel_file, sheet_name = "vat", index = False)

#excel_file.save()

In [58]:
#excel_file = pd.ExcelWriter("Darko VAT3.xlsx")

#vat.to_excel(excel_file, sheet_name = "vat", index = False)

#excel_file.save()

In [59]:
vat.loc[#((vat['Sum of VAT'].isnull()) | (vat['Sum of VAT'] == 0)) & this is goes trough each Row and uses OR when same column same effect as below code
        (vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comment'] == "Transactions 0DKK") &
        (vat['Type'].isin(['Bill', 'Bill Credit'])) &
        (~vat['Maximum of Linked Invoice'].isin([np.nan, ' '])), 'Comment'] = 'Linked invoice'
vat[vat["Comment"] == "Linked invoice"]

Empty DataFrame
Columns: [External name, External ID, Document Number, Transaction Number, Maximum of Linked Invoice, Type, Date, Period, Terms, Maximum of Due Date/Receive By, Company Name, Customer VAT Registration Number, Bill to City, Bill to State, Bill to Country, Bill to Zip, Source System, Source System Identifier, City, State/Province, Country, Zip, Currency, Memo (Main), Maximum of GMAX Tax Code, Maximum of NetSuite Tax Item, Maximum of Coupa Tax Code, Maximum of External System Tax Code, Maximum of Tax Code (Consolidated), FOP Type, Sum of Assets, Sum of Accounts Payable, Sum of Other Liabilities, Sum of Income, Sum of Expense, Sum of VAT, VAT rate, Liab+Net Inc, Correct revenue, Comment, Transaction type]
Index: []

[0 rows x 41 columns]

In [60]:
#This column in CSV File is corrupt, you cannot fileter on - None - accurately

#vat.loc[#((vat['Sum of VAT'].isnull()) | (vat['Sum of VAT'] == 0)) &
        #(vat['Sum of VAT'].isin([np.nan, 0])) &
        #(vat['Comment'] == 'Transactions 0DKK') &
        #(vat['Memo (Main)'] != '- None -'), 'Comment'] = 'Travel bill'
        #(vat['Memo (Main)'].isin(['- None -'] ) == False), 'Comment'] = 'Travel bill'
        #(~vat['Memo (Main)'].isin(['- None -'])), 'Comment'] = 'Travel bill'
#vat[vat["Comment"] == "Travel bill"]
#vat[vat['Memo (Main)'] != '- None -']

In [61]:
vat.iloc[4:]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type
4,None,- None -,31331755,BL-DK0409712,,Bill,2/29/2020,Aug-20,Due on receipt,2/29/2020,...,-90.00,NaN,NaN,90.00,NaN,NaN,NaN,NaN,Procurement inv,None
5,None,- None -,31898105,BL-DK0409840,,Bill,2/29/2020,Aug-20,Net 30,3/30/2020,...,-348125.00,NaN,NaN,278500.00,NaN,NaN,NaN,NaN,Procurement inv,None
6,None,- None -,640012494,BL-DK0409835,,Bill,3/3/2020,Aug-20,Net 15,3/18/2020,...,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Procurement inv,None
7,None,- None -,640012755,BL-DK0409832,,Bill,4/2/2020,Aug-20,Net 15,4/17/2020,...,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Procurement inv,None
8,None,- None -,640012916,BL-DK0409833,,Bill,5/5/2020,Aug-20,Net 15,5/20/2020,...,-1683.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Procurement inv,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14550,GBTICJE,GBTICJE-IDENTIFIERB-ID2304859,JE-NL1279367,TJE-NL0169291,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-13626.93,0.0,NaN,13626.93,-3406.73,NaN,NaN,-13626.92,Reverse charge booked automatically in Netsuite,Reverse charge
14551,GBTICJE,GBTICJE-IDENTIFIERB-ID2304878,JE-NL1279388,TJE-NL0169312,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-2232.54,0.0,NaN,2232.54,-558.14,NaN,NaN,-2232.56,Reverse charge booked automatically in Netsuite,Reverse charge
14552,GBTICJE,GBTICJE-IDENTIFIERB-ID2304896,JE-NL1279405,TJE-NL0169329,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-1677.03,0.0,NaN,1677.03,-419.26,NaN,NaN,-1677.04,Reverse charge booked automatically in Netsuite,Reverse charge
14553,GBTICJE,GBTICJE-IDENTIFIERH-ID2305279,JE-NL1279455,TJE-NL0169379,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,0.0,NaN,-3077.97,769.49,NaN,NaN,3077.96,Reverse charge booked automatically in Netsuite,Reverse charge
14554,GBTICJE,GBTICJE-IDENTIFIERH-ID2305297,JE-NL1279473,TJE-NL0169397,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,0.0,NaN,-2064.09,516.02,NaN,NaN,2064.08,Reverse charge booked automatically in Netsuite,Reverse charge

In [62]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comment'] == 'Transactions 0DKK') &
        (vat['External name'] == 'GBTICJE') &
        (vat['Maximum of NetSuite Tax Item'].notnull()), 'Comment'] = 'IC invoice EU/Outside'
vat[vat["Comment"] == "IC invoice EU/Outside"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type
7038,GBTICJE,GBTICJE-IDENTIFIERA-ID2280758,JE-DK0300630,TJE-DK0300630,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-2240.42,NaN,0.0,-0.0,-2240.42,0.0,IC invoice EU/Outside,None
7039,GBTICJE,GBTICJE-IDENTIFIERA-ID2280759,JE-DK0300631,TJE-DK0300631,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-809.04,NaN,0.0,-0.0,-809.04,0.0,IC invoice EU/Outside,None
7040,GBTICJE,GBTICJE-IDENTIFIERA-ID2280767,JE-DK0300632,TJE-DK0300632,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-2707.17,NaN,0.0,-0.0,-2707.17,0.0,IC invoice EU/Outside,None
7041,GBTICJE,GBTICJE-IDENTIFIERA-ID2280760,JE-DK0300633,TJE-DK0300633,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-1991.48,NaN,0.0,-0.0,-1991.48,0.0,IC invoice EU/Outside,None
7042,GBTICJE,GBTICJE-IDENTIFIERA-ID2280761,JE-DK0300634,TJE-DK0300634,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-217.82,NaN,0.0,-0.0,-217.82,0.0,IC invoice EU/Outside,None
7043,GBTICJE,GBTICJE-IDENTIFIERA-ID2280763,JE-DK0300635,TJE-DK0300635,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-403679.89,NaN,0.0,-0.0,-403679.89,0.0,IC invoice EU/Outside,None
7044,GBTICJE,GBTICJE-IDENTIFIERA-ID2280762,JE-DK0300636,TJE-DK0300636,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-116750.71,NaN,0.0,-0.0,-116750.71,0.0,IC invoice EU/Outside,None
7045,GBTICJE,GBTICJE-IDENTIFIERA-ID2280764,JE-DK0300637,TJE-DK0300637,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-6285.62,NaN,0.0,-0.0,-6285.62,0.0,IC invoice EU/Outside,None
7046,GBTICJE,GBTICJE-IDENTIFIERA-ID2280765,JE-DK0300638,TJE-DK0300638,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-373.40,NaN,0.0,-0.0,-373.40,0.0,IC invoice EU/Outside,None
7047,GBTICJE,GBTICJE-IDENTIFIERA-ID2280766,JE-DK0300639,TJE-DK0300639,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-65283.31,NaN,0.0,-0.0,-65283.31,0.0,IC invoice EU/Outside,None
7048,GBTICJE,GBTICJE-IDENTIFIERA-ID2280769,JE-DK0300640,TJE-DK0300640,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-11139.86,NaN,0.0,-0.0,-11139.86,0.0,IC invoice EU/Outside,None
7049,GBTICJE,GBTICJE-IDENTIFIERA-ID2280768,JE-DK0300641,TJE-DK0300641,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-3609.56,NaN,0.0,-0.0,-3609.56,0.0,IC invoice EU/Outside,None
7050,GBTICJE,GBTICJE-IDENTIFIERA-ID2280770,JE-DK0300642,TJE-DK0300642,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-11980.02,NaN,0.0,-0.0,-11980.02,0.0,IC invoice EU/Outside,None
7051,GBTICJE,GBTICJE-IDENTIFIERA-ID2280771,JE-DK0300643,TJE-DK0300643,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-27040.61,NaN,0.0,-0.0,-27040.61,0.0,IC invoice EU/Outside,None
7052,GBTICJE,GBTICJE-IDENTIFIERA-ID2280772,JE-DK0300644,TJE-DK0300644,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-12602.36,NaN,0.0,-0.0,-12602.36,0.0,IC invoice EU/Outside,None
7053,GBTICJE,GBTICJE-IDENTIFIERA-ID2280773,JE-DK0300645,TJE-DK0300645,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-5943.33,NaN,0.0,-0.0,-5943.33,0.0,IC invoice EU/Outside,None
7054,GBTICJE,GBTICJE-IDENTIFIERA-ID2280774,JE-DK0300646,TJE-DK0300646,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-9957.42,NaN,0.0,-0.0,-9957.42,0.0,IC invoice EU/Outside,None
7055,GBTICJE,GBTICJE-IDENTIFIERA-ID2280775,JE-DK0300647,TJE-DK0300647,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-75085.14,NaN,0.0,-0.0,-75085.14,0.0,IC invoice EU/Outside,None
7056,GBTICJE,GBTICJE-IDENTIFIERA-ID2280777,JE-DK0300648,TJE-DK0300648,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-59028.81,NaN,0.0,-0.0,-59028.81,0.0,IC invoice EU/Outside,None
7057,GBTICJE,GBTICJE-IDENTIFIERA-ID2280778,JE-DK0300649,TJE-DK0300649,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-10486.40,NaN,0.0,-0.0,-10486.40,0.0,IC invoice EU/Outside,None
7058,GBTICJE,GBTICJE-IDENTIFIERA-ID2280779,JE-DK0300650,TJE-DK0300650,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-62.23,NaN,0.0,-0.0,-62.23,0.0,IC invoice EU/Outside,None
7059,GBTICJE,GBTICJE-IDENTIFIERA-ID2280781,JE-DK0300651,TJE-DK0300651,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-3018.34,NaN,0.0,-0.0,-3018.34,0.0,IC invoice EU/Outside,None
7060,GBTICJE,GBTICJE-IDENTIFIERA-ID2280776,JE-DK0300652,TJE-DK0300652,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-4947.59,NaN,0.0,-0.0,-4947.59,0.0,IC invoice EU/Outside,None
7061,GBTICJE,GBTICJE-IDENTIFIERA-ID2280782,JE-DK0300653,TJE-DK0300653,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-11980.02,NaN,0.0,-0.0,-11980.02,0.0,IC invoice EU/Outside,None
7062,GBTICJE,GBTICJE-IDENTIFIERA-ID2280784,JE-DK0300654,TJE-DK0300654,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-31210.28,NaN,0.0,-0.0,-31210.28,0.0,IC invoice EU/Outside,None
7063,GBTICJE,GBTICJE-IDENTIFIERA-ID2280785,JE-DK0300655,TJE-DK0300655,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-1213.56,NaN,0.0,-0.0,-1213.56,0.0,IC invoice EU/Outside,None
7064,GBTICJE,GBTICJE-IDENTIFIERA-ID2280786,JE-DK0300656,TJE-DK0300656,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-1711.43,NaN,0.0,-0.0,-1711.43,0.0,IC invoice EU/Outside,None
7065,GBTICJE,GBTICJE-IDENTIFIERA-ID2280780,JE-DK0300657,TJE-DK0300657,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-528.99,NaN,0.0,-0.0,-528.99,0.0,IC invoice EU/Outside,None
7066,GBTICJE,GBTICJE-IDENTIFIERA-ID2280788,JE-DK0300658,TJE-DK0300658,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-560.10,NaN,0.0,-0.0,-560.10,0.0,IC invoice EU/Outside,None
7067,GBTICJE,GBTICJE-IDENTIFIERA-ID2280789,JE-DK0300659,TJE-DK0300659,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-53676.70,NaN,0.0,-0.0,-53676.70,0.0,IC invoice EU/Outside,None
7068,GBTICJE,GBTICJE-IDENTIFIERA-ID2280783,JE-DK0300660,TJE-DK0300660,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-62.23,NaN,0.0,-0.0,-62.23,0.0,IC invoice EU/Outside,None
7069,GBTICJE,GBTICJE-IDENTIFIERA-ID2280790,JE-DK0300661,TJE-DK0300661,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-6472.32,NaN,0.0,-0.0,-6472.32,0.0,IC invoice EU/Outside,None
7070,GBTICJE,GBTICJE-IDENTIFIERA-ID2280791,JE-DK0300662,TJE-DK0300662,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-12789.06,NaN,0.0,-0.0,-12789.06,0.0,IC invoice EU/Outside,None
7071,GBTICJE,GBTICJE-IDENTIFIERA-ID2280792,JE-DK0300663,TJE-DK0300663,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-1618.08,NaN,0.0,-0.0,-1618.08,0.0,IC invoice EU/Outside,None
7072,GBTICJE,GBTICJE-IDENTIFIERA-ID2280793,JE-DK0300664,TJE-DK0300664,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-41198.81,NaN,0.0,-0.0,-41198.81,0.0,IC invoice EU/Outside,None
7073,GBTICJE,GBTICJE-IDENTIFIERA-ID2280794,JE-DK0300665,TJE-DK0300665,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-8526.04,NaN,0.0,-0.0,-8526.04,0.0,IC invoice EU/Outside,None
7074,GBTICJE,GBTICJE-IDENTIFIERA-ID2280787,JE-DK0300666,TJE-DK0300666,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-2147.07,NaN,0.0,-0.0,-2147.07,0.0,IC invoice EU/Outside,None

In [63]:
##Method to convert excel files to Csv files, use last months file and change the column names if does not match with below merge
read_file = pd.read_excel (r'C:\Users\darko\Desktop\pandas\VAT\test_sales_july.xlsx')
read_file.to_csv (r'C:\Users\darko\Desktop\pandas\VAT\test_sales_july2.csv', index = None, header=True)

In [64]:
csv=pd.read_csv('test_sales_july2.csv')

In [65]:
#Douplicates are created when matching both csv files, same principle as match in excel
vat = vat.merge(csv[['Sum of Income','Comment 2', 'VAT No', 'Comment 3']].drop_duplicates(), how='left', on='Sum of Income', suffixes=['', ' 3'])

In [66]:
vat[vat['Comment'] == 'IC invoice EU/Outside']

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type,Comment 2,VAT No,Comment 3
7003,GBTICJE,GBTICJE-IDENTIFIERA-ID2280758,JE-DK0300630,TJE-DK0300630,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-2240.42,0.0,IC invoice EU/Outside,None,APMM c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
7004,GBTICJE,GBTICJE-IDENTIFIERA-ID2280759,JE-DK0300631,TJE-DK0300631,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-809.04,0.0,IC invoice EU/Outside,None,APMM c-out from DK,FI02152075,IC Invoice - EU Sales
7005,GBTICJE,GBTICJE-IDENTIFIERA-ID2280767,JE-DK0300632,TJE-DK0300632,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-2707.17,0.0,IC invoice EU/Outside,None,Carlsberg c-out from DK,FI02152075,IC Invoice - EU Sales
7006,GBTICJE,GBTICJE-IDENTIFIERA-ID2280760,JE-DK0300633,TJE-DK0300633,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-1991.48,0.0,IC invoice EU/Outside,None,APMM c-out from DK,FR 15 304 475 338,IC Invoice - EU Sales
7007,GBTICJE,GBTICJE-IDENTIFIERA-ID2280761,JE-DK0300634,TJE-DK0300634,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-217.82,0.0,IC invoice EU/Outside,None,APMM c-out from DK,DE254337470,IC Invoice - EU Sales
7008,GBTICJE,GBTICJE-IDENTIFIERA-ID2280763,JE-DK0300635,TJE-DK0300635,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-403679.89,0.0,IC invoice EU/Outside,None,APMM c-out from DK,NO959209502,IC Invoice - Outside EU
7009,GBTICJE,GBTICJE-IDENTIFIERA-ID2280762,JE-DK0300636,TJE-DK0300636,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-116750.71,0.0,IC invoice EU/Outside,None,APMM c-out from DK,NL853361757B01,IC Invoice - EU Sales
7010,GBTICJE,GBTICJE-IDENTIFIERA-ID2280764,JE-DK0300637,TJE-DK0300637,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-6285.62,0.0,IC invoice EU/Outside,None,APMM c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7011,GBTICJE,GBTICJE-IDENTIFIERA-ID2280765,JE-DK0300638,TJE-DK0300638,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-373.40,0.0,IC invoice EU/Outside,None,APMM c-out from DK,CHE-300.737.496 MWST,IC Invoice - Outside EU
7012,GBTICJE,GBTICJE-IDENTIFIERA-ID2280766,JE-DK0300639,TJE-DK0300639,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-65283.31,0.0,IC invoice EU/Outside,None,APMM c-out from DK,GB 177248479,IC Invoice - EU Sales
7013,GBTICJE,GBTICJE-IDENTIFIERA-ID2280769,JE-DK0300640,TJE-DK0300640,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-11139.86,0.0,IC invoice EU/Outside,None,Carlsberg c-out from DK,NO959209502,IC Invoice - Outside EU
7014,GBTICJE,GBTICJE-IDENTIFIERA-ID2280768,JE-DK0300641,TJE-DK0300641,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-3609.56,0.0,IC invoice EU/Outside,None,Carlsberg c-out from DK,DE254337470,IC Invoice - EU Sales
7015,GBTICJE,GBTICJE-IDENTIFIERA-ID2280770,JE-DK0300642,TJE-DK0300642,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-11980.02,0.0,IC invoice EU/Outside,None,Carlsberg c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7016,GBTICJE,GBTICJE-IDENTIFIERA-ID2280771,JE-DK0300643,TJE-DK0300643,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-27040.61,0.0,IC invoice EU/Outside,None,Carlsberg c-out from DK,CHE-300.737.496 MWST,IC Invoice - Outside EU
7017,GBTICJE,GBTICJE-IDENTIFIERA-ID2280772,JE-DK0300644,TJE-DK0300644,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-12602.36,0.0,IC invoice EU/Outside,None,Carlsberg c-out from DK,GB 177248479,IC Invoice - EU Sales
7018,GBTICJE,GBTICJE-IDENTIFIERA-ID2280773,JE-DK0300645,TJE-DK0300645,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-5943.33,0.0,IC invoice EU/Outside,None,Danske Bank c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
7019,GBTICJE,GBTICJE-IDENTIFIERA-ID2280774,JE-DK0300646,TJE-DK0300646,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-9957.42,0.0,IC invoice EU/Outside,None,Danske Bank c-out from DK,FI02152075,IC Invoice - EU Sales
7020,GBTICJE,GBTICJE-IDENTIFIERA-ID2280775,JE-DK0300647,TJE-DK0300647,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-75085.14,0.0,IC invoice EU/Outside,None,Danske Bank c-out from DK,NO959209502,IC Invoice - Outside EU
7021,GBTICJE,GBTICJE-IDENTIFIERA-ID2280777,JE-DK0300648,TJE-DK0300648,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-59028.81,0.0,IC invoice EU/Outside,None,Danske Bank c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7022,GBTICJE,GBTICJE-IDENTIFIERA-ID2280778,JE-DK0300649,TJE-DK0300649,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-10486.40,0.0,IC invoice EU/Outside,None,Danske Bank c-out from DK,GB 177248479,IC Invoice - EU Sales
7023,GBTICJE,GBTICJE-IDENTIFIERA-ID2280779,JE-DK0300650,TJE-DK0300650,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-62.23,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
7024,GBTICJE,GBTICJE-IDENTIFIERA-ID2280781,JE-DK0300651,TJE-DK0300651,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-3018.34,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,FR 15 304 475 338,IC Invoice - EU Sales
7025,GBTICJE,GBTICJE-IDENTIFIERA-ID2280776,JE-DK0300652,TJE-DK0300652,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-4947.59,0.0,IC invoice EU/Outside,None,Danske Bank c-out from DK,PL 5252273929,IC Invoice - EU Sales
7026,GBTICJE,GBTICJE-IDENTIFIERA-ID2280782,JE-DK0300653,TJE-DK0300653,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-11980.02,0.0,IC invoice EU/Outside,None,Carlsberg c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7027,GBTICJE,GBTICJE-IDENTIFIERA-ID2280784,JE-DK0300654,TJE-DK0300654,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-31210.28,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,NL853361757B01,IC Invoice - EU Sales
7028,GBTICJE,GBTICJE-IDENTIFIERA-ID2280785,JE-DK0300655,TJE-DK0300655,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-1213.56,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,NO959209502,IC Invoice - Outside EU
7029,GBTICJE,GBTICJE-IDENTIFIERA-ID2280786,JE-DK0300656,TJE-DK0300656,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-1711.43,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,PL 5252273929,IC Invoice - EU Sales
7030,GBTICJE,GBTICJE-IDENTIFIERA-ID2280780,JE-DK0300657,TJE-DK0300657,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-528.99,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,CZ 02525071,IC Invoice - EU Sales
7031,GBTICJE,GBTICJE-IDENTIFIERA-ID2280788,JE-DK0300658,TJE-DK0300658,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-560.10,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7032,GBTICJE,GBTICJE-IDENTIFIERA-ID2280789,JE-DK0300659,TJE-DK0300659,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-53676.70,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,GB 177248479,IC Invoice - EU Sales
7033,GBTICJE,GBTICJE-IDENTIFIERA-ID2280783,JE-DK0300660,TJE-DK0300660,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-62.23,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
7034,GBTICJE,GBTICJE-IDENTIFIERA-ID2280790,JE-DK0300661,TJE-DK0300661,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-6472.32,0.0,IC invoice EU/Outside,None,Ramboll c-out from DK,FI02152075,IC Invoice - EU Sales
7035,GBTICJE,GBTICJE-IDENTIFIERA-ID2280791,JE-DK0300662,TJE-DK0300662,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-12789.06,0.0,IC invoice EU/Outside,None,Ramboll c-out from DK,NO959209502,IC Invoice - Outside EU
7036,GBTICJE,GBTICJE-IDENTIFIERA-ID2280792,JE-DK0300663,TJE-DK0300663,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-1618.08,0.0,IC invoice EU/Outside,None,Ramboll c-out from DK,DE254337470,IC Invoice - EU Sales
7037,GBTICJE,GBTICJE-IDENTIFIERA-ID2280793,JE-DK0300664,TJE-DK0300664,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-41198.81,0.0,IC invoice EU/Outside,None,Ramboll c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7038,GBTICJE,GBTICJE-IDENTIFIERA-ID2280794,JE-DK0300665,TJE-DK0300665,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-8526.04,0.0,IC invoice EU/Outside,None,Ramboll c-out from DK,GB 177248479,IC Invoice - EU Sales
7039,GBTICJE,GBTICJE-IDENTIFIERA-ID2280787,JE-DK0300666,TJE-DK0300666,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-2147.07,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,B85376630,IC Invoice - EU Sales

In [67]:
#Check manually if a new row is added!!!Then add a new comment in Comment 3
#vat.at[9501, 'Comment 3']='IC invoice EU/Outside'

In [68]:
#vat.iloc[9501]

In [69]:
vat[vat['Comment'] == 'IC invoice EU/Outside']

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type,Comment 2,VAT No,Comment 3
7003,GBTICJE,GBTICJE-IDENTIFIERA-ID2280758,JE-DK0300630,TJE-DK0300630,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-2240.42,0.0,IC invoice EU/Outside,None,APMM c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
7004,GBTICJE,GBTICJE-IDENTIFIERA-ID2280759,JE-DK0300631,TJE-DK0300631,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-809.04,0.0,IC invoice EU/Outside,None,APMM c-out from DK,FI02152075,IC Invoice - EU Sales
7005,GBTICJE,GBTICJE-IDENTIFIERA-ID2280767,JE-DK0300632,TJE-DK0300632,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-2707.17,0.0,IC invoice EU/Outside,None,Carlsberg c-out from DK,FI02152075,IC Invoice - EU Sales
7006,GBTICJE,GBTICJE-IDENTIFIERA-ID2280760,JE-DK0300633,TJE-DK0300633,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-1991.48,0.0,IC invoice EU/Outside,None,APMM c-out from DK,FR 15 304 475 338,IC Invoice - EU Sales
7007,GBTICJE,GBTICJE-IDENTIFIERA-ID2280761,JE-DK0300634,TJE-DK0300634,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-217.82,0.0,IC invoice EU/Outside,None,APMM c-out from DK,DE254337470,IC Invoice - EU Sales
7008,GBTICJE,GBTICJE-IDENTIFIERA-ID2280763,JE-DK0300635,TJE-DK0300635,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-403679.89,0.0,IC invoice EU/Outside,None,APMM c-out from DK,NO959209502,IC Invoice - Outside EU
7009,GBTICJE,GBTICJE-IDENTIFIERA-ID2280762,JE-DK0300636,TJE-DK0300636,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-116750.71,0.0,IC invoice EU/Outside,None,APMM c-out from DK,NL853361757B01,IC Invoice - EU Sales
7010,GBTICJE,GBTICJE-IDENTIFIERA-ID2280764,JE-DK0300637,TJE-DK0300637,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-6285.62,0.0,IC invoice EU/Outside,None,APMM c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7011,GBTICJE,GBTICJE-IDENTIFIERA-ID2280765,JE-DK0300638,TJE-DK0300638,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-373.40,0.0,IC invoice EU/Outside,None,APMM c-out from DK,CHE-300.737.496 MWST,IC Invoice - Outside EU
7012,GBTICJE,GBTICJE-IDENTIFIERA-ID2280766,JE-DK0300639,TJE-DK0300639,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-65283.31,0.0,IC invoice EU/Outside,None,APMM c-out from DK,GB 177248479,IC Invoice - EU Sales
7013,GBTICJE,GBTICJE-IDENTIFIERA-ID2280769,JE-DK0300640,TJE-DK0300640,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-11139.86,0.0,IC invoice EU/Outside,None,Carlsberg c-out from DK,NO959209502,IC Invoice - Outside EU
7014,GBTICJE,GBTICJE-IDENTIFIERA-ID2280768,JE-DK0300641,TJE-DK0300641,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-3609.56,0.0,IC invoice EU/Outside,None,Carlsberg c-out from DK,DE254337470,IC Invoice - EU Sales
7015,GBTICJE,GBTICJE-IDENTIFIERA-ID2280770,JE-DK0300642,TJE-DK0300642,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-11980.02,0.0,IC invoice EU/Outside,None,Carlsberg c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7016,GBTICJE,GBTICJE-IDENTIFIERA-ID2280771,JE-DK0300643,TJE-DK0300643,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-27040.61,0.0,IC invoice EU/Outside,None,Carlsberg c-out from DK,CHE-300.737.496 MWST,IC Invoice - Outside EU
7017,GBTICJE,GBTICJE-IDENTIFIERA-ID2280772,JE-DK0300644,TJE-DK0300644,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-12602.36,0.0,IC invoice EU/Outside,None,Carlsberg c-out from DK,GB 177248479,IC Invoice - EU Sales
7018,GBTICJE,GBTICJE-IDENTIFIERA-ID2280773,JE-DK0300645,TJE-DK0300645,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-5943.33,0.0,IC invoice EU/Outside,None,Danske Bank c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
7019,GBTICJE,GBTICJE-IDENTIFIERA-ID2280774,JE-DK0300646,TJE-DK0300646,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-9957.42,0.0,IC invoice EU/Outside,None,Danske Bank c-out from DK,FI02152075,IC Invoice - EU Sales
7020,GBTICJE,GBTICJE-IDENTIFIERA-ID2280775,JE-DK0300647,TJE-DK0300647,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-75085.14,0.0,IC invoice EU/Outside,None,Danske Bank c-out from DK,NO959209502,IC Invoice - Outside EU
7021,GBTICJE,GBTICJE-IDENTIFIERA-ID2280777,JE-DK0300648,TJE-DK0300648,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-59028.81,0.0,IC invoice EU/Outside,None,Danske Bank c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7022,GBTICJE,GBTICJE-IDENTIFIERA-ID2280778,JE-DK0300649,TJE-DK0300649,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-10486.40,0.0,IC invoice EU/Outside,None,Danske Bank c-out from DK,GB 177248479,IC Invoice - EU Sales
7023,GBTICJE,GBTICJE-IDENTIFIERA-ID2280779,JE-DK0300650,TJE-DK0300650,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-62.23,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
7024,GBTICJE,GBTICJE-IDENTIFIERA-ID2280781,JE-DK0300651,TJE-DK0300651,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-3018.34,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,FR 15 304 475 338,IC Invoice - EU Sales
7025,GBTICJE,GBTICJE-IDENTIFIERA-ID2280776,JE-DK0300652,TJE-DK0300652,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-4947.59,0.0,IC invoice EU/Outside,None,Danske Bank c-out from DK,PL 5252273929,IC Invoice - EU Sales
7026,GBTICJE,GBTICJE-IDENTIFIERA-ID2280782,JE-DK0300653,TJE-DK0300653,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-11980.02,0.0,IC invoice EU/Outside,None,Carlsberg c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7027,GBTICJE,GBTICJE-IDENTIFIERA-ID2280784,JE-DK0300654,TJE-DK0300654,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-31210.28,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,NL853361757B01,IC Invoice - EU Sales
7028,GBTICJE,GBTICJE-IDENTIFIERA-ID2280785,JE-DK0300655,TJE-DK0300655,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-1213.56,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,NO959209502,IC Invoice - Outside EU
7029,GBTICJE,GBTICJE-IDENTIFIERA-ID2280786,JE-DK0300656,TJE-DK0300656,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-1711.43,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,PL 5252273929,IC Invoice - EU Sales
7030,GBTICJE,GBTICJE-IDENTIFIERA-ID2280780,JE-DK0300657,TJE-DK0300657,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-528.99,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,CZ 02525071,IC Invoice - EU Sales
7031,GBTICJE,GBTICJE-IDENTIFIERA-ID2280788,JE-DK0300658,TJE-DK0300658,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-560.10,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7032,GBTICJE,GBTICJE-IDENTIFIERA-ID2280789,JE-DK0300659,TJE-DK0300659,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-53676.70,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,GB 177248479,IC Invoice - EU Sales
7033,GBTICJE,GBTICJE-IDENTIFIERA-ID2280783,JE-DK0300660,TJE-DK0300660,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-62.23,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
7034,GBTICJE,GBTICJE-IDENTIFIERA-ID2280790,JE-DK0300661,TJE-DK0300661,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-6472.32,0.0,IC invoice EU/Outside,None,Ramboll c-out from DK,FI02152075,IC Invoice - EU Sales
7035,GBTICJE,GBTICJE-IDENTIFIERA-ID2280791,JE-DK0300662,TJE-DK0300662,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-12789.06,0.0,IC invoice EU/Outside,None,Ramboll c-out from DK,NO959209502,IC Invoice - Outside EU
7036,GBTICJE,GBTICJE-IDENTIFIERA-ID2280792,JE-DK0300663,TJE-DK0300663,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-1618.08,0.0,IC invoice EU/Outside,None,Ramboll c-out from DK,DE254337470,IC Invoice - EU Sales
7037,GBTICJE,GBTICJE-IDENTIFIERA-ID2280793,JE-DK0300664,TJE-DK0300664,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-41198.81,0.0,IC invoice EU/Outside,None,Ramboll c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7038,GBTICJE,GBTICJE-IDENTIFIERA-ID2280794,JE-DK0300665,TJE-DK0300665,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-8526.04,0.0,IC invoice EU/Outside,None,Ramboll c-out from DK,GB 177248479,IC Invoice - EU Sales
7039,GBTICJE,GBTICJE-IDENTIFIERA-ID2280787,JE-DK0300666,TJE-DK0300666,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-2147.07,0.0,IC invoice EU/Outside,None,LEGO c-out from DK,B85376630,IC Invoice - EU Sales

In [70]:
#use na=False to avoid errors when filtering on IC
vat.loc[(vat['Comment'] == 'IC invoice EU/Outside'), 'Comment'] = vat['Comment 3']
vat[vat["Comment"].str.contains("IC", na=False)]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type,Comment 2,VAT No,Comment 3
7003,GBTICJE,GBTICJE-IDENTIFIERA-ID2280758,JE-DK0300630,TJE-DK0300630,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-2240.42,0.0,IC Invoice - EU Sales,None,APMM c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
7004,GBTICJE,GBTICJE-IDENTIFIERA-ID2280759,JE-DK0300631,TJE-DK0300631,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-809.04,0.0,IC Invoice - EU Sales,None,APMM c-out from DK,FI02152075,IC Invoice - EU Sales
7005,GBTICJE,GBTICJE-IDENTIFIERA-ID2280767,JE-DK0300632,TJE-DK0300632,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-2707.17,0.0,IC Invoice - EU Sales,None,Carlsberg c-out from DK,FI02152075,IC Invoice - EU Sales
7006,GBTICJE,GBTICJE-IDENTIFIERA-ID2280760,JE-DK0300633,TJE-DK0300633,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-1991.48,0.0,IC Invoice - EU Sales,None,APMM c-out from DK,FR 15 304 475 338,IC Invoice - EU Sales
7007,GBTICJE,GBTICJE-IDENTIFIERA-ID2280761,JE-DK0300634,TJE-DK0300634,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-217.82,0.0,IC Invoice - EU Sales,None,APMM c-out from DK,DE254337470,IC Invoice - EU Sales
7008,GBTICJE,GBTICJE-IDENTIFIERA-ID2280763,JE-DK0300635,TJE-DK0300635,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-403679.89,0.0,IC Invoice - Outside EU,None,APMM c-out from DK,NO959209502,IC Invoice - Outside EU
7009,GBTICJE,GBTICJE-IDENTIFIERA-ID2280762,JE-DK0300636,TJE-DK0300636,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-116750.71,0.0,IC Invoice - EU Sales,None,APMM c-out from DK,NL853361757B01,IC Invoice - EU Sales
7010,GBTICJE,GBTICJE-IDENTIFIERA-ID2280764,JE-DK0300637,TJE-DK0300637,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-6285.62,0.0,IC Invoice - EU Sales,None,APMM c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7011,GBTICJE,GBTICJE-IDENTIFIERA-ID2280765,JE-DK0300638,TJE-DK0300638,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-373.40,0.0,IC Invoice - Outside EU,None,APMM c-out from DK,CHE-300.737.496 MWST,IC Invoice - Outside EU
7012,GBTICJE,GBTICJE-IDENTIFIERA-ID2280766,JE-DK0300639,TJE-DK0300639,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-65283.31,0.0,IC Invoice - EU Sales,None,APMM c-out from DK,GB 177248479,IC Invoice - EU Sales
7013,GBTICJE,GBTICJE-IDENTIFIERA-ID2280769,JE-DK0300640,TJE-DK0300640,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-11139.86,0.0,IC Invoice - Outside EU,None,Carlsberg c-out from DK,NO959209502,IC Invoice - Outside EU
7014,GBTICJE,GBTICJE-IDENTIFIERA-ID2280768,JE-DK0300641,TJE-DK0300641,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-3609.56,0.0,IC Invoice - EU Sales,None,Carlsberg c-out from DK,DE254337470,IC Invoice - EU Sales
7015,GBTICJE,GBTICJE-IDENTIFIERA-ID2280770,JE-DK0300642,TJE-DK0300642,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-11980.02,0.0,IC Invoice - EU Sales,None,Carlsberg c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7016,GBTICJE,GBTICJE-IDENTIFIERA-ID2280771,JE-DK0300643,TJE-DK0300643,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-27040.61,0.0,IC Invoice - Outside EU,None,Carlsberg c-out from DK,CHE-300.737.496 MWST,IC Invoice - Outside EU
7017,GBTICJE,GBTICJE-IDENTIFIERA-ID2280772,JE-DK0300644,TJE-DK0300644,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-12602.36,0.0,IC Invoice - EU Sales,None,Carlsberg c-out from DK,GB 177248479,IC Invoice - EU Sales
7018,GBTICJE,GBTICJE-IDENTIFIERA-ID2280773,JE-DK0300645,TJE-DK0300645,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-5943.33,0.0,IC Invoice - EU Sales,None,Danske Bank c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
7019,GBTICJE,GBTICJE-IDENTIFIERA-ID2280774,JE-DK0300646,TJE-DK0300646,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-9957.42,0.0,IC Invoice - EU Sales,None,Danske Bank c-out from DK,FI02152075,IC Invoice - EU Sales
7020,GBTICJE,GBTICJE-IDENTIFIERA-ID2280775,JE-DK0300647,TJE-DK0300647,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-75085.14,0.0,IC Invoice - Outside EU,None,Danske Bank c-out from DK,NO959209502,IC Invoice - Outside EU
7021,GBTICJE,GBTICJE-IDENTIFIERA-ID2280777,JE-DK0300648,TJE-DK0300648,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-59028.81,0.0,IC Invoice - EU Sales,None,Danske Bank c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7022,GBTICJE,GBTICJE-IDENTIFIERA-ID2280778,JE-DK0300649,TJE-DK0300649,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-10486.40,0.0,IC Invoice - EU Sales,None,Danske Bank c-out from DK,GB 177248479,IC Invoice - EU Sales
7023,GBTICJE,GBTICJE-IDENTIFIERA-ID2280779,JE-DK0300650,TJE-DK0300650,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-62.23,0.0,IC Invoice - EU Sales,None,LEGO c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
7024,GBTICJE,GBTICJE-IDENTIFIERA-ID2280781,JE-DK0300651,TJE-DK0300651,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-3018.34,0.0,IC Invoice - EU Sales,None,LEGO c-out from DK,FR 15 304 475 338,IC Invoice - EU Sales
7025,GBTICJE,GBTICJE-IDENTIFIERA-ID2280776,JE-DK0300652,TJE-DK0300652,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-4947.59,0.0,IC Invoice - EU Sales,None,Danske Bank c-out from DK,PL 5252273929,IC Invoice - EU Sales
7026,GBTICJE,GBTICJE-IDENTIFIERA-ID2280782,JE-DK0300653,TJE-DK0300653,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-11980.02,0.0,IC Invoice - EU Sales,None,Carlsberg c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7027,GBTICJE,GBTICJE-IDENTIFIERA-ID2280784,JE-DK0300654,TJE-DK0300654,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-31210.28,0.0,IC Invoice - EU Sales,None,LEGO c-out from DK,NL853361757B01,IC Invoice - EU Sales
7028,GBTICJE,GBTICJE-IDENTIFIERA-ID2280785,JE-DK0300655,TJE-DK0300655,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-1213.56,0.0,IC Invoice - Outside EU,None,LEGO c-out from DK,NO959209502,IC Invoice - Outside EU
7029,GBTICJE,GBTICJE-IDENTIFIERA-ID2280786,JE-DK0300656,TJE-DK0300656,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-1711.43,0.0,IC Invoice - EU Sales,None,LEGO c-out from DK,PL 5252273929,IC Invoice - EU Sales
7030,GBTICJE,GBTICJE-IDENTIFIERA-ID2280780,JE-DK0300657,TJE-DK0300657,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-528.99,0.0,IC Invoice - EU Sales,None,LEGO c-out from DK,CZ 02525071,IC Invoice - EU Sales
7031,GBTICJE,GBTICJE-IDENTIFIERA-ID2280788,JE-DK0300658,TJE-DK0300658,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-560.10,0.0,IC Invoice - EU Sales,None,LEGO c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7032,GBTICJE,GBTICJE-IDENTIFIERA-ID2280789,JE-DK0300659,TJE-DK0300659,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-53676.70,0.0,IC Invoice - EU Sales,None,LEGO c-out from DK,GB 177248479,IC Invoice - EU Sales
7033,GBTICJE,GBTICJE-IDENTIFIERA-ID2280783,JE-DK0300660,TJE-DK0300660,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-62.23,0.0,IC Invoice - EU Sales,None,LEGO c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
7034,GBTICJE,GBTICJE-IDENTIFIERA-ID2280790,JE-DK0300661,TJE-DK0300661,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-6472.32,0.0,IC Invoice - EU Sales,None,Ramboll c-out from DK,FI02152075,IC Invoice - EU Sales
7035,GBTICJE,GBTICJE-IDENTIFIERA-ID2280791,JE-DK0300662,TJE-DK0300662,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-12789.06,0.0,IC Invoice - Outside EU,None,Ramboll c-out from DK,NO959209502,IC Invoice - Outside EU
7036,GBTICJE,GBTICJE-IDENTIFIERA-ID2280792,JE-DK0300663,TJE-DK0300663,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-1618.08,0.0,IC Invoice - EU Sales,None,Ramboll c-out from DK,DE254337470,IC Invoice - EU Sales
7037,GBTICJE,GBTICJE-IDENTIFIERA-ID2280793,JE-DK0300664,TJE-DK0300664,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-41198.81,0.0,IC Invoice - EU Sales,None,Ramboll c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
7038,GBTICJE,GBTICJE-IDENTIFIERA-ID2280794,JE-DK0300665,TJE-DK0300665,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-8526.04,0.0,IC Invoice - EU Sales,None,Ramboll c-out from DK,GB 177248479,IC Invoice - EU Sales
7039,GBTICJE,GBTICJE-IDENTIFIERA-ID2280787,JE-DK0300666,TJE-DK0300666,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-0.0,-2147.07,0.0,IC Invoice - EU Sales,None,LEGO c-out from DK,B85376630,IC Invoice - EU Sales

In [71]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comment'] == 'Transactions 0DKK') &
        (vat['External name'] == 'GBTICJE') &
        (vat['Maximum of NetSuite Tax Item'].isnull()), 'Comment'] = 'Intercompany'
vat[vat["Comment"] == "Intercompany"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type,Comment 2,VAT No,Comment 3
177,GBTICJE,GBTICJE-IDENTIFIERH-ID2270896,JE-NL1276238,TJE-NL0166162,,Journal,8/1/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
178,GBTICJE,GBTICJE-IDENTIFIERB-ID2270895,JE-NL1276239,TJE-NL0166163,,Journal,8/1/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
6335,GBTICJE,GBTICJE-IDENTIFIERH-ID2290961,JE-NL1277402,TJE-NL0167326,,Journal,8/15/2020,Aug-20,- None -,NaN,...,-151.94,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
13623,GBTICJE,GBTICJE-IDENTIFIERA-ID2306485,JE-DK0303434,TJE-DK0303434,,Journal,8/30/2020,Aug-20,- None -,NaN,...,-29858.59,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
13624,GBTICJE,GBTICJE-IDENTIFIERB-ID2287460,JE-NL1277252,TJE-NL0167176,,Journal,8/30/2020,Aug-20,- None -,NaN,...,1772.89,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
13625,GBTICJE,GBTICJE-IDENTIFIERB-ID2287486,JE-NL1277277,TJE-NL0167201,,Journal,8/30/2020,Aug-20,- None -,NaN,...,1911.82,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
13626,GBTICJE,GBTICJE-IDENTIFIERB-ID2295766,JE-NL1278038,TJE-NL0167962,,Journal,8/30/2020,Aug-20,- None -,NaN,...,464.28,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14453,GBTICJE,GBTICJE-IDENTIFIERB-ID2291763,JE-NL1277575,TJE-NL0167499,,Journal,8/31/2020,Aug-20,- None -,NaN,...,27255.75,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14454,GBTICJE,GBTICJE-IDENTIFIERB-ID2292068,JE-NL1277602,TJE-NL0167526,,Journal,8/31/2020,Aug-20,- None -,NaN,...,3360.65,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14455,GBTICJE,GBTICJE-IDENTIFIERH-ID2292091,JE-NL1277627,TJE-NL0167551,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-388.12,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14456,GBTICJE,GBTICJE-IDENTIFIERB-ID2294354,JE-NL1277874,TJE-NL0167798,,Journal,8/31/2020,Aug-20,- None -,NaN,...,1358.56,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14457,GBTICJE,GBTICJE-IDENTIFIERB-ID2294457,JE-NL1277900,TJE-NL0167824,,Journal,8/31/2020,Aug-20,- None -,NaN,...,10478.00,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14458,GBTICJE,GBTICJE-IDENTIFIERB-ID2294563,JE-NL1277911,TJE-NL0167835,,Journal,8/31/2020,Aug-20,- None -,NaN,...,2422.08,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14462,GBTICJE,GBTICJE-IDENTIFIERH-ID2299558,JE-NL1278690,TJE-NL0168614,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14463,GBTICJE,GBTICJE-IDENTIFIERB-ID2299554,JE-NL1278693,TJE-NL0168617,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14464,GBTICJE,GBTICJE-IDENTIFIERH-ID2301063,JE-NL1278952,TJE-NL0168876,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14465,GBTICJE,GBTICJE-IDENTIFIERH-ID2301059,JE-NL1278953,TJE-NL0168877,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14466,GBTICJE,GBTICJE-IDENTIFIERH-ID2301062,JE-NL1278954,TJE-NL0168878,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14467,GBTICJE,GBTICJE-IDENTIFIERH-ID2301060,JE-NL1278955,TJE-NL0168879,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14468,GBTICJE,GBTICJE-IDENTIFIERH-ID2301055,JE-NL1278956,TJE-NL0168880,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14469,GBTICJE,GBTICJE-IDENTIFIERH-ID2301054,JE-NL1278957,TJE-NL0168881,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14470,GBTICJE,GBTICJE-IDENTIFIERH-ID2301061,JE-NL1278958,TJE-NL0168882,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14471,GBTICJE,GBTICJE-IDENTIFIERH-ID2301057,JE-NL1278959,TJE-NL0168883,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14472,GBTICJE,GBTICJE-IDENTIFIERH-ID2301056,JE-NL1278960,TJE-NL0168884,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14473,GBTICJE,GBTICJE-IDENTIFIERH-ID2301058,JE-NL1278961,TJE-NL0168885,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14474,GBTICJE,GBTICJE-IDENTIFIERH-ID2301064,JE-NL1278962,TJE-NL0168886,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN
14475,GBTICJE,GBTICJE-IDENTIFIERH-ID2301065,JE-NL1278963,TJE-NL0168887,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Intercompany,None,NaN,NaN,NaN

In [72]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comment'] == 'Transactions 0DKK') &
        (vat['Type'] == 'Journal'), 'Comment'] = 'JE-transactions-no vat'
vat[vat["Comment"] == "JE-transactions-no vat"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type,Comment 2,VAT No,Comment 3
35,ID,21538_ID-549901_COGSADJ,JE-DK0303432,TJE-DK0303432,,Journal,6/26/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,0.0,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
57,HC,HC-OPF-1115-2020-7-17 Fee Adj,JE-DK0300362,TJE-DK0300362,,Journal,7/17/2020,Aug-20,- None -,NaN,...,3461.18,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
58,HCTransient_thenry7_Reclass,20200717_HCTransient_thenry7_Reclass Onyx Fee_...,JE-DK0300363,TJE-DK0300363,,Journal,7/17/2020,Aug-20,- None -,NaN,...,0.00,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
63,HC,HC-OPF-1115-2020-7-22 Fee Adj,JE-DK0300361,TJE-DK0300361,,Journal,7/22/2020,Aug-20,- None -,NaN,...,537.32,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
64,HCTransient_thenry7_Reclass,20200722_HCTransient_thenry7_Reclass Onyx Fee_...,JE-DK0300364,TJE-DK0300364,,Journal,7/22/2020,Aug-20,- None -,NaN,...,0.00,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14443,FINREP_wkalika_Aug,20200831_FINREP_wkalika_Aug 2020_AIA tax_4,JE-DK0302990,TJE-DK0302990,,Journal,8/31/2020,Aug-20,- None -,NaN,...,36863.20,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
14444,FST_shatfield_DK_1115_1,20200831_FST_shatfield_DK_1115_1,JE-DK0302992,TJE-DK0302992,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
14445,RLFO_Vmarrahi_KDS,20200831_RLFO_Vmarrahi_KDS mkts allocation1115,JE-DK0303433,TJE-DK0303433,,Journal,8/31/2020,Aug-20,- None -,NaN,...,0.00,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
14446,RCL102AUGUST2020,RCL102AUGUST2020 1004,JE-DK0303483,TJE-DK0303483,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
14448,AugHRG_DNK_TB_movement_Sales,2020AugHRG_DNK_TB_movement_Sales,JE-DK0303587,TJE-DK0303587,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN

In [73]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comment'] == 'Transactions 0DKK') &
        (~vat['Source System'].isin(['- None -','GMAX'])) &
        (vat['Type'].isin(['Bill','Bill Credit'])), 'Comment'] = 'Linked invoice'
vat[vat["Comment"] == "Linked invoice"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type,Comment 2,VAT No,Comment 3
720,None,- None -,2800047416 3800047417,BL-DK0409694,,Bill,8/4/2020,Aug-20,Due on receipt,8/4/2020,...,NaN,NaN,NaN,NaN,NaN,Linked invoice,None,NaN,NaN,NaN
721,None,- None -,2800047452 3800047453,BL-DK0409696,,Bill,8/4/2020,Aug-20,Due on receipt,8/4/2020,...,NaN,NaN,NaN,NaN,NaN,Linked invoice,None,NaN,NaN,NaN
1221,None,- None -,2800047585 3800047586,BL-DK0409705,,Bill,8/5/2020,Aug-20,Due on receipt,8/5/2020,...,NaN,NaN,NaN,NaN,NaN,Linked invoice,None,NaN,NaN,NaN
1578,IDSUM,26216056_IDSUM-525701,JAH3YC,BL-DK0409770,,Bill,8/5/2020,Aug-20,Net 15,8/20/2020,...,NaN,NaN,NaN,NaN,NaN,Linked invoice,None,NaN,NaN,NaN
1579,IDSUM,26216047_IDSUM-525501,JCJH9V,BL-DK0409761,,Bill,8/5/2020,Aug-20,- None -,8/5/2020,...,NaN,NaN,NaN,NaN,NaN,Linked invoice,None,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10652,KDS_Exp_VB_5046988,KDS_Exp_VB_5046988.2020-08-25-1,5046988.2020-08-25-1,BL-DK0409838,,Bill,8/25/2020,Aug-20,Due on receipt,8/25/2020,...,NaN,NaN,NaN,NaN,NaN,Linked invoice,None,NaN,NaN,NaN
11343,None,- None -,2800047678,BL-DK0409839,,Bill,8/26/2020,Aug-20,Due on receipt,9/10/2020,...,NaN,NaN,NaN,NaN,NaN,Linked invoice,None,NaN,NaN,NaN
13379,None,- None -,refund aug0828,BC-DK0126202,,Bill Credit,8/28/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Linked invoice,None,NaN,NaN,NaN
13380,None,- None -,refund0828,BC-DK0126203,,Bill Credit,8/28/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,Linked invoice,None,NaN,NaN,NaN
13627,None,- None -,87302732,BL-DK0409846,,Bill,8/31/2020,Aug-20,Due on receipt,8/31/2020,...,NaN,NaN,NaN,NaN,NaN,Linked invoice,None,NaN,NaN,NaN

In [74]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comment'] == 'Transactions 0DKK') &
        (~vat['Source System'].isin(['- None -','GMAX'])) &
        (vat['Type'].isin(['Credit Memo','Invoice', 'Journal'])), 'Comment'] = 'JE-transactions-no vat'
vat[vat["Comment"] == "JE-transactions-no vat"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type,Comment 2,VAT No,Comment 3
35,ID,21538_ID-549901_COGSADJ,JE-DK0303432,TJE-DK0303432,,Journal,6/26/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,0.0,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
57,HC,HC-OPF-1115-2020-7-17 Fee Adj,JE-DK0300362,TJE-DK0300362,,Journal,7/17/2020,Aug-20,- None -,NaN,...,3461.18,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
58,HCTransient_thenry7_Reclass,20200717_HCTransient_thenry7_Reclass Onyx Fee_...,JE-DK0300363,TJE-DK0300363,,Journal,7/17/2020,Aug-20,- None -,NaN,...,0.00,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
63,HC,HC-OPF-1115-2020-7-22 Fee Adj,JE-DK0300361,TJE-DK0300361,,Journal,7/22/2020,Aug-20,- None -,NaN,...,537.32,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
64,HCTransient_thenry7_Reclass,20200722_HCTransient_thenry7_Reclass Onyx Fee_...,JE-DK0300364,TJE-DK0300364,,Journal,7/22/2020,Aug-20,- None -,NaN,...,0.00,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14443,FINREP_wkalika_Aug,20200831_FINREP_wkalika_Aug 2020_AIA tax_4,JE-DK0302990,TJE-DK0302990,,Journal,8/31/2020,Aug-20,- None -,NaN,...,36863.20,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
14444,FST_shatfield_DK_1115_1,20200831_FST_shatfield_DK_1115_1,JE-DK0302992,TJE-DK0302992,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
14445,RLFO_Vmarrahi_KDS,20200831_RLFO_Vmarrahi_KDS mkts allocation1115,JE-DK0303433,TJE-DK0303433,,Journal,8/31/2020,Aug-20,- None -,NaN,...,0.00,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
14446,RCL102AUGUST2020,RCL102AUGUST2020 1004,JE-DK0303483,TJE-DK0303483,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN
14448,AugHRG_DNK_TB_movement_Sales,2020AugHRG_DNK_TB_movement_Sales,JE-DK0303587,TJE-DK0303587,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,NaN,JE-transactions-no vat,None,NaN,NaN,NaN

In [75]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comment'] == 'Transactions 0DKK') &
        (vat['Source System'].isin(['- None -','GMAX'])) &
        (vat['Maximum of Tax Code (Consolidated)'].str.contains('-E-2-VT-S-')), 'Transaction type'] = 'Regional-not in EU-Rubrik C'
vat[vat["Transaction type"] == "Regional-not in EU-Rubrik C"]

Empty DataFrame
Columns: [External name, External ID, Document Number, Transaction Number, Maximum of Linked Invoice, Type, Date, Period, Terms, Maximum of Due Date/Receive By, Company Name, Customer VAT Registration Number, Bill to City, Bill to State, Bill to Country, Bill to Zip, Source System, Source System Identifier, City, State/Province, Country, Zip, Currency, Memo (Main), Maximum of GMAX Tax Code, Maximum of NetSuite Tax Item, Maximum of Coupa Tax Code, Maximum of External System Tax Code, Maximum of Tax Code (Consolidated), FOP Type, Sum of Assets, Sum of Accounts Payable, Sum of Other Liabilities, Sum of Income, Sum of Expense, Sum of VAT, VAT rate, Liab+Net Inc, Correct revenue, Comment, Transaction type, Comment 2, VAT No, Comment 3]
Index: []

[0 rows x 44 columns]

In [76]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comment'] == 'Transactions 0DKK') &
        (vat['Source System'].isin(['- None -','GMAX'])) &
        (vat['Maximum of Tax Code (Consolidated)'].str.contains('-I-2-VT-S-')), 'Transaction type'] = 'International - Rubrik C'
vat[vat["Transaction type"] == "International - Rubrik C"]

Empty DataFrame
Columns: [External name, External ID, Document Number, Transaction Number, Maximum of Linked Invoice, Type, Date, Period, Terms, Maximum of Due Date/Receive By, Company Name, Customer VAT Registration Number, Bill to City, Bill to State, Bill to Country, Bill to Zip, Source System, Source System Identifier, City, State/Province, Country, Zip, Currency, Memo (Main), Maximum of GMAX Tax Code, Maximum of NetSuite Tax Item, Maximum of Coupa Tax Code, Maximum of External System Tax Code, Maximum of Tax Code (Consolidated), FOP Type, Sum of Assets, Sum of Accounts Payable, Sum of Other Liabilities, Sum of Income, Sum of Expense, Sum of VAT, VAT rate, Liab+Net Inc, Correct revenue, Comment, Transaction type, Comment 2, VAT No, Comment 3]
Index: []

[0 rows x 44 columns]

In [77]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comment'] == 'Transactions 0DKK') &
        (vat['Source System'].isin(['- None -','GMAX'])) &
        (vat['Maximum of Tax Code (Consolidated)'].str.contains('-CPB-')), 'Transaction type'] = 'Rail - commission passback - Rubrik C'
vat[vat["Transaction type"] == "Rail - commission passback - Rubrik C"]

Empty DataFrame
Columns: [External name, External ID, Document Number, Transaction Number, Maximum of Linked Invoice, Type, Date, Period, Terms, Maximum of Due Date/Receive By, Company Name, Customer VAT Registration Number, Bill to City, Bill to State, Bill to Country, Bill to Zip, Source System, Source System Identifier, City, State/Province, Country, Zip, Currency, Memo (Main), Maximum of GMAX Tax Code, Maximum of NetSuite Tax Item, Maximum of Coupa Tax Code, Maximum of External System Tax Code, Maximum of Tax Code (Consolidated), FOP Type, Sum of Assets, Sum of Accounts Payable, Sum of Other Liabilities, Sum of Income, Sum of Expense, Sum of VAT, VAT rate, Liab+Net Inc, Correct revenue, Comment, Transaction type, Comment 2, VAT No, Comment 3]
Index: []

[0 rows x 44 columns]

In [78]:
vat.loc[(vat['Transaction type'] == 'International - Rubrik C'), 'Comment'] = '0% VAT Denmark'
vat[vat["Transaction type"] == "International - Rubrik C"]

Empty DataFrame
Columns: [External name, External ID, Document Number, Transaction Number, Maximum of Linked Invoice, Type, Date, Period, Terms, Maximum of Due Date/Receive By, Company Name, Customer VAT Registration Number, Bill to City, Bill to State, Bill to Country, Bill to Zip, Source System, Source System Identifier, City, State/Province, Country, Zip, Currency, Memo (Main), Maximum of GMAX Tax Code, Maximum of NetSuite Tax Item, Maximum of Coupa Tax Code, Maximum of External System Tax Code, Maximum of Tax Code (Consolidated), FOP Type, Sum of Assets, Sum of Accounts Payable, Sum of Other Liabilities, Sum of Income, Sum of Expense, Sum of VAT, VAT rate, Liab+Net Inc, Correct revenue, Comment, Transaction type, Comment 2, VAT No, Comment 3]
Index: []

[0 rows x 44 columns]

In [79]:
vat.loc[(vat['Transaction type'] == 'Regional-not in EU-Rubrik C'), 'Comment'] = '0% VAT Denmark'
vat[vat["Transaction type"] == "Regional-not in EU-Rubrik C"]

Empty DataFrame
Columns: [External name, External ID, Document Number, Transaction Number, Maximum of Linked Invoice, Type, Date, Period, Terms, Maximum of Due Date/Receive By, Company Name, Customer VAT Registration Number, Bill to City, Bill to State, Bill to Country, Bill to Zip, Source System, Source System Identifier, City, State/Province, Country, Zip, Currency, Memo (Main), Maximum of GMAX Tax Code, Maximum of NetSuite Tax Item, Maximum of Coupa Tax Code, Maximum of External System Tax Code, Maximum of Tax Code (Consolidated), FOP Type, Sum of Assets, Sum of Accounts Payable, Sum of Other Liabilities, Sum of Income, Sum of Expense, Sum of VAT, VAT rate, Liab+Net Inc, Correct revenue, Comment, Transaction type, Comment 2, VAT No, Comment 3]
Index: []

[0 rows x 44 columns]

In [80]:
vat.loc[(vat['Comment'] == 'Transactions 0DKK'), 'Comment'] = 'Travel Bill'
vat[vat["Comment"] == "Travel Bill"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type,Comment 2,VAT No,Comment 3
9,VOID,584168307-VOID,IN-DK4779863,TIN-DK4779863,Credit Memo #CM-DK0311839,Invoice,5/5/2020,Aug-20,Due on receipt,5/5/2020,...,NaN,0.0,-0.0,-4638.09,0.0,Travel Bill,None,NaN,NaN,NaN
10,VOID,584186447-VOID,IN-DK4779864,TIN-DK4779864,Credit Memo #CM-DK0311849,Invoice,5/5/2020,Aug-20,Due on receipt,5/5/2020,...,NaN,0.0,-0.0,-235.12,0.0,Travel Bill,None,NaN,NaN,NaN
13,VOID,584429618-VOID,IN-DK4779865,TIN-DK4779865,Credit Memo #CM-DK0311909,Invoice,5/11/2020,Aug-20,Net 30,6/10/2020,...,NaN,0.0,-0.0,-1140.00,0.0,Travel Bill,None,NaN,NaN,NaN
14,VOID,584431188-VOID,IN-DK4779866,TIN-DK4779866,Credit Memo #CM-DK0311910,Invoice,5/11/2020,Aug-20,- None -,5/11/2020,...,NaN,0.0,-0.0,-764.00,0.0,Travel Bill,None,NaN,NaN,NaN
15,VOID,584431196-VOID,IN-DK4779867,TIN-DK4779867,Credit Memo #CM-DK0311911,Invoice,5/11/2020,Aug-20,- None -,5/11/2020,...,NaN,0.0,-0.0,-2838.00,0.0,Travel Bill,None,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14150,CI,00385758424-0009873-002-001-CI,IN-DK4787014,TIN-DK4787014,,Invoice,8/31/2020,Aug-20,- None -,NaN,...,NaN,0.0,NaN,0.00,0.0,Travel Bill,None,NaN,NaN,NaN
14159,CI,00385282022-0009874-010-001-CI,IN-DK4787375,TIN-DK4787375,,Invoice,8/31/2020,Aug-20,Due on receipt,8/31/2020,...,NaN,0.0,NaN,0.00,0.0,Travel Bill,None,NaN,NaN,NaN
14160,CI,00385815134-1328783-001-001-CI,IN-DK4787399,TIN-DK4787399,,Invoice,8/31/2020,Aug-20,- None -,8/31/2020,...,NaN,0.0,NaN,0.00,0.0,Travel Bill,None,NaN,NaN,NaN
14161,CI,00385815185-1328783-001-001-CI,IN-DK4787422,TIN-DK4787422,,Invoice,8/31/2020,Aug-20,- None -,8/31/2020,...,NaN,0.0,NaN,0.00,0.0,Travel Bill,None,NaN,NaN,NaN
14162,CI,00385815223-1328783-001-001-CI,IN-DK4787430,TIN-DK4787430,,Invoice,8/31/2020,Aug-20,- None -,8/31/2020,...,NaN,0.0,NaN,0.00,0.0,Travel Bill,None,NaN,NaN,NaN

In [81]:
vat[vat["Comment"] == "VAT"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Expense,Sum of VAT,VAT rate,Liab+Net Inc,Correct revenue,Comment,Transaction type,Comment 2,VAT No,Comment 3
152,None,- None -,JE-DK0299166,TJE-DK0299166,Invoice #IN-DK4777272,Journal,8/1/2020,Aug-20,- None -,NaN,...,NaN,-684.50,0.250000,-2738.00,-2738.00,VAT,Domestic 25%,NaN,NaN,NaN
154,None,- None -,JE-DK0299168,TJE-DK0299168,Invoice #IN-DK4777272,Journal,8/1/2020,Aug-20,- None -,NaN,...,NaN,-245.75,0.250000,-983.00,-983.00,VAT,Domestic 25%,NaN,NaN,NaN
155,None,- None -,JE-DK0299170,TJE-DK0299170,Invoice #IN-DK4777271,Journal,8/1/2020,Aug-20,- None -,NaN,...,NaN,-93.75,0.250000,-375.00,-375.00,VAT,Domestic 25%,NaN,NaN,NaN
159,None,- None -,JE-DK0299175,TJE-DK0299175,Invoice #IN-DK4777271,Journal,8/1/2020,Aug-20,- None -,NaN,...,NaN,-3.75,0.250000,-15.00,-15.00,VAT,Domestic 25%,NaN,NaN,NaN
160,None,- None -,JE-DK0299176,TJE-DK0299176,Invoice #IN-DK4777272,Journal,8/1/2020,Aug-20,- None -,NaN,...,NaN,-47.50,0.250000,-190.00,-190.00,VAT,Domestic 25%,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14403,None,- None -,JE-DK0302869,TJE-DK0302869,Invoice #IN-DK4788243,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,-36.25,0.250000,-145.00,-145.00,VAT,Domestic 25%,NaN,NaN,NaN
14405,None,- None -,JE-DK0302876,TJE-DK0302876,Invoice #IN-DK4788242,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,-36.25,0.250000,-145.00,-145.00,VAT,Domestic 25%,NaN,NaN,NaN
14406,None,- None -,JE-DK0302879,TJE-DK0302879,Invoice #IN-DK4788232,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,-21.50,0.250000,-86.00,-86.00,VAT,Domestic 25%,NaN,NaN,NaN
14407,None,- None -,JE-DK0302888,TJE-DK0302888,Invoice #IN-DK4788242,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,-15.00,0.250000,-60.00,-60.00,VAT,Domestic 25%,NaN,NaN,NaN
14447,AugHRG_DNK_TB_Movement,2020AugHRG_DNK_TB_Movement,JE-DK0303586,TJE-DK0303586,,Journal,8/31/2020,Aug-20,- None -,NaN,...,12275.19,-13763.02,-0.091903,149756.59,-55052.08,VAT,Domestic 25%,NaN,NaN,NaN

In [82]:
pvt=vat.pivot_table(index='Comment', values=['Sum of Income', 'Correct revenue', 'Sum of VAT'], aggfunc='sum', margins=True, margins_name='Grand total')

In [83]:
pvt

,Correct revenue,Sum of Income,Sum of VAT
Comment,,,
Hotel Commission,-19219.88,-50677.67,-4804.97
IC Invoice - EU Sales,0.00,-477613.70,0.00
IC Invoice - Outside EU,0.00,-531321.52,0.00
Intercompany,0.00,-12598.24,0.00
JE-transactions-no vat,0.00,-1259358.78,0.00
Linked invoice,0.00,31660.00,0.00
Neo Travel Expense no vat,0.00,0.00,0.00
Procurement inv,0.00,0.00,0.00
Reverse charge booked automatically in Netsuite,-257093.16,0.00,-64273.29
Travel Bill,0.00,-16065.81,0.00
VAT,-1872611.76,-1719334.06,-468152.94
Grand total,-1529282.04,-4560125.54,-382320.51

In [84]:
pvt.loc[('Grand total'),:] = pvt.iloc[:(pvt.shape[0]-1), :].sum()

In [85]:
pvt.round(0).astype(int)

,Correct revenue,Sum of Income,Sum of VAT
Comment,,,
Hotel Commission,-19220,-50678,-4805
IC Invoice - EU Sales,0,-477614,0
IC Invoice - Outside EU,0,-531322,0
Intercompany,0,-12598,0
JE-transactions-no vat,0,-1259359,0
Linked invoice,0,31660,0
Neo Travel Expense no vat,0,0,0
Procurement inv,0,0,0
Reverse charge booked automatically in Netsuite,-257093,0,-64273
Travel Bill,0,-16066,0
VAT,-1872612,-1719334,-468153
Grand total,-2148925,-4035310,-537231

In [87]:
# excel_file = pd.ExcelWriter("Darko_VAT_sales_202008.xlsx")

# vat.to_excel(excel_file, sheet_name = "vat", index = False)

# excel_file.save()