In [1]:
import pandas as pd
import numpy as np

In [2]:
vat = pd.read_csv("VAT_purchase_2020_03.csv")
vat.head(3)

,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,Vendor Category,...,Maximum of Coupa Tax Code,Maximum of External System Tax Code,Maximum of Tax Code (Consolidated),FOP Type,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT
0,20200101_FINREP_bjhamb_253150 account reclass_06,JE-DK0289677,TJE-DK0289677,,Journal,1/1/2020,Mar-20,- None -,NaN,- None -,...,NaN,NaN,NaN,- None -,NaN,NaN,0.0,NaN,NaN,NaN
1,565788256-SUMVOID,JE-DK0290724,TJE-DK0290724,Credit Memo #CM-DK0296577,Journal,1/20/2020,Mar-20,- None -,NaN,- None -,...,NaN,NaN,NaN,- None -,NaN,NaN,NaN,0.0,NaN,NaN
2,565788266-SUMVOID,JE-DK0290725,TJE-DK0290725,Credit Memo #CM-DK0296581,Journal,1/20/2020,Mar-20,- None -,NaN,- None -,...,NaN,NaN,NaN,- None -,NaN,NaN,NaN,0.0,NaN,NaN

In [3]:
vat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5950 entries, 0 to 5949
Data columns (total 40 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   External ID                          5950 non-null   object
 1   Document Number                      5949 non-null   object
 2   Transaction Number                   5949 non-null   object
 3   Maximum of Linked Invoice            5949 non-null   object
 4   Type                                 5949 non-null   object
 5   Date                                 5949 non-null   object
 6   Period                               5949 non-null   object
 7   Terms                                5949 non-null   object
 8   Maximum of Due Date/Receive By       2666 non-null   object
 9   Vendor Category                      5949 non-null   object
 10  Vendor Name                          5949 non-null   object
 11  Vendor Number                        0 non-null      float64
 12  Company Name                         5949 non-null   object
 13  Vendor VAT Registration Number       5949 non-null   object
 14  Vendor Billing Address               5949 non-null   object
 15  Vendor Billing Country               5949 non-null   object
 16  Bill to City                         5949 non-null   object
 17  Bill to State                        5949 non-null   object
 18  Bill to Country                      5949 non-null   object
 19  Bill to Zip                          5949 non-null   object
 20  Source System                        5949 non-null   object
 21  Source System Identifier             5949 non-null   object
 22  City                                 5949 non-null   object
 23  State/Province                       5949 non-null   object
 24  Country                              5949 non-null   object
 25  Zip                                  5949 non-null   object
 26  Currency                             5949 non-null   object
 27  Memo (Main)                          5949 non-null   object
 28  Maximum of GMAX Tax Code             40 non-null     object
 29  Maximum of NetSuite Tax Item         3657 non-null   object
 30  Maximum of Coupa Tax Code            0 non-null      float64
 31  Maximum of External System Tax Code  0 non-null      float64
 32  Maximum of Tax Code (Consolidated)   3657 non-null   object
 33  FOP Type                             5949 non-null   object
 34  Sum of Asset                         918 non-null    float64
 35  Sum of Accounts Payable              3741 non-null   float64
 36  Sum of Other Liabilities             908 non-null    float64
 37  Sum of Income                        4703 non-null   float64
 38  Sum of Expense                       276 non-null    float64
 39  Sum of VAT                           3662 non-null   float64
dtypes: float64(9), object(31)
memory usage: 1.8+ MB

In [4]:
mask1 = vat[vat["External ID"].str.contains("clearing")].index
mask2 = vat[vat["External ID"].str.contains("Cross")].index
mask3 = vat[vat["Type"] == "Currency Revaluation"].index

In [5]:
mask2

Int64Index([5909, 5910, 5911, 5912, 5913, 5914, 5915, 5916, 5917, 5918], dtype='int64')

In [6]:
mask3

Int64Index([  19,   20,   40,   41,   42,   43,   44,   45,   46,   47,
            ...
            5629, 5630, 5631, 5706, 5707, 5764, 5765, 5766, 5767, 5768],
           dtype='int64', length=145)

In [7]:
vat.drop(mask1, inplace=True)

In [8]:
vat.drop(mask2, inplace=True)

In [9]:
vat.drop(mask3, inplace=True)

In [10]:
mask1

Int64Index([5908], dtype='int64')

In [11]:
5908 in vat.index

False

In [12]:
vat.index

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            5940, 5941, 5942, 5943, 5944, 5945, 5946, 5947, 5948, 5949],
           dtype='int64', length=5794)

In [13]:
vat.tail(3)

,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,Vendor Category,...,Maximum of Coupa Tax Code,Maximum of External System Tax Code,Maximum of Tax Code (Consolidated),FOP Type,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT
5947,GBTICJE-IDENTIFIERB-ID2128891,JE-NL1264110,TJE-NL0154034,,Journal,3/31/2020,Mar-20,- None -,NaN,- None -,...,NaN,NaN,DK-S : DK-ESSP,- None -,NaN,-38095.45,-9523.86,NaN,38095.45,9523.86
5948,- None -,XXXXXXXXXXX3103- V-Pay,BC-DK0126114,,Bill Credit,3/31/2020,Mar-20,- None -,NaN,GMAX_CHILD,...,NaN,NaN,DK-Z,- None -,-75177.78,75177.78,NaN,NaN,NaN,0.00
5949,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-8576277.91,-8214988.30,6034795.20,2368904.4,8387566.61,0.00

In [14]:
vat.drop(index=5949, inplace=True)

In [15]:
vat.tail(3)

,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,Vendor Category,...,Maximum of Coupa Tax Code,Maximum of External System Tax Code,Maximum of Tax Code (Consolidated),FOP Type,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT
5946,GBTICJE-IDENTIFIERB-ID2125818,JE-NL1263845,TJE-NL0153769,,Journal,3/31/2020,Mar-20,- None -,NaN,- None -,...,NaN,NaN,NaN,- None -,NaN,-998892.66,NaN,998892.66,NaN,NaN
5947,GBTICJE-IDENTIFIERB-ID2128891,JE-NL1264110,TJE-NL0154034,,Journal,3/31/2020,Mar-20,- None -,NaN,- None -,...,NaN,NaN,DK-S : DK-ESSP,- None -,NaN,-38095.45,-9523.86,NaN,38095.45,9523.86
5948,- None -,XXXXXXXXXXX3103- V-Pay,BC-DK0126114,,Bill Credit,3/31/2020,Mar-20,- None -,NaN,GMAX_CHILD,...,NaN,NaN,DK-Z,- None -,-75177.78,75177.78,NaN,NaN,NaN,0.00

In [16]:
vat[["Sum of Asset","Sum of Accounts Payable","Sum of Other Liabilities","Sum of Income","Sum of Expense","Sum of VAT"]].sum(axis= "rows")

Sum of Asset               -8531256.42
Sum of Accounts Payable    -8232149.40
Sum of Other Liabilities    5423916.44
Sum of Income               2368904.40
Sum of Expense              8370680.66
Sum of VAT                   599904.32
dtype: float64

In [17]:
#Summerize the last row
#vat.loc["Totals"] = pd.Series(vat[["Sum of Asset","Sum of Accounts Payable","Sum of Other Liabilities","Sum of Income","Sum of Expense","Sum of VAT"]].sum(), index = ["Sum of Asset","Sum of Accounts Payable","Sum of Other Liabilities","Sum of Income","Sum of Expense","Sum of VAT"])

In [18]:
#vat.drop(index='Totals', inplace=True)

In [19]:
vat['Sum of VAT'].fillna(0, inplace=True)

In [20]:
def vat_amount(row):
    
    vat = row[39]
    
    if vat >0:
        return 'VAT'
    elif vat <0:
        return 'VAT'
    else:
        return 'Transactions 0DKK'

vat['Comments'] = vat.apply(vat_amount, axis='columns')

In [21]:
vat.head(3)

,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,Vendor Category,...,Maximum of External System Tax Code,Maximum of Tax Code (Consolidated),FOP Type,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments
0,20200101_FINREP_bjhamb_253150 account reclass_06,JE-DK0289677,TJE-DK0289677,,Journal,1/1/2020,Mar-20,- None -,NaN,- None -,...,NaN,NaN,- None -,NaN,NaN,0.0,NaN,NaN,0.0,Transactions 0DKK
1,565788256-SUMVOID,JE-DK0290724,TJE-DK0290724,Credit Memo #CM-DK0296577,Journal,1/20/2020,Mar-20,- None -,NaN,- None -,...,NaN,NaN,- None -,NaN,NaN,NaN,0.0,NaN,0.0,Transactions 0DKK
2,565788266-SUMVOID,JE-DK0290725,TJE-DK0290725,Credit Memo #CM-DK0296581,Journal,1/20/2020,Mar-20,- None -,NaN,- None -,...,NaN,NaN,- None -,NaN,NaN,NaN,0.0,NaN,0.0,Transactions 0DKK

In [22]:
vat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5793 entries, 0 to 5948
Data columns (total 41 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   External ID                          5793 non-null   object
 1   Document Number                      5793 non-null   object
 2   Transaction Number                   5793 non-null   object
 3   Maximum of Linked Invoice            5793 non-null   object
 4   Type                                 5793 non-null   object
 5   Date                                 5793 non-null   object
 6   Period                               5793 non-null   object
 7   Terms                                5793 non-null   object
 8   Maximum of Due Date/Receive By       2666 non-null   object
 9   Vendor Category                      5793 non-null   object
 10  Vendor Name                          5793 non-null   object
 11  Vendor Number                        0 non-null      float64
 12  Company Name                         5793 non-null   object
 13  Vendor VAT Registration Number       5793 non-null   object
 14  Vendor Billing Address               5793 non-null   object
 15  Vendor Billing Country               5793 non-null   object
 16  Bill to City                         5793 non-null   object
 17  Bill to State                        5793 non-null   object
 18  Bill to Country                      5793 non-null   object
 19  Bill to Zip                          5793 non-null   object
 20  Source System                        5793 non-null   object
 21  Source System Identifier             5793 non-null   object
 22  City                                 5793 non-null   object
 23  State/Province                       5793 non-null   object
 24  Country                              5793 non-null   object
 25  Zip                                  5793 non-null   object
 26  Currency                             5793 non-null   object
 27  Memo (Main)                          5793 non-null   object
 28  Maximum of GMAX Tax Code             40 non-null     object
 29  Maximum of NetSuite Tax Item         3657 non-null   object
 30  Maximum of Coupa Tax Code            0 non-null      float64
 31  Maximum of External System Tax Code  0 non-null      float64
 32  Maximum of Tax Code (Consolidated)   3657 non-null   object
 33  FOP Type                             5793 non-null   object
 34  Sum of Asset                         878 non-null    float64
 35  Sum of Accounts Payable              3694 non-null   float64
 36  Sum of Other Liabilities             893 non-null    float64
 37  Sum of Income                        4702 non-null   float64
 38  Sum of Expense                       201 non-null    float64
 39  Sum of VAT                           5793 non-null   float64
 40  Comments                             5793 non-null   object
dtypes: float64(9), object(32)
memory usage: 1.9+ MB

In [23]:
vat.insert(0, column = "External name", value = vat['External ID'].str.extract('([A-Z]\w{0,})', expand=True))

In [24]:
vat['Comment 2']=''

In [25]:
vat['VAT reverse charge']=''

In [26]:
vat['VAT No']=''

In [27]:
vat.columns

Index(['External name', 'External ID', 'Document Number', 'Transaction Number',
       'Maximum of Linked Invoice', 'Type', 'Date', 'Period', 'Terms',
       'Maximum of Due Date/Receive By', 'Vendor Category', 'Vendor Name',
       'Vendor Number', 'Company Name', 'Vendor VAT Registration Number',
       'Vendor Billing Address', 'Vendor Billing Country', 'Bill to City',
       'Bill to State', 'Bill to Country', 'Bill to Zip', 'Source System',
       'Source System Identifier', 'City', 'State/Province', 'Country', 'Zip',
       'Currency', 'Memo (Main)', 'Maximum of GMAX Tax Code',
       'Maximum of NetSuite Tax Item', 'Maximum of Coupa Tax Code',
       'Maximum of External System Tax Code',
       'Maximum of Tax Code (Consolidated)', 'FOP Type', 'Sum of Asset',
       'Sum of Accounts Payable', 'Sum of Other Liabilities', 'Sum of Income',
       'Sum of Expense', 'Sum of VAT', 'Comments', 'Comment 2',
       'VAT reverse charge', 'VAT No'],
      dtype='object')

In [28]:
 vat.loc[((vat['Sum of VAT'].notnull()) | (vat['Sum of VAT'] != 0)) &
        (vat['Comments'] == "VAT") &
        (vat['External name'] == 'GBTICJE'), "Comments"] = 'IC reverse charge EU/Outside'
vat[vat["Comments"] == "IC reverse charge EU/Outside"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,Comment 2,VAT reverse charge,VAT No
5869,GBTICJE,GBTICJE-IDENTIFIERG-ID2119781,JE-DK0290746,TJE-DK0290746,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-8619.50,-2154.88,NaN,8619.50,2154.88,IC reverse charge EU/Outside,,,
5925,GBTICJE,GBTICJE-IDENTIFIERB-ID2114379,JE-NL1262268,TJE-NL0152192,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-11260.92,-2815.23,NaN,11260.92,2815.23,IC reverse charge EU/Outside,,,
5926,GBTICJE,GBTICJE-IDENTIFIERB-ID2114381,JE-NL1262269,TJE-NL0152193,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-13570.36,-3392.59,NaN,13570.36,3392.59,IC reverse charge EU/Outside,,,
5927,GBTICJE,GBTICJE-IDENTIFIERB-ID2114445,JE-NL1262327,TJE-NL0152251,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-788.28,-197.07,NaN,788.28,197.07,IC reverse charge EU/Outside,,,
5928,GBTICJE,GBTICJE-IDENTIFIERB-ID2114446,JE-NL1262329,TJE-NL0152253,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-949.93,-237.48,NaN,949.93,237.48,IC reverse charge EU/Outside,,,
5930,GBTICJE,GBTICJE-IDENTIFIERB-ID2115281,JE-NL1262465,TJE-NL0152390,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-19119.23,-4779.81,NaN,19119.23,4779.81,IC reverse charge EU/Outside,,,
5931,GBTICJE,GBTICJE-IDENTIFIERB-ID2115278,JE-NL1262468,TJE-NL0152392,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-19119.23,-4779.81,NaN,19119.23,4779.81,IC reverse charge EU/Outside,,,
5932,GBTICJE,GBTICJE-IDENTIFIERB-ID2115283,JE-NL1262474,TJE-NL0152398,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-18815.95,-4703.99,NaN,18815.95,4703.99,IC reverse charge EU/Outside,,,
5933,GBTICJE,GBTICJE-IDENTIFIERB-ID2115392,JE-NL1262490,TJE-NL0152414,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-17193.08,-4298.27,NaN,17193.08,4298.27,IC reverse charge EU/Outside,,,
5934,GBTICJE,GBTICJE-IDENTIFIERB-ID2115393,JE-NL1262494,TJE-NL0152418,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-68571.34,-17142.84,NaN,68571.34,17142.84,IC reverse charge EU/Outside,,,
5937,GBTICJE,GBTICJE-IDENTIFIERB-ID2116287,JE-NL1262595,TJE-NL0152519,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-6667.20,-1666.80,NaN,6667.20,1666.80,IC reverse charge EU/Outside,,,
5940,GBTICJE,GBTICJE-IDENTIFIERB-ID2124779,JE-NL1263508,TJE-NL0153432,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-4399.38,-1099.85,NaN,4399.38,1099.85,IC reverse charge EU/Outside,,,
5941,GBTICJE,GBTICJE-IDENTIFIERB-ID2124793,JE-NL1263520,TJE-NL0153444,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-660.04,-165.01,NaN,660.04,165.01,IC reverse charge EU/Outside,,,
5942,GBTICJE,GBTICJE-IDENTIFIERB-ID2124822,JE-NL1263550,TJE-NL0153474,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-39239.06,-9809.77,NaN,39239.06,9809.77,IC reverse charge EU/Outside,,,
5943,GBTICJE,GBTICJE-IDENTIFIERB-ID2124823,JE-NL1263551,TJE-NL0153475,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-14405.59,-3601.40,NaN,14405.59,3601.40,IC reverse charge EU/Outside,,,
5944,GBTICJE,GBTICJE-IDENTIFIERB-ID2124824,JE-NL1263552,TJE-NL0153476,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-3202.67,-800.67,NaN,3202.67,800.67,IC reverse charge EU/Outside,,,
5947,GBTICJE,GBTICJE-IDENTIFIERB-ID2128891,JE-NL1264110,TJE-NL0154034,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-38095.45,-9523.86,NaN,38095.45,9523.86,IC reverse charge EU/Outside,,,

In [29]:
 vat.loc[((vat['Sum of VAT'].notnull()) | (vat['Sum of VAT'] != 0)) &
        (vat['Comments'] == "IC reverse charge EU/Outside") &
        (vat['External name'] == 'GBTICJE'), "VAT reverse charge"] = 'Reverse charge booked automatically in Netsuite'
vat[vat["VAT reverse charge"] == "Reverse charge booked automatically in Netsuite"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,Comment 2,VAT reverse charge,VAT No
5869,GBTICJE,GBTICJE-IDENTIFIERG-ID2119781,JE-DK0290746,TJE-DK0290746,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-8619.50,-2154.88,NaN,8619.50,2154.88,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,
5925,GBTICJE,GBTICJE-IDENTIFIERB-ID2114379,JE-NL1262268,TJE-NL0152192,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-11260.92,-2815.23,NaN,11260.92,2815.23,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,
5926,GBTICJE,GBTICJE-IDENTIFIERB-ID2114381,JE-NL1262269,TJE-NL0152193,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-13570.36,-3392.59,NaN,13570.36,3392.59,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,
5927,GBTICJE,GBTICJE-IDENTIFIERB-ID2114445,JE-NL1262327,TJE-NL0152251,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-788.28,-197.07,NaN,788.28,197.07,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,
5928,GBTICJE,GBTICJE-IDENTIFIERB-ID2114446,JE-NL1262329,TJE-NL0152253,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-949.93,-237.48,NaN,949.93,237.48,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,
5930,GBTICJE,GBTICJE-IDENTIFIERB-ID2115281,JE-NL1262465,TJE-NL0152390,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-19119.23,-4779.81,NaN,19119.23,4779.81,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,
5931,GBTICJE,GBTICJE-IDENTIFIERB-ID2115278,JE-NL1262468,TJE-NL0152392,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-19119.23,-4779.81,NaN,19119.23,4779.81,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,
5932,GBTICJE,GBTICJE-IDENTIFIERB-ID2115283,JE-NL1262474,TJE-NL0152398,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-18815.95,-4703.99,NaN,18815.95,4703.99,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,
5933,GBTICJE,GBTICJE-IDENTIFIERB-ID2115392,JE-NL1262490,TJE-NL0152414,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-17193.08,-4298.27,NaN,17193.08,4298.27,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,
5934,GBTICJE,GBTICJE-IDENTIFIERB-ID2115393,JE-NL1262494,TJE-NL0152418,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-68571.34,-17142.84,NaN,68571.34,17142.84,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,
5937,GBTICJE,GBTICJE-IDENTIFIERB-ID2116287,JE-NL1262595,TJE-NL0152519,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-6667.20,-1666.80,NaN,6667.20,1666.80,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,
5940,GBTICJE,GBTICJE-IDENTIFIERB-ID2124779,JE-NL1263508,TJE-NL0153432,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-4399.38,-1099.85,NaN,4399.38,1099.85,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,
5941,GBTICJE,GBTICJE-IDENTIFIERB-ID2124793,JE-NL1263520,TJE-NL0153444,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-660.04,-165.01,NaN,660.04,165.01,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,
5942,GBTICJE,GBTICJE-IDENTIFIERB-ID2124822,JE-NL1263550,TJE-NL0153474,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-39239.06,-9809.77,NaN,39239.06,9809.77,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,
5943,GBTICJE,GBTICJE-IDENTIFIERB-ID2124823,JE-NL1263551,TJE-NL0153475,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-14405.59,-3601.40,NaN,14405.59,3601.40,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,
5944,GBTICJE,GBTICJE-IDENTIFIERB-ID2124824,JE-NL1263552,TJE-NL0153476,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-3202.67,-800.67,NaN,3202.67,800.67,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,
5947,GBTICJE,GBTICJE-IDENTIFIERB-ID2128891,JE-NL1264110,TJE-NL0154034,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-38095.45,-9523.86,NaN,38095.45,9523.86,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,

In [30]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == "Transactions 0DKK") &
        (vat['Source System'].isin(['Procurement']) &
        (vat['Bill to Country'].isin(['Denmark']))), 'Comments'] = 'Procurement-Denmark 0% VAT'
vat[vat["Comments"] == "Procurement-Denmark 0% VAT"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,Comment 2,VAT reverse charge,VAT No
11,None,- None -,102581746,BL-DK0406470,,Bill,2/13/2020,Mar-20,NET 8,2/13/2020,...,NaN,-3490.00,NaN,NaN,3490.00,0.0,Procurement-Denmark 0% VAT,,,
665,None,- None -,3260056,BL-DK0408947,,Bill,3/3/2020,Mar-20,Net 30,4/2/2020,...,NaN,-58480.54,NaN,NaN,58480.54,0.0,Procurement-Denmark 0% VAT,,,
1578,None,- None -,800583,BL-DK0407578,,Bill,3/6/2020,Mar-20,Due on receipt,3/6/2020,...,NaN,-699.00,NaN,NaN,699.00,0.0,Procurement-Denmark 0% VAT,,,
1927,None,- None -,8.60009E+11,BL-DK0407357,,Bill,3/9/2020,Mar-20,Net 15,3/24/2020,...,NaN,-106.43,NaN,NaN,106.43,0.0,Procurement-Denmark 0% VAT,,,
1928,None,- None -,8.70017E+11,BL-DK0407356,,Bill,3/9/2020,Mar-20,Net 15,3/24/2020,...,NaN,-109.91,NaN,NaN,109.91,0.0,Procurement-Denmark 0% VAT,,,
4071,None,- None -,4312387,BL-DK0408540,,Bill,3/18/2020,Mar-20,Net 14,4/1/2020,...,NaN,-2882.10,NaN,NaN,2882.10,0.0,Procurement-Denmark 0% VAT,,,
4073,None,- None -,4312389,BL-DK0408542,,Bill,3/18/2020,Mar-20,Net 14,4/1/2020,...,NaN,-2591.30,NaN,NaN,2591.30,0.0,Procurement-Denmark 0% VAT,,,

In [31]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == "Transactions 0DKK") &
        (vat['Source System'].isin(['Procurement']) &
        (~vat['Bill to Country'].isin(['Denmark']))), 'Comments'] = 'Procurement-EU/Outside Reverse charge'
vat[vat["Comments"] == "Procurement-EU/Outside Reverse charge"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,Comment 2,VAT reverse charge,VAT No
8,None,- None -,2470,BL-DK0406898,,Bill,2/6/2020,Mar-20,NET 8,2/6/2020,...,NaN,-347811.15,NaN,NaN,347811.15,0.0,Procurement-EU/Outside Reverse charge,,,
9,None,- None -,2471,BL-DK0406899,,Bill,2/6/2020,Mar-20,NET 8,2/6/2020,...,NaN,-69562.23,NaN,NaN,69562.23,0.0,Procurement-EU/Outside Reverse charge,,,
17,None,- None -,12286,BL-DK0407128,,Bill,2/29/2020,Mar-20,Net 60,4/29/2020,...,NaN,-22832.98,NaN,NaN,22832.98,0.0,Procurement-EU/Outside Reverse charge,,,
22,None,- None -,495765,BL-DK0407340,,Bill,2/29/2020,Mar-20,Due on receipt,2/29/2020,...,NaN,-38584.14,NaN,NaN,38584.14,0.0,Procurement-EU/Outside Reverse charge,,,
23,None,- None -,495766,BL-DK0406900,,Bill,2/29/2020,Mar-20,Due on receipt,2/29/2020,...,NaN,-94511.92,NaN,NaN,94511.92,0.0,Procurement-EU/Outside Reverse charge,,,
24,None,- None -,495767,BL-DK0406901,,Bill,2/29/2020,Mar-20,Due on receipt,2/29/2020,...,NaN,-11326.98,NaN,NaN,11326.98,0.0,Procurement-EU/Outside Reverse charge,,,
25,None,- None -,495768,BL-DK0406902,,Bill,2/29/2020,Mar-20,Due on receipt,2/29/2020,...,NaN,-1767.39,NaN,NaN,1767.39,0.0,Procurement-EU/Outside Reverse charge,,,
294,None,- None -,4524,BL-DK0406309,,Bill,3/2/2020,Mar-20,Net 30,4/1/2020,...,NaN,-16209.42,NaN,NaN,16209.42,0.0,Procurement-EU/Outside Reverse charge,,,
993,None,- None -,2474,BL-DK0406769,,Bill,3/4/2020,Mar-20,NET 8,3/4/2020,...,NaN,-342901.55,NaN,NaN,342901.55,0.0,Procurement-EU/Outside Reverse charge,,,
994,None,- None -,2475,BL-DK0406770,,Bill,3/4/2020,Mar-20,NET 8,3/4/2020,...,NaN,-68580.31,NaN,NaN,68580.31,0.0,Procurement-EU/Outside Reverse charge,,,
4069,None,- None -,3882347887,BL-DK0408351,,Bill,3/18/2020,Mar-20,Net 45,5/2/2020,...,NaN,-7936.17,NaN,NaN,7936.17,0.0,Procurement-EU/Outside Reverse charge,,,

In [32]:
## DOES NOT WORK IN THIS CASE

# def proc(row):
    
#     check =row[41]
    
#     if check == 'Procurement-EU/Outside Reverse charge':
#         return vat["Sum of Accounts Payable"] * 0.25
#     else:
#         return ''

    
# vat["VAT reverse charge"] = vat["Comments"].apply(proc)

In [33]:
## DOES NOT WORK IN THIS CASE

# def applyFunc(s):
#     if s == "Procurement-EU/Outside Reverse charge":
#         return vat["Sum of Accounts Payable"] * 0.25
    

# vat["VAT reverse charge"] = vat["Comments"].apply(applyFunc)

In [34]:
#This Method worksin this case
vat['VAT reverse charge'] = np.where(vat['Comments'] == 'Procurement-EU/Outside Reverse charge',vat['Sum of Accounts Payable'] * 0.25, vat['VAT reverse charge'])

In [35]:
#tip from internet
#df.loc[df['product']=='a', ['market_penetration_rate', 'success_rate']] * 100

In [36]:
#tip from internet
# df.apply(lambda row: row[['success_rate', 'market_penetration_rate']]*100 if row['product'] == 'a' 
#      else row[['success_rate', 'market_penetration_rate']], axis=1)

In [37]:
vat[vat["Comments"] == "Procurement-EU/Outside Reverse charge"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,Comment 2,VAT reverse charge,VAT No
8,None,- None -,2470,BL-DK0406898,,Bill,2/6/2020,Mar-20,NET 8,2/6/2020,...,NaN,-347811.15,NaN,NaN,347811.15,0.0,Procurement-EU/Outside Reverse charge,,-86952.8,
9,None,- None -,2471,BL-DK0406899,,Bill,2/6/2020,Mar-20,NET 8,2/6/2020,...,NaN,-69562.23,NaN,NaN,69562.23,0.0,Procurement-EU/Outside Reverse charge,,-17390.6,
17,None,- None -,12286,BL-DK0407128,,Bill,2/29/2020,Mar-20,Net 60,4/29/2020,...,NaN,-22832.98,NaN,NaN,22832.98,0.0,Procurement-EU/Outside Reverse charge,,-5708.24,
22,None,- None -,495765,BL-DK0407340,,Bill,2/29/2020,Mar-20,Due on receipt,2/29/2020,...,NaN,-38584.14,NaN,NaN,38584.14,0.0,Procurement-EU/Outside Reverse charge,,-9646.03,
23,None,- None -,495766,BL-DK0406900,,Bill,2/29/2020,Mar-20,Due on receipt,2/29/2020,...,NaN,-94511.92,NaN,NaN,94511.92,0.0,Procurement-EU/Outside Reverse charge,,-23628,
24,None,- None -,495767,BL-DK0406901,,Bill,2/29/2020,Mar-20,Due on receipt,2/29/2020,...,NaN,-11326.98,NaN,NaN,11326.98,0.0,Procurement-EU/Outside Reverse charge,,-2831.74,
25,None,- None -,495768,BL-DK0406902,,Bill,2/29/2020,Mar-20,Due on receipt,2/29/2020,...,NaN,-1767.39,NaN,NaN,1767.39,0.0,Procurement-EU/Outside Reverse charge,,-441.848,
294,None,- None -,4524,BL-DK0406309,,Bill,3/2/2020,Mar-20,Net 30,4/1/2020,...,NaN,-16209.42,NaN,NaN,16209.42,0.0,Procurement-EU/Outside Reverse charge,,-4052.36,
993,None,- None -,2474,BL-DK0406769,,Bill,3/4/2020,Mar-20,NET 8,3/4/2020,...,NaN,-342901.55,NaN,NaN,342901.55,0.0,Procurement-EU/Outside Reverse charge,,-85725.4,
994,None,- None -,2475,BL-DK0406770,,Bill,3/4/2020,Mar-20,NET 8,3/4/2020,...,NaN,-68580.31,NaN,NaN,68580.31,0.0,Procurement-EU/Outside Reverse charge,,-17145.1,
4069,None,- None -,3882347887,BL-DK0408351,,Bill,3/18/2020,Mar-20,Net 45,5/2/2020,...,NaN,-7936.17,NaN,NaN,7936.17,0.0,Procurement-EU/Outside Reverse charge,,-1984.04,

In [38]:
vat.tail(3)

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,Comment 2,VAT reverse charge,VAT No
5946,GBTICJE,GBTICJE-IDENTIFIERB-ID2125818,JE-NL1263845,TJE-NL0153769,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-998892.66,NaN,998892.66,NaN,0.00,Transactions 0DKK,,,
5947,GBTICJE,GBTICJE-IDENTIFIERB-ID2128891,JE-NL1264110,TJE-NL0154034,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-38095.45,-9523.86,NaN,38095.45,9523.86,IC reverse charge EU/Outside,,Reverse charge booked automatically in Netsuite,
5948,None,- None -,XXXXXXXXXXX3103- V-Pay,BC-DK0126114,,Bill Credit,3/31/2020,Mar-20,- None -,NaN,...,-75177.78,75177.78,NaN,NaN,NaN,0.00,Transactions 0DKK,,,

In [39]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == "Transactions 0DKK") &
        (vat['Source System'].isin(['NEO'])), 'Comments'] = 'Neo travel expense - no vat'
vat[vat["Comments"] == "Neo travel expense - no vat"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,Comment 2,VAT reverse charge,VAT No
295,KDS_Exp_VB_5046988,KDS_Exp_VB_5046988.2020-03-02-1,5046988.2020-03-02-1,BL-DK0406433,,Bill,3/2/2020,Mar-20,Due on receipt,3/2/2020,...,NaN,-30724.34,30724.34,NaN,NaN,0.0,Neo travel expense - no vat,,,
297,KDS_Exp_VB_6247332,KDS_Exp_VB_6247332.2020-03-02-1,6247332.2020-03-02-1,BL-DK0406434,,Bill,3/2/2020,Mar-20,Due on receipt,3/2/2020,...,NaN,-4981.41,4981.41,NaN,NaN,0.0,Neo travel expense - no vat,,,
298,KDS_Exp_VB_8008094,KDS_Exp_VB_8008094.2020-03-02-1,8008094.2020-03-02-1,BL-DK0406435,,Bill,3/2/2020,Mar-20,Due on receipt,3/2/2020,...,NaN,-6231.85,6231.85,NaN,NaN,0.0,Neo travel expense - no vat,,,
669,KDS_Exp_VB_348600,KDS_Exp_VB_348600,348600,BL-DK0406445,,Bill,3/3/2020,Mar-20,Due on receipt,3/3/2020,...,NaN,-832.85,NaN,NaN,832.85,0.0,Neo travel expense - no vat,,,
670,KDS_Exp_VB_348624,KDS_Exp_VB_348624,348624,BL-DK0406446,,Bill,3/3/2020,Mar-20,Due on receipt,3/3/2020,...,NaN,-1772.41,NaN,NaN,1772.41,0.0,Neo travel expense - no vat,,,
672,KDS_Exp_VB_8008094,KDS_Exp_VB_8008094.2020-03-03-1,8008094.2020-03-03-1,BL-DK0406657,,Bill,3/3/2020,Mar-20,Due on receipt,3/3/2020,...,NaN,-108645.78,108645.78,NaN,NaN,0.0,Neo travel expense - no vat,,,
676,KDS_Exp_JE_347817__OOP,KDS_Exp_JE_347817__OOP,JE-DK0288528,TJE-DK0288528,,Journal,3/3/2020,Mar-20,- None -,NaN,...,NaN,NaN,-387.81,NaN,387.81,0.0,Neo travel expense - no vat,,,
1017,KDS_Exp_VB_342819,KDS_Exp_VB_342819,342819,BL-DK0406659,,Bill,3/4/2020,Mar-20,Due on receipt,3/4/2020,...,NaN,-4303.47,NaN,NaN,4303.47,0.0,Neo travel expense - no vat,,,
1571,KDS_Exp_VB_340001,KDS_Exp_VB_340001,340001,BL-DK0406956,,Bill,3/6/2020,Mar-20,Due on receipt,3/6/2020,...,NaN,-2081.54,NaN,NaN,2081.54,0.0,Neo travel expense - no vat,,,
1575,KDS_Exp_VB_6353386,KDS_Exp_VB_6353386.2020-03-06-1,6353386.2020-03-06-1,BL-DK0407082,,Bill,3/6/2020,Mar-20,Due on receipt,3/6/2020,...,NaN,-46571.96,46571.96,NaN,NaN,0.0,Neo travel expense - no vat,,,
1582,KDS_Exp_JE_340001__OOP,KDS_Exp_JE_340001__OOP,JE-DK0288934,TJE-DK0288934,,Journal,3/6/2020,Mar-20,- None -,NaN,...,NaN,NaN,-278.84,NaN,278.84,0.0,Neo travel expense - no vat,,,
2107,KDS_Exp_VB_342344,KDS_Exp_VB_342344,342344,BL-DK0407217,,Bill,3/10/2020,Mar-20,Due on receipt,3/10/2020,...,NaN,-2116.76,NaN,NaN,2116.76,0.0,Neo travel expense - no vat,,,
2119,KDS_Exp_JE_348723__OOP,KDS_Exp_JE_348723__OOP,JE-DK0289194,TJE-DK0289194,,Journal,3/10/2020,Mar-20,- None -,NaN,...,NaN,NaN,-2477.00,NaN,2477.00,0.0,Neo travel expense - no vat,,,
2352,KDS_Exp_JE_348708__OOP,KDS_Exp_JE_348708__OOP,JE-DK0289281,TJE-DK0289281,,Journal,3/11/2020,Mar-20,- None -,NaN,...,NaN,NaN,-3655.83,NaN,3655.83,0.0,Neo travel expense - no vat,,,
2353,KDS_Exp_JE_350738__OOP,KDS_Exp_JE_350738__OOP,JE-DK0289282,TJE-DK0289282,,Journal,3/11/2020,Mar-20,- None -,NaN,...,NaN,NaN,-2289.33,NaN,2289.33,0.0,Neo travel expense - no vat,,,
2763,KDS_Exp_VB_351249,KDS_Exp_VB_351249,351249,BL-DK0407443,,Bill,3/12/2020,Mar-20,Due on receipt,3/12/2020,...,NaN,-5244.94,NaN,NaN,5244.94,0.0,Neo travel expense - no vat,,,
2770,KDS_Exp_JE_351254__OOP,KDS_Exp_JE_351254__OOP,JE-DK0289481,TJE-DK0289481,,Journal,3/12/2020,Mar-20,- None -,NaN,...,NaN,NaN,-248.80,NaN,248.80,0.0,Neo travel expense - no vat,,,
3176,KDS_Exp_VB_351095,KDS_Exp_VB_351095,351095,BL-DK0407653,,Bill,3/14/2020,Mar-20,Due on receipt,3/14/2020,...,NaN,-1621.53,NaN,NaN,1621.53,0.0,Neo travel expense - no vat,,,
3177,KDS_Exp_JE_352152__OOP,KDS_Exp_JE_352152__OOP,JE-DK0289627,TJE-DK0289627,,Journal,3/14/2020,Mar-20,- None -,NaN,...,NaN,NaN,-897.00,NaN,897.00,0.0,Neo travel expense - no vat,,,
4075,KDS_Exp_VB_5046988,KDS_Exp_VB_5046988.2020-03-18-1,5046988.2020-03-18-1,BL-DK0408233,,Bill,3/18/2020,Mar-20,Due on receipt,3/18/2020,...,NaN,-3045.00,3045.00,NaN,NaN,0.0,Neo travel expense - no vat,,,
4076,KDS_Exp_VC_8008094,KDS_Exp_VC_8008094.2020-03-18-1-CR,8008094.2020-03-18-1-CR,BC-DK0125984,,Bill Credit,3/18/2020,Mar-20,- None -,NaN,...,NaN,4348.48,-4348.48,NaN,NaN,0.0,Neo travel expense - no vat,,,
4528,KDS_Exp_VC_6247332,KDS_Exp_VC_6247332.2020-03-19-1-CR,6247332.2020-03-19-1-CR,BC-DK0126022,,Bill Credit,3/19/2020,Mar-20,- None -,NaN,...,NaN,10743.70,-10743.70,NaN,NaN,0.0,Neo travel expense - no vat,,,
4529,KDS_Exp_VB_6299271,KDS_Exp_VB_6299271.2020-03-19-1,6299271.2020-03-19-1,BL-DK0408463,,Bill,3/19/2020,Mar-20,Due on receipt,3/19/2020,...,NaN,-6879.36,6879.36,NaN,NaN,0.0,Neo travel expense - no vat,,,
4530,KDS_Exp_VB_8006463,KDS_Exp_VB_8006463.2020-03-19-1,8006463.2020-03-19-1,BL-DK0408464,,Bill,3/19/2020,Mar-20,Due on receipt,3/19/2020,...,NaN,-100250.40,100250.40,NaN,NaN,0.0,Neo travel expense - no vat,,,
4531,KDS_Exp_VC_8006463,KDS_Exp_VC_8006463.2020-03-19-1-CR,8006463.2020-03-19-1-CR,BC-DK0126023,,Bill Credit,3/19/2020,Mar-20,- None -,NaN,...,NaN,17117.97,-17117.97,NaN,NaN,0.0,Neo travel expense - no vat,,,
5178,KDS_Exp_VB_347832,KDS_Exp_VB_347832,347832,BL-DK0408740,,Bill,3/24/2020,Mar-20,Due on receipt,3/24/2020,...,NaN,-4700.49,NaN,NaN,4700.49,0.0,Neo travel expense - no vat,,,
5179,KDS_Exp_VB_5046988,KDS_Exp_VB_5046988.2020-03-24-1,5046988.2020-03-24-1,BL-DK0408795,,Bill,3/24/2020,Mar-20,Due on receipt,3/24/2020,...,NaN,-174.53,174.53,NaN,NaN,0.0,Neo travel expense - no vat,,,
5182,KDS_Exp_JE_351119__OOP,KDS_Exp_JE_351119__OOP,JE-DK0290263,TJE-DK0290263,,Journal,3/24/2020,Mar-20,- None -,NaN,...,NaN,NaN,-309.00,NaN,309.00,0.0,Neo travel expense - no vat,,,
5561,KDS_Exp_JE_354006__OOP,KDS_Exp_JE_354006__OOP,JE-DK0290502,TJE-DK0290502,,Journal,3/27/2020,Mar-20,- None -,NaN,...,NaN,NaN,-656.72,NaN,656.72,0.0,Neo travel expense - no vat,,,
5769,KDS_Exp_VB_339424,KDS_Exp_VB_339424,339424,BL-DK0408955,,Bill,3/31/2020,Mar-20,Due on receipt,3/31/2020,...,NaN,-155.80,NaN,NaN,155.80,0.0,Neo travel expense - no vat,,,
5781,KDS_Exp_JE_339424__OOP,KDS_Exp_JE_339424__OOP,JE-DK0290616,TJE-DK0290616,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,NaN,-65.00,NaN,65.00,0.0,Neo travel expense - no vat,,,
5783,KDS_Exp_JE_354303__OOP,KDS_Exp_JE_354303__OOP,JE-DK0290618,TJE-DK0290618,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,NaN,-793.58,NaN,793.58,0.0,Neo travel expense - no vat,,,
5784,KDS_Exp_JE_354460__OOP,KDS_Exp_JE_354460__OOP,JE-DK0290619,TJE-DK0290619,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,NaN,-92.70,NaN,92.70,0.0,Neo travel expense - no vat,,,

In [40]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == "Transactions 0DKK") &
        (vat['External name'] == 'GBTICJE') &
        (vat['Maximum of NetSuite Tax Item'].notnull()), 'Comments'] = 'IC Invoice - EU Sales/IC Invoice - Outside EU'
vat[vat["Comments"] == "IC Invoice - EU Sales/IC Invoice - Outside EU"]
#'DK-S : DK-ESSS', 'DK-OS'

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,Comment 2,VAT reverse charge,VAT No
5665,GBTICJE,GBTICJE-IDENTIFIERB-ID2118282,JE-NL1262716,TJE-NL0152640,,Journal,3/29/2020,Mar-20,- None -,NaN,...,NaN,-33546.36,0.0,33546.36,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5666,GBTICJE,GBTICJE-IDENTIFIERH-ID2123084,JE-NL1263185,TJE-NL0153109,,Journal,3/29/2020,Mar-20,- None -,NaN,...,33546.36,NaN,0.0,-33546.36,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5667,GBTICJE,GBTICJE-IDENTIFIERB-ID2123089,JE-NL1263187,TJE-NL0153111,,Journal,3/29/2020,Mar-20,- None -,NaN,...,NaN,-66370.58,0.0,66370.58,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5806,GBTICJE,GBTICJE-IDENTIFIERA-ID2115288,JE-DK0290642,TJE-DK0290642,,Journal,3/31/2020,Mar-20,- None -,NaN,...,2240.42,NaN,0.0,-2240.42,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5807,GBTICJE,GBTICJE-IDENTIFIERA-ID2115297,JE-DK0290643,TJE-DK0290643,,Journal,3/31/2020,Mar-20,- None -,NaN,...,2707.17,NaN,0.0,-2707.17,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5808,GBTICJE,GBTICJE-IDENTIFIERA-ID2115289,JE-DK0290644,TJE-DK0290644,,Journal,3/31/2020,Mar-20,- None -,NaN,...,809.04,NaN,0.0,-809.04,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5809,GBTICJE,GBTICJE-IDENTIFIERA-ID2115290,JE-DK0290645,TJE-DK0290645,,Journal,3/31/2020,Mar-20,- None -,NaN,...,1991.48,NaN,0.0,-1991.48,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5810,GBTICJE,GBTICJE-IDENTIFIERA-ID2115294,JE-DK0290646,TJE-DK0290646,,Journal,3/31/2020,Mar-20,- None -,NaN,...,6285.62,NaN,0.0,-6285.62,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5811,GBTICJE,GBTICJE-IDENTIFIERA-ID2115291,JE-DK0290647,TJE-DK0290647,,Journal,3/31/2020,Mar-20,- None -,NaN,...,217.82,NaN,0.0,-217.82,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5812,GBTICJE,GBTICJE-IDENTIFIERA-ID2115293,JE-DK0290648,TJE-DK0290648,,Journal,3/31/2020,Mar-20,- None -,NaN,...,403679.89,NaN,0.0,-403679.89,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5813,GBTICJE,GBTICJE-IDENTIFIERA-ID2115292,JE-DK0290649,TJE-DK0290649,,Journal,3/31/2020,Mar-20,- None -,NaN,...,116750.71,NaN,0.0,-116750.71,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5814,GBTICJE,GBTICJE-IDENTIFIERA-ID2115295,JE-DK0290650,TJE-DK0290650,,Journal,3/31/2020,Mar-20,- None -,NaN,...,373.40,NaN,0.0,-373.40,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5815,GBTICJE,GBTICJE-IDENTIFIERA-ID2115296,JE-DK0290651,TJE-DK0290651,,Journal,3/31/2020,Mar-20,- None -,NaN,...,65283.31,NaN,0.0,-65283.31,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5816,GBTICJE,GBTICJE-IDENTIFIERA-ID2115298,JE-DK0290652,TJE-DK0290652,,Journal,3/31/2020,Mar-20,- None -,NaN,...,3609.56,NaN,0.0,-3609.56,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5817,GBTICJE,GBTICJE-IDENTIFIERA-ID2115299,JE-DK0290653,TJE-DK0290653,,Journal,3/31/2020,Mar-20,- None -,NaN,...,11139.86,NaN,0.0,-11139.86,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5818,GBTICJE,GBTICJE-IDENTIFIERA-ID2115300,JE-DK0290654,TJE-DK0290654,,Journal,3/31/2020,Mar-20,- None -,NaN,...,11980.02,NaN,0.0,-11980.02,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5819,GBTICJE,GBTICJE-IDENTIFIERA-ID2115301,JE-DK0290655,TJE-DK0290655,,Journal,3/31/2020,Mar-20,- None -,NaN,...,27040.61,NaN,0.0,-27040.61,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5820,GBTICJE,GBTICJE-IDENTIFIERA-ID2115302,JE-DK0290656,TJE-DK0290656,,Journal,3/31/2020,Mar-20,- None -,NaN,...,12602.36,NaN,0.0,-12602.36,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5821,GBTICJE,GBTICJE-IDENTIFIERA-ID2115303,JE-DK0290657,TJE-DK0290657,,Journal,3/31/2020,Mar-20,- None -,NaN,...,5943.33,NaN,0.0,-5943.33,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5822,GBTICJE,GBTICJE-IDENTIFIERA-ID2115304,JE-DK0290658,TJE-DK0290658,,Journal,3/31/2020,Mar-20,- None -,NaN,...,9957.42,NaN,0.0,-9957.42,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5823,GBTICJE,GBTICJE-IDENTIFIERA-ID2115305,JE-DK0290659,TJE-DK0290659,,Journal,3/31/2020,Mar-20,- None -,NaN,...,75085.14,NaN,0.0,-75085.14,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5824,GBTICJE,GBTICJE-IDENTIFIERA-ID2115306,JE-DK0290660,TJE-DK0290660,,Journal,3/31/2020,Mar-20,- None -,NaN,...,59028.81,NaN,0.0,-59028.81,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5825,GBTICJE,GBTICJE-IDENTIFIERA-ID2115308,JE-DK0290661,TJE-DK0290661,,Journal,3/31/2020,Mar-20,- None -,NaN,...,10486.40,NaN,0.0,-10486.40,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5826,GBTICJE,GBTICJE-IDENTIFIERA-ID2115309,JE-DK0290662,TJE-DK0290662,,Journal,3/31/2020,Mar-20,- None -,NaN,...,62.23,NaN,0.0,-62.23,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5827,GBTICJE,GBTICJE-IDENTIFIERA-ID2115311,JE-DK0290663,TJE-DK0290663,,Journal,3/31/2020,Mar-20,- None -,NaN,...,3018.34,NaN,0.0,-3018.34,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5828,GBTICJE,GBTICJE-IDENTIFIERA-ID2115307,JE-DK0290664,TJE-DK0290664,,Journal,3/31/2020,Mar-20,- None -,NaN,...,4947.59,NaN,0.0,-4947.59,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5829,GBTICJE,GBTICJE-IDENTIFIERA-ID2115314,JE-DK0290665,TJE-DK0290665,,Journal,3/31/2020,Mar-20,- None -,NaN,...,11980.02,NaN,0.0,-11980.02,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5830,GBTICJE,GBTICJE-IDENTIFIERA-ID2115313,JE-DK0290666,TJE-DK0290666,,Journal,3/31/2020,Mar-20,- None -,NaN,...,31210.28,NaN,0.0,-31210.28,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5831,GBTICJE,GBTICJE-IDENTIFIERA-ID2115316,JE-DK0290667,TJE-DK0290667,,Journal,3/31/2020,Mar-20,- None -,NaN,...,1711.43,NaN,0.0,-1711.43,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5832,GBTICJE,GBTICJE-IDENTIFIERA-ID2115315,JE-DK0290668,TJE-DK0290668,,Journal,3/31/2020,Mar-20,- None -,NaN,...,1213.56,NaN,0.0,-1213.56,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5833,GBTICJE,GBTICJE-IDENTIFIERA-ID2115310,JE-DK0290669,TJE-DK0290669,,Journal,3/31/2020,Mar-20,- None -,NaN,...,528.99,NaN,0.0,-528.99,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5834,GBTICJE,GBTICJE-IDENTIFIERA-ID2115318,JE-DK0290670,TJE-DK0290670,,Journal,3/31/2020,Mar-20,- None -,NaN,...,560.10,NaN,0.0,-560.10,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5835,GBTICJE,GBTICJE-IDENTIFIERA-ID2115312,JE-DK0290671,TJE-DK0290671,,Journal,3/31/2020,Mar-20,- None -,NaN,...,62.23,NaN,0.0,-62.23,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5836,GBTICJE,GBTICJE-IDENTIFIERA-ID2115319,JE-DK0290672,TJE-DK0290672,,Journal,3/31/2020,Mar-20,- None -,NaN,...,53676.70,NaN,0.0,-53676.70,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5837,GBTICJE,GBTICJE-IDENTIFIERA-ID2115320,JE-DK0290673,TJE-DK0290673,,Journal,3/31/2020,Mar-20,- None -,NaN,...,6472.32,NaN,0.0,-6472.32,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5838,GBTICJE,GBTICJE-IDENTIFIERA-ID2115321,JE-DK0290674,TJE-DK0290674,,Journal,3/31/2020,Mar-20,- None -,NaN,...,1618.08,NaN,0.0,-1618.08,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5839,GBTICJE,GBTICJE-IDENTIFIERA-ID2115322,JE-DK0290675,TJE-DK0290675,,Journal,3/31/2020,Mar-20,- None -,NaN,...,12789.06,NaN,0.0,-12789.06,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5840,GBTICJE,GBTICJE-IDENTIFIERA-ID2115323,JE-DK0290676,TJE-DK0290676,,Journal,3/31/2020,Mar-20,- None -,NaN,...,41198.81,NaN,0.0,-41198.81,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5841,GBTICJE,GBTICJE-IDENTIFIERA-ID2115324,JE-DK0290677,TJE-DK0290677,,Journal,3/31/2020,Mar-20,- None -,NaN,...,8526.04,NaN,0.0,-8526.04,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,
5842,GBTICJE,GBTICJE-IDENTIFIERA-ID2115317,JE-DK0290678,TJE-DK0290678,,Journal,3/31/2020,Mar-20,- None -,NaN,...,2147.07,NaN,0.0,-2147.07,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,,

In [41]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == "Transactions 0DKK") &
        (vat['External name'] == 'GBTICJE') &
        (vat['Maximum of NetSuite Tax Item'].isnull()), 'Comments'] = 'Intercompany no IC invoice'
vat[vat["Comments"] == "Intercompany no IC invoice"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,Comment 2,VAT reverse charge,VAT No
101,GBTICJE,GBTICJE-IDENTIFIERH-ID2079345,JE-NL1258535,TJE-NL0148459,,Journal,3/1/2020,Mar-20,- None -,NaN,...,1403600.72,NaN,NaN,-1403600.72,NaN,0.0,Intercompany no IC invoice,,,
102,GBTICJE,GBTICJE-IDENTIFIERB-ID2079344,JE-NL1258536,TJE-NL0148460,,Journal,3/1/2020,Mar-20,- None -,NaN,...,NaN,-1559556.34,NaN,1559556.34,NaN,0.0,Intercompany no IC invoice,,,
2884,GBTICJE,GBTICJE-IDENTIFIERH-ID2094966,JE-NL1260345,TJE-NL0150269,,Journal,3/12/2020,Mar-20,- None -,NaN,...,0.00,NaN,NaN,NaN,NaN,0.0,Intercompany no IC invoice,,,
3166,GBTICJE,GBTICJE-IDENTIFIERH-ID2096667,JE-NL1260381,TJE-NL0150305,,Journal,3/13/2020,Mar-20,- None -,NaN,...,520.60,NaN,NaN,-520.60,NaN,0.0,Intercompany no IC invoice,,,
3167,GBTICJE,GBTICJE-IDENTIFIERB-ID2096668,JE-NL1260382,TJE-NL0150306,,Journal,3/13/2020,Mar-20,- None -,NaN,...,NaN,-479.12,NaN,479.12,NaN,0.0,Intercompany no IC invoice,,,
3471,GBTICJE,GBTICJE-IDENTIFIERH-ID2101171,JE-NL1260905,TJE-NL0150829,,Journal,3/16/2020,Mar-20,- None -,NaN,...,27169.31,NaN,NaN,-27169.31,NaN,0.0,Intercompany no IC invoice,,,
3472,GBTICJE,GBTICJE-IDENTIFIERB-ID2101170,JE-NL1260906,TJE-NL0150830,,Journal,3/16/2020,Mar-20,- None -,NaN,...,NaN,-30188.12,NaN,30188.12,NaN,0.0,Intercompany no IC invoice,,,
4247,GBTICJE,GBTICJE-IDENTIFIERH-ID2101879,JE-NL1260926,TJE-NL0150850,,Journal,3/18/2020,Mar-20,- None -,NaN,...,609.49,NaN,-609.49,NaN,NaN,0.0,Intercompany no IC invoice,,,
5212,GBTICJE,GBTICJE-IDENTIFIERB-ID2105979,JE-NL1261226,TJE-NL0151150,,Journal,3/24/2020,Mar-20,- None -,NaN,...,NaN,-3360.73,3360.73,NaN,NaN,0.0,Intercompany no IC invoice,,,
5745,GBTICJE,GBTICJE-IDENTIFIERH-ID2112673,JE-NL1262169,TJE-NL0152093,,Journal,3/30/2020,Mar-20,- None -,NaN,...,0.00,NaN,NaN,NaN,NaN,0.0,Intercompany no IC invoice,,,
5746,GBTICJE,GBTICJE-IDENTIFIERH-ID2114074,JE-NL1262253,TJE-NL0152177,,Journal,3/30/2020,Mar-20,- None -,NaN,...,0.00,NaN,NaN,NaN,NaN,0.0,Intercompany no IC invoice,,,
5747,GBTICJE,GBTICJE-IDENTIFIERB-ID2121981,JE-NL1262995,TJE-NL0152919,,Journal,3/30/2020,Mar-20,- None -,NaN,...,NaN,-4588.55,NaN,4588.55,NaN,0.0,Intercompany no IC invoice,,,
5748,GBTICJE,GBTICJE-IDENTIFIERH-ID2121982,JE-NL1263000,TJE-NL0152924,,Journal,3/30/2020,Mar-20,- None -,NaN,...,4830.05,NaN,NaN,-4830.05,NaN,0.0,Intercompany no IC invoice,,,
5921,GBTICJE,GBTICJE-IDENTIFIERB-ID2110873,JE-NL1262019,TJE-NL0151943,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-89629.18,NaN,NaN,89629.18,0.0,Intercompany no IC invoice,,,
5922,GBTICJE,GBTICJE-IDENTIFIERB-ID2110910,JE-NL1262049,TJE-NL0151973,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-1009.90,NaN,NaN,1009.90,0.0,Intercompany no IC invoice,,,
5923,GBTICJE,GBTICJE-IDENTIFIERB-ID2110922,JE-NL1262061,TJE-NL0151985,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-16032.24,NaN,NaN,16032.24,0.0,Intercompany no IC invoice,,,
5924,GBTICJE,GBTICJE-IDENTIFIERB-ID2110944,JE-NL1262083,TJE-NL0152007,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-2146.08,NaN,NaN,2146.08,0.0,Intercompany no IC invoice,,,
5929,GBTICJE,GBTICJE-IDENTIFIERB-ID2114585,JE-NL1262389,TJE-NL0152313,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-29344.64,NaN,NaN,29344.64,0.0,Intercompany no IC invoice,,,
5935,GBTICJE,GBTICJE-IDENTIFIERB-ID2116084,JE-NL1262568,TJE-NL0152492,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-122782.65,NaN,NaN,122782.65,0.0,Intercompany no IC invoice,,,
5936,GBTICJE,GBTICJE-IDENTIFIERB-ID2116183,JE-NL1262588,TJE-NL0152512,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-22771.36,NaN,NaN,22771.36,0.0,Intercompany no IC invoice,,,
5938,GBTICJE,GBTICJE-IDENTIFIERB-ID2116692,JE-NL1262618,TJE-NL0152542,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-22621.03,NaN,NaN,22621.03,0.0,Intercompany no IC invoice,,,
5939,GBTICJE,GBTICJE-IDENTIFIERB-ID2121592,JE-NL1262963,TJE-NL0152887,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-9434.53,NaN,NaN,9434.53,0.0,Intercompany no IC invoice,,,
5945,GBTICJE,GBTICJE-IDENTIFIERH-ID2125817,JE-NL1263844,TJE-NL0153768,,Journal,3/31/2020,Mar-20,- None -,NaN,...,1109880.72,NaN,NaN,-1109880.72,NaN,0.0,Intercompany no IC invoice,,,
5946,GBTICJE,GBTICJE-IDENTIFIERB-ID2125818,JE-NL1263845,TJE-NL0153769,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,-998892.66,NaN,998892.66,NaN,0.0,Intercompany no IC invoice,,,

In [42]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == "Transactions 0DKK") &
        (vat['Type'].isin(['Journal'])), 'Comments'] = 'JE-transactions no vat'
vat[vat["Comments"] == "JE-transactions no vat"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,Comment 2,VAT reverse charge,VAT No
0,FINREP_bjhamb_253150,20200101_FINREP_bjhamb_253150 account reclass_06,JE-DK0289677,TJE-DK0289677,,Journal,1/1/2020,Mar-20,- None -,NaN,...,NaN,NaN,0.00,NaN,NaN,0.0,JE-transactions no vat,,,
1,SUMVOID,565788256-SUMVOID,JE-DK0290724,TJE-DK0290724,Credit Memo #CM-DK0296577,Journal,1/20/2020,Mar-20,- None -,NaN,...,NaN,NaN,NaN,0.0,NaN,0.0,JE-transactions no vat,,,
2,SUMVOID,565788266-SUMVOID,JE-DK0290725,TJE-DK0290725,Credit Memo #CM-DK0296581,Journal,1/20/2020,Mar-20,- None -,NaN,...,NaN,NaN,NaN,0.0,NaN,0.0,JE-transactions no vat,,,
3,SUMVOID,566326875-SUMVOID,JE-DK0290726,TJE-DK0290726,Credit Memo #CM-DK0296872,Journal,1/22/2020,Mar-20,- None -,NaN,...,NaN,NaN,NaN,0.0,NaN,0.0,JE-transactions no vat,,,
4,SUMVOID,566326931-SUMVOID,JE-DK0290727,TJE-DK0290727,Credit Memo #CM-DK0296892,Journal,1/22/2020,Mar-20,- None -,NaN,...,NaN,NaN,NaN,0.0,NaN,0.0,JE-transactions no vat,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5905,FINREP_snakk3_AIAtax4,20200331_FINREP_snakk3_AIAtax4,JE-DK0290873,TJE-DK0290873,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,NaN,-12751.54,NaN,12751.54,0.0,JE-transactions no vat,,,
5906,None,- None -,JE-DK0290875,TJE-DK0290875,,Journal,3/31/2020,Mar-20,- None -,NaN,...,0.00,NaN,NaN,NaN,NaN,0.0,JE-transactions no vat,,,
5907,GSD_jkuper_Region,20200331_GSD_jkuper_Region Cleanup_GG210r-dk,JE-DK0290877,TJE-DK0290877,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,NaN,NaN,NaN,0.00,0.0,JE-transactions no vat,,,
5919,FINREP_FCCA,20200331_FINREP_FCCA Clearance_1115_AG2_Mar'20,JE-DK0290917,TJE-DK0290917,,Journal,3/31/2020,Mar-20,- None -,NaN,...,139.32,NaN,NaN,NaN,-139.32,0.0,JE-transactions no vat,,,
5920,FINREP_snakk3_AIAtax11,20200331_FINREP_snakk3_AIAtax11,JE-DK0290957,TJE-DK0290957,,Journal,3/31/2020,Mar-20,- None -,NaN,...,NaN,NaN,51232.64,NaN,-51232.64,0.0,JE-transactions no vat,,,

In [43]:
## REMEMBER TO CHECK THAT ALL OF THE SPACES IN THE BLANK CELLS IN THE CSV FILE ARE REMOVED AS WELL!!!

vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == 'Transactions 0DKK') &
        (vat['Type'].isin(['Bill','Bill Credit'])) &
        (~vat['Maximum of Linked Invoice'].isin([np.nan, ' '])), 'Comments'] = 'Linked invoice'
vat[vat["Comments"] == "Linked invoice"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,Comment 2,VAT reverse charge,VAT No
28,VB,00380287939-1289112-010-001-VB,00380287939-1289112-010-001,BL-DK0406275,Invoice #IN-DK4695663,Bill,3/1/2020,Mar-20,- None -,3/1/2020,...,NaN,-1010.00,NaN,1010.00,NaN,0.0,Linked invoice,,,
29,VB,00381646059-1289089-012-001-VB,00381646059-1289089-012-001,BL-DK0406276,Invoice #IN-DK4695673,Bill,3/1/2020,Mar-20,- None -,3/1/2020,...,NaN,-386.80,NaN,386.80,NaN,0.0,Linked invoice,,,
30,VB,00382201135-1289060-001-001-VB,00382201135-1289060-001-001,BL-DK0406273,Invoice #IN-DK4695564,Bill,3/1/2020,Mar-20,- None -,3/1/2020,...,NaN,-1853.00,NaN,1853.00,NaN,0.0,Linked invoice,,,
31,VB,00382201145-1289102-005-001-VB,00382201145-1289102-005-001,BL-DK0406278,Invoice #IN-DK4695768,Bill,3/1/2020,Mar-20,- None -,3/1/2020,...,NaN,-823.29,NaN,823.29,NaN,0.0,Linked invoice,,,
32,VB,00382201196-1289076-001-001-VB,00382201196-1289076-001-001,BL-DK0406274,Invoice #IN-DK4695591,Bill,3/1/2020,Mar-20,- None -,3/1/2020,...,NaN,-2503.00,NaN,2503.00,NaN,0.0,Linked invoice,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5759,VB,00383800438-1308222-001-001-VB,00383800438-1308222-001-001,BL-DK0408966,Invoice #IN-DK4748471,Bill,3/31/2020,Mar-20,- None -,3/31/2020,...,NaN,-109.00,NaN,109.00,NaN,0.0,Linked invoice,,,
5760,VB,00383800446-1308220-001-001-VB,00383800446-1308220-001-001,BL-DK0408967,Invoice #IN-DK4748472,Bill,3/31/2020,Mar-20,- None -,3/31/2020,...,NaN,-109.00,NaN,109.00,NaN,0.0,Linked invoice,,,
5761,VB,00383800447-1308221-001-001-VB,00383800447-1308221-001-001,BL-DK0408968,Invoice #IN-DK4748473,Bill,3/31/2020,Mar-20,- None -,3/31/2020,...,NaN,-109.00,NaN,109.00,NaN,0.0,Linked invoice,,,
5762,VB,00383800458-1308223-001-001-VB,00383800458-1308223-001-001,BL-DK0408969,Invoice #IN-DK4748476,Bill,3/31/2020,Mar-20,- None -,3/31/2020,...,NaN,-109.00,NaN,109.00,NaN,0.0,Linked invoice,,,
5763,VB,00383800459-1308224-001-001-VB,00383800459-1308224-001-001,BL-DK0408970,Invoice #IN-DK4748477,Bill,3/31/2020,Mar-20,- None -,3/31/2020,...,NaN,-109.00,NaN,109.00,NaN,0.0,Linked invoice,,,

In [44]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == 'Transactions 0DKK') &
        (~vat['Memo (Main)'].isin(['- None -'])), 'Comments'] = 'Travel Bill'
vat[vat["Comments"] == "Travel Bill"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,Comment 2,VAT reverse charge,VAT No
292,None,- None -,2582,BL-DK0406393,,Bill,3/2/2020,Mar-20,Due on receipt,3/2/2020,...,NaN,-136060.41,136060.41,NaN,NaN,0.0,Travel Bill,,,
293,None,- None -,3260232298,BL-DK0406334,,Bill,3/2/2020,Mar-20,Due on receipt,3/2/2020,...,NaN,-5921.26,5921.26,NaN,NaN,0.0,Travel Bill,,,
299,None,- None -,I09010000189175,BL-DK0406436,,Bill,3/2/2020,Mar-20,Net 15,3/10/2020,...,NaN,-2105.58,NaN,2105.58,NaN,0.0,Travel Bill,,,
300,None,- None -,I09010000190741,BL-DK0406289,,Bill,3/2/2020,Mar-20,Net 15,3/10/2020,...,NaN,-3798.01,NaN,3798.01,NaN,0.0,Travel Bill,,,
673,None,- None -,99011695,BC-DK0125263,,Bill Credit,3/3/2020,Mar-20,- None -,NaN,...,NaN,375.00,NaN,-375.00,NaN,0.0,Travel Bill,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5712,None,- None -,87288608,BL-DK0408937,,Bill,3/30/2020,Mar-20,Net 15,4/8/2020,...,NaN,-2645.83,NaN,2645.83,NaN,0.0,Travel Bill,,,
5713,None,- None -,I09118002290110,BL-DK0408924,,Bill,3/30/2020,Mar-20,Net 15,4/29/2020,...,NaN,-3417.85,NaN,3417.85,NaN,0.0,Travel Bill,,,
5714,None,- None -,I09118002356352,BL-DK0408926,,Bill,3/30/2020,Mar-20,Due on receipt,4/1/2020,...,NaN,-503.23,NaN,503.23,NaN,0.0,Travel Bill,,,
5715,None,- None -,I09118002373362,BL-DK0408928,,Bill,3/30/2020,Mar-20,Due on receipt,4/1/2020,...,NaN,-604.31,NaN,604.31,NaN,0.0,Travel Bill,,,
5948,None,- None -,XXXXXXXXXXX3103- V-Pay,BC-DK0126114,,Bill Credit,3/31/2020,Mar-20,- None -,NaN,...,-75177.78,75177.78,NaN,NaN,NaN,0.0,Travel Bill,,,

In [45]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == 'Transactions 0DKK'), 'Comments'] = 'Travel Bill'
vat[vat["Comments"] == "Travel Bill"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,Comment 2,VAT reverse charge,VAT No
292,None,- None -,2582,BL-DK0406393,,Bill,3/2/2020,Mar-20,Due on receipt,3/2/2020,...,NaN,-136060.41,136060.41,NaN,NaN,0.0,Travel Bill,,,
293,None,- None -,3260232298,BL-DK0406334,,Bill,3/2/2020,Mar-20,Due on receipt,3/2/2020,...,NaN,-5921.26,5921.26,NaN,NaN,0.0,Travel Bill,,,
299,None,- None -,I09010000189175,BL-DK0406436,,Bill,3/2/2020,Mar-20,Net 15,3/10/2020,...,NaN,-2105.58,NaN,2105.58,NaN,0.0,Travel Bill,,,
300,None,- None -,I09010000190741,BL-DK0406289,,Bill,3/2/2020,Mar-20,Net 15,3/10/2020,...,NaN,-3798.01,NaN,3798.01,NaN,0.0,Travel Bill,,,
673,None,- None -,99011695,BC-DK0125263,,Bill Credit,3/3/2020,Mar-20,- None -,NaN,...,NaN,375.00,NaN,-375.00,NaN,0.0,Travel Bill,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5712,None,- None -,87288608,BL-DK0408937,,Bill,3/30/2020,Mar-20,Net 15,4/8/2020,...,NaN,-2645.83,NaN,2645.83,NaN,0.0,Travel Bill,,,
5713,None,- None -,I09118002290110,BL-DK0408924,,Bill,3/30/2020,Mar-20,Net 15,4/29/2020,...,NaN,-3417.85,NaN,3417.85,NaN,0.0,Travel Bill,,,
5714,None,- None -,I09118002356352,BL-DK0408926,,Bill,3/30/2020,Mar-20,Due on receipt,4/1/2020,...,NaN,-503.23,NaN,503.23,NaN,0.0,Travel Bill,,,
5715,None,- None -,I09118002373362,BL-DK0408928,,Bill,3/30/2020,Mar-20,Due on receipt,4/1/2020,...,NaN,-604.31,NaN,604.31,NaN,0.0,Travel Bill,,,
5948,None,- None -,XXXXXXXXXXX3103- V-Pay,BC-DK0126114,,Bill Credit,3/31/2020,Mar-20,- None -,NaN,...,-75177.78,75177.78,NaN,NaN,NaN,0.0,Travel Bill,,,

In [53]:
vat.pivot_table(index='Comments', values=['Sum of Accounts Payable', 'Sum of Expense', 'Sum of VAT'], aggfunc='sum')

,Sum of Accounts Payable,Sum of Expense,Sum of VAT
Comments,,,
IC Invoice - EU Sales/IC Invoice - Outside EU,-99916.94,0.00,0.00
IC reverse charge EU/Outside,-284677.21,284677.21,71169.33
Intercompany no IC invoice,-2912837.13,315771.61,0.00
JE-transactions no vat,6258978.95,6328706.48,0.00
Linked invoice,-2518424.38,0.00,0.00
Neo travel expense - no vat,-298124.27,34981.40,0.00
Procurement-Denmark 0% VAT,-68359.28,68359.28,0.00
Procurement-EU/Outside Reverse charge,-1022024.24,1022024.24,0.00
Travel Bill,-4507503.91,4669.92,0.00
VAT,-2779260.99,311490.52,528734.99

In [47]:
# excel_file = pd.ExcelWriter("Darko VAT1.xlsx")

# vat.to_excel(excel_file, sheet_name = "vat", index = False)

# excel_file.save()