In [1]:
import pandas as pd
import numpy as np

In [2]:
vat = pd.read_csv("Purchase_register_aug_2020.csv")
vat.head(3)

,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,Vendor Category,...,Maximum of Coupa Tax Code,Maximum of External System Tax Code,Maximum of Tax Code (Consolidated),FOP Type,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT
0,- None -,31298815,BL-DK0409713,,Bill,11/6/2019,Aug-20,Due on receipt,11/6/2019,Coupa,...,NaN,NaN,DK-Z,- None -,NaN,-2480.0,NaN,NaN,2480.0,0.0
1,- None -,31307391,BL-DK0409710,,Bill,11/30/2019,Aug-20,Due on receipt,11/30/2019,Coupa,...,NaN,NaN,DK-Z,- None -,NaN,-135.0,NaN,NaN,135.0,0.0
2,- None -,31315780,BL-DK0409711,,Bill,12/31/2019,Aug-20,Due on receipt,12/31/2019,Coupa,...,NaN,NaN,DK-Z,- None -,NaN,-135.0,NaN,NaN,135.0,0.0

In [3]:
vat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3814 entries, 0 to 3813
Data columns (total 40 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   External ID                          3814 non-null   object
 1   Document Number                      3813 non-null   object
 2   Transaction Number                   3813 non-null   object
 3   Maximum of Linked Invoice            3813 non-null   object
 4   Type                                 3813 non-null   object
 5   Date                                 3813 non-null   object
 6   Period                               3813 non-null   object
 7   Terms                                3813 non-null   object
 8   Maximum of Due Date/Receive By       147 non-null    object
 9   Vendor Category                      3813 non-null   object
 10  Vendor Name                          3813 non-null   object
 11  Vendor Number                        0 non-null      float64
 12  Company Name                         3813 non-null   object
 13  Vendor VAT Registration Number       3813 non-null   object
 14  Vendor Billing Address               3813 non-null   object
 15  Vendor Billing Country               3813 non-null   object
 16  Bill to City                         3813 non-null   object
 17  Bill to State                        3813 non-null   object
 18  Bill to Country                      3813 non-null   object
 19  Bill to Zip                          3813 non-null   object
 20  Source System                        3813 non-null   object
 21  Source System Identifier             3813 non-null   object
 22  City                                 3813 non-null   object
 23  State/Province                       3813 non-null   object
 24  Country                              3813 non-null   object
 25  Zip                                  3813 non-null   object
 26  Currency                             3813 non-null   object
 27  Memo (Main)                          3813 non-null   object
 28  Maximum of GMAX Tax Code             0 non-null      float64
 29  Maximum of NetSuite Tax Item         2504 non-null   object
 30  Maximum of Coupa Tax Code            0 non-null      float64
 31  Maximum of External System Tax Code  0 non-null      float64
 32  Maximum of Tax Code (Consolidated)   2504 non-null   object
 33  FOP Type                             3813 non-null   object
 34  Sum of Asset                         2898 non-null   float64
 35  Sum of Accounts Payable              256 non-null    float64
 36  Sum of Other Liabilities             2577 non-null   float64
 37  Sum of Income                        2958 non-null   float64
 38  Sum of Expense                       253 non-null    float64
 39  Sum of VAT                           231 non-null    float64
dtypes: float64(10), object(30)
memory usage: 1.2+ MB

In [4]:
mask1 = vat[vat["External ID"].str.contains("clearing")].index
mask2 = vat[vat["External ID"].str.contains("Cross")].index
mask3 = vat[vat["Type"] == "Currency Revaluation"].index

In [5]:
mask2

Int64Index([3248, 3730, 3765, 3766, 3767, 3768, 3769, 3770], dtype='int64')

In [6]:
mask3

Int64Index([  28,   29,   30,   31,   44,   45,   46,   47,   48,   49,   50,
              51,   52,   53,   54,   55,   56,   57,   58,   59,   60,   61,
              62,   63,   64,   65,   66,  716,  717,  718,  719, 1603, 1604,
            1605, 1606, 1773, 1774, 1775, 1776, 1952, 1953, 1954, 1955, 1956,
            1957, 2274, 2275, 2276, 2277, 2482, 2483, 3083, 3084, 3230, 3231,
            3476, 3477, 3478, 3479, 3480],
           dtype='int64')

In [7]:
vat.drop(mask1, inplace=True)

In [8]:
vat.drop(mask2, inplace=True)

In [9]:
vat.drop(mask3, inplace=True)

In [10]:
mask1

Int64Index([3775], dtype='int64')

In [11]:
3774 in vat.index

True

In [12]:
vat.index

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            3804, 3805, 3806, 3807, 3808, 3809, 3810, 3811, 3812, 3813],
           dtype='int64', length=3745)

In [13]:
vat.tail(3)

,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,Vendor Category,...,Maximum of Coupa Tax Code,Maximum of External System Tax Code,Maximum of Tax Code (Consolidated),FOP Type,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT
3811,GBTICJE-IDENTIFIERH-ID2305279,JE-NL1279455,TJE-NL0169379,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,NaN,NaN,DK-S : DK-ESSP,- None -,3077.97,NaN,769.49,NaN,-3077.97,-769.49
3812,GBTICJE-IDENTIFIERH-ID2305297,JE-NL1279473,TJE-NL0169397,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,NaN,NaN,DK-S : DK-ESSP,- None -,2064.09,NaN,516.02,NaN,-2064.09,-516.02
3813,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1711374.33,-4080201.64,-3118953.66,-4242509.89,9730290.86,0.00

In [14]:
vat.drop(index=3813, inplace=True)

In [15]:
vat.tail(3)

,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,Vendor Category,...,Maximum of Coupa Tax Code,Maximum of External System Tax Code,Maximum of Tax Code (Consolidated),FOP Type,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT
3810,GBTICJE-IDENTIFIERB-ID2304896,JE-NL1279405,TJE-NL0169329,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,NaN,NaN,DK-S : DK-ESSP,- None -,NaN,-1677.03,-419.26,NaN,1677.03,419.26
3811,GBTICJE-IDENTIFIERH-ID2305279,JE-NL1279455,TJE-NL0169379,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,NaN,NaN,DK-S : DK-ESSP,- None -,3077.97,NaN,769.49,NaN,-3077.97,-769.49
3812,GBTICJE-IDENTIFIERH-ID2305297,JE-NL1279473,TJE-NL0169397,,Journal,8/31/2020,Aug-20,- None -,NaN,- None -,...,NaN,NaN,DK-S : DK-ESSP,- None -,2064.09,NaN,516.02,NaN,-2064.09,-516.02

In [16]:
vat[["Sum of Asset","Sum of Accounts Payable","Sum of Other Liabilities","Sum of Income","Sum of Expense","Sum of VAT"]].sum(axis= "rows")

Sum of Asset                1475216.00
Sum of Accounts Payable    -3988692.36
Sum of Other Liabilities   -3343542.97
Sum of Income              -4009961.42
Sum of Expense              9699017.10
Sum of VAT                   167963.65
dtype: float64

In [17]:
#Summerize the last row
#vat.loc["Totals"] = pd.Series(vat[["Sum of Asset","Sum of Accounts Payable","Sum of Other Liabilities","Sum of Income","Sum of Expense","Sum of VAT"]].sum(), index = ["Sum of Asset","Sum of Accounts Payable","Sum of Other Liabilities","Sum of Income","Sum of Expense","Sum of VAT"])

In [18]:
#vat.drop(index='Totals', inplace=True)

In [19]:
vat['Sum of VAT'].fillna(0, inplace=True)

In [20]:
def vat_amount(row):
    
    vat = row[39]
    
    if vat >0:
        return 'VAT'
    elif vat <0:
        return 'VAT'
    else:
        return 'Transactions 0DKK'

vat['Comments'] = vat.apply(vat_amount, axis='columns')

In [21]:
vat.head(3)

,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,Vendor Category,...,Maximum of External System Tax Code,Maximum of Tax Code (Consolidated),FOP Type,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments
0,- None -,31298815,BL-DK0409713,,Bill,11/6/2019,Aug-20,Due on receipt,11/6/2019,Coupa,...,NaN,DK-Z,- None -,NaN,-2480.0,NaN,NaN,2480.0,0.0,Transactions 0DKK
1,- None -,31307391,BL-DK0409710,,Bill,11/30/2019,Aug-20,Due on receipt,11/30/2019,Coupa,...,NaN,DK-Z,- None -,NaN,-135.0,NaN,NaN,135.0,0.0,Transactions 0DKK
2,- None -,31315780,BL-DK0409711,,Bill,12/31/2019,Aug-20,Due on receipt,12/31/2019,Coupa,...,NaN,DK-Z,- None -,NaN,-135.0,NaN,NaN,135.0,0.0,Transactions 0DKK

In [22]:
vat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3744 entries, 0 to 3812
Data columns (total 41 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   External ID                          3744 non-null   object
 1   Document Number                      3744 non-null   object
 2   Transaction Number                   3744 non-null   object
 3   Maximum of Linked Invoice            3744 non-null   object
 4   Type                                 3744 non-null   object
 5   Date                                 3744 non-null   object
 6   Period                               3744 non-null   object
 7   Terms                                3744 non-null   object
 8   Maximum of Due Date/Receive By       147 non-null    object
 9   Vendor Category                      3744 non-null   object
 10  Vendor Name                          3744 non-null   object
 11  Vendor Number                        0 non-null      float64
 12  Company Name                         3744 non-null   object
 13  Vendor VAT Registration Number       3744 non-null   object
 14  Vendor Billing Address               3744 non-null   object
 15  Vendor Billing Country               3744 non-null   object
 16  Bill to City                         3744 non-null   object
 17  Bill to State                        3744 non-null   object
 18  Bill to Country                      3744 non-null   object
 19  Bill to Zip                          3744 non-null   object
 20  Source System                        3744 non-null   object
 21  Source System Identifier             3744 non-null   object
 22  City                                 3744 non-null   object
 23  State/Province                       3744 non-null   object
 24  Country                              3744 non-null   object
 25  Zip                                  3744 non-null   object
 26  Currency                             3744 non-null   object
 27  Memo (Main)                          3744 non-null   object
 28  Maximum of GMAX Tax Code             0 non-null      float64
 29  Maximum of NetSuite Tax Item         2504 non-null   object
 30  Maximum of Coupa Tax Code            0 non-null      float64
 31  Maximum of External System Tax Code  0 non-null      float64
 32  Maximum of Tax Code (Consolidated)   2504 non-null   object
 33  FOP Type                             3744 non-null   object
 34  Sum of Asset                         2882 non-null   float64
 35  Sum of Accounts Payable              229 non-null    float64
 36  Sum of Other Liabilities             2566 non-null   float64
 37  Sum of Income                        2956 non-null   float64
 38  Sum of Expense                       219 non-null    float64
 39  Sum of VAT                           3744 non-null   float64
 40  Comments                             3744 non-null   object
dtypes: float64(10), object(31)
memory usage: 1.2+ MB

In [23]:
vat.insert(0, column = "External name", value = vat['External ID'].str.extract('([A-Z]\w{0,})', expand=True))

In [24]:
#vat['Comment 2']=''

In [25]:
vat['VAT reverse charge']=''

In [26]:
#vat['VAT No']=''

In [27]:
vat.columns

Index(['External name', 'External ID', 'Document Number', 'Transaction Number',
       'Maximum of Linked Invoice', 'Type', 'Date', 'Period', 'Terms',
       'Maximum of Due Date/Receive By', 'Vendor Category', 'Vendor Name',
       'Vendor Number', 'Company Name', 'Vendor VAT Registration Number',
       'Vendor Billing Address', 'Vendor Billing Country', 'Bill to City',
       'Bill to State', 'Bill to Country', 'Bill to Zip', 'Source System',
       'Source System Identifier', 'City', 'State/Province', 'Country', 'Zip',
       'Currency', 'Memo (Main)', 'Maximum of GMAX Tax Code',
       'Maximum of NetSuite Tax Item', 'Maximum of Coupa Tax Code',
       'Maximum of External System Tax Code',
       'Maximum of Tax Code (Consolidated)', 'FOP Type', 'Sum of Asset',
       'Sum of Accounts Payable', 'Sum of Other Liabilities', 'Sum of Income',
       'Sum of Expense', 'Sum of VAT', 'Comments', 'VAT reverse charge'],
      dtype='object')

In [28]:
 vat.loc[((vat['Sum of VAT'].notnull()) | (vat['Sum of VAT'] != 0)) &
        (vat['Comments'] == "VAT") &
        (vat['External name'] == 'GBTICJE'), "Comments"] = 'IC reverse charge EU/Outside'
vat[vat["Comments"] == "IC reverse charge EU/Outside"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Maximum of Tax Code (Consolidated),FOP Type,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,VAT reverse charge
1766,GBTICJE,GBTICJE-IDENTIFIERB-ID2280561,JE-NL1276976,TJE-NL0166900,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-I,- None -,NaN,-65982.75,-16495.69,NaN,65982.75,16495.69,IC reverse charge EU/Outside,
1767,GBTICJE,GBTICJE-IDENTIFIERB-ID2280559,JE-NL1276978,TJE-NL0166902,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-I,- None -,NaN,-16006.67,-4001.67,NaN,16006.67,4001.67,IC reverse charge EU/Outside,
1768,GBTICJE,GBTICJE-IDENTIFIERB-ID2280748,JE-NL1276989,TJE-NL0166913,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-20497.25,-5124.31,NaN,20497.25,5124.31,IC reverse charge EU/Outside,
1769,GBTICJE,GBTICJE-IDENTIFIERB-ID2280749,JE-NL1276990,TJE-NL0166915,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-20497.25,-5124.31,NaN,20497.25,5124.31,IC reverse charge EU/Outside,
1770,GBTICJE,GBTICJE-IDENTIFIERB-ID2280755,JE-NL1276991,TJE-NL0166914,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-I,- None -,NaN,-20577.00,-5144.25,NaN,20577.00,5144.25,IC reverse charge EU/Outside,
3565,GBTICJE,GBTICJE-IDENTIFIERG-ID2295056,JE-DK0302539,TJE-DK0302539,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-7931.73,-1982.93,NaN,7931.73,1982.93,IC reverse charge EU/Outside,
3776,GBTICJE,GBTICJE-IDENTIFIERB-ID2291560,JE-NL1277451,TJE-NL0167375,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-I,- None -,NaN,-10459.31,-2614.83,NaN,10459.31,2614.83,IC reverse charge EU/Outside,
3777,GBTICJE,GBTICJE-IDENTIFIERB-ID2291557,JE-NL1277454,TJE-NL0167378,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-I,- None -,NaN,-12604.36,-3151.09,NaN,12604.36,3151.09,IC reverse charge EU/Outside,
3778,GBTICJE,GBTICJE-IDENTIFIERB-ID2291621,JE-NL1277512,TJE-NL0167436,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-I,- None -,NaN,-732.16,-183.04,NaN,732.16,183.04,IC reverse charge EU/Outside,
3779,GBTICJE,GBTICJE-IDENTIFIERB-ID2291622,JE-NL1277514,TJE-NL0167438,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-I,- None -,NaN,-882.31,-220.58,NaN,882.31,220.58,IC reverse charge EU/Outside,
3786,GBTICJE,GBTICJE-IDENTIFIERB-ID2294757,JE-NL1277948,TJE-NL0167872,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-6625.72,-1656.43,NaN,6625.72,1656.43,IC reverse charge EU/Outside,
3787,GBTICJE,GBTICJE-IDENTIFIERB-ID2299077,JE-NL1278631,TJE-NL0168555,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-3077.97,-769.49,NaN,3077.97,769.49,IC reverse charge EU/Outside,
3788,GBTICJE,GBTICJE-IDENTIFIERB-ID2299094,JE-NL1278648,TJE-NL0168572,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-2064.09,-516.02,NaN,2064.09,516.02,IC reverse charge EU/Outside,
3803,GBTICJE,GBTICJE-IDENTIFIERB-ID2301160,JE-NL1279027,TJE-NL0168951,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-1443.82,-360.96,NaN,1443.82,360.96,IC reverse charge EU/Outside,
3804,GBTICJE,GBTICJE-IDENTIFIERB-ID2301171,JE-NL1279032,TJE-NL0168956,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-504.52,-126.13,NaN,504.52,126.13,IC reverse charge EU/Outside,
3805,GBTICJE,GBTICJE-IDENTIFIERB-ID2301200,JE-NL1279065,TJE-NL0168989,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-33362.69,-8340.67,NaN,33362.69,8340.67,IC reverse charge EU/Outside,
3806,GBTICJE,GBTICJE-IDENTIFIERB-ID2301201,JE-NL1279066,TJE-NL0168990,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-17131.49,-4282.87,NaN,17131.49,4282.87,IC reverse charge EU/Outside,
3807,GBTICJE,GBTICJE-IDENTIFIERB-ID2301202,JE-NL1279068,TJE-NL0168992,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-3864.38,-966.10,NaN,3864.38,966.10,IC reverse charge EU/Outside,
3808,GBTICJE,GBTICJE-IDENTIFIERB-ID2304859,JE-NL1279367,TJE-NL0169291,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-13626.93,-3406.73,NaN,13626.93,3406.73,IC reverse charge EU/Outside,
3809,GBTICJE,GBTICJE-IDENTIFIERB-ID2304878,JE-NL1279388,TJE-NL0169312,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-2232.54,-558.14,NaN,2232.54,558.14,IC reverse charge EU/Outside,
3810,GBTICJE,GBTICJE-IDENTIFIERB-ID2304896,JE-NL1279405,TJE-NL0169329,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-1677.03,-419.26,NaN,1677.03,419.26,IC reverse charge EU/Outside,
3811,GBTICJE,GBTICJE-IDENTIFIERH-ID2305279,JE-NL1279455,TJE-NL0169379,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,3077.97,NaN,769.49,NaN,-3077.97,-769.49,IC reverse charge EU/Outside,
3812,GBTICJE,GBTICJE-IDENTIFIERH-ID2305297,JE-NL1279473,TJE-NL0169397,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,2064.09,NaN,516.02,NaN,-2064.09,-516.02,IC reverse charge EU/Outside,

In [29]:
 vat.loc[((vat['Sum of VAT'].notnull()) | (vat['Sum of VAT'] != 0)) &
        (vat['Comments'] == "IC reverse charge EU/Outside") &
        (vat['External name'] == 'GBTICJE'), "VAT reverse charge"] = 'Reverse charge booked automatically in Netsuite'
vat[vat["VAT reverse charge"] == "Reverse charge booked automatically in Netsuite"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Maximum of Tax Code (Consolidated),FOP Type,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,VAT reverse charge
1766,GBTICJE,GBTICJE-IDENTIFIERB-ID2280561,JE-NL1276976,TJE-NL0166900,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-I,- None -,NaN,-65982.75,-16495.69,NaN,65982.75,16495.69,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
1767,GBTICJE,GBTICJE-IDENTIFIERB-ID2280559,JE-NL1276978,TJE-NL0166902,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-I,- None -,NaN,-16006.67,-4001.67,NaN,16006.67,4001.67,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
1768,GBTICJE,GBTICJE-IDENTIFIERB-ID2280748,JE-NL1276989,TJE-NL0166913,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-20497.25,-5124.31,NaN,20497.25,5124.31,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
1769,GBTICJE,GBTICJE-IDENTIFIERB-ID2280749,JE-NL1276990,TJE-NL0166915,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-20497.25,-5124.31,NaN,20497.25,5124.31,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
1770,GBTICJE,GBTICJE-IDENTIFIERB-ID2280755,JE-NL1276991,TJE-NL0166914,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-I,- None -,NaN,-20577.00,-5144.25,NaN,20577.00,5144.25,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3565,GBTICJE,GBTICJE-IDENTIFIERG-ID2295056,JE-DK0302539,TJE-DK0302539,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-7931.73,-1982.93,NaN,7931.73,1982.93,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3776,GBTICJE,GBTICJE-IDENTIFIERB-ID2291560,JE-NL1277451,TJE-NL0167375,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-I,- None -,NaN,-10459.31,-2614.83,NaN,10459.31,2614.83,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3777,GBTICJE,GBTICJE-IDENTIFIERB-ID2291557,JE-NL1277454,TJE-NL0167378,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-I,- None -,NaN,-12604.36,-3151.09,NaN,12604.36,3151.09,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3778,GBTICJE,GBTICJE-IDENTIFIERB-ID2291621,JE-NL1277512,TJE-NL0167436,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-I,- None -,NaN,-732.16,-183.04,NaN,732.16,183.04,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3779,GBTICJE,GBTICJE-IDENTIFIERB-ID2291622,JE-NL1277514,TJE-NL0167438,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-I,- None -,NaN,-882.31,-220.58,NaN,882.31,220.58,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3786,GBTICJE,GBTICJE-IDENTIFIERB-ID2294757,JE-NL1277948,TJE-NL0167872,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-6625.72,-1656.43,NaN,6625.72,1656.43,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3787,GBTICJE,GBTICJE-IDENTIFIERB-ID2299077,JE-NL1278631,TJE-NL0168555,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-3077.97,-769.49,NaN,3077.97,769.49,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3788,GBTICJE,GBTICJE-IDENTIFIERB-ID2299094,JE-NL1278648,TJE-NL0168572,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-2064.09,-516.02,NaN,2064.09,516.02,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3803,GBTICJE,GBTICJE-IDENTIFIERB-ID2301160,JE-NL1279027,TJE-NL0168951,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-1443.82,-360.96,NaN,1443.82,360.96,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3804,GBTICJE,GBTICJE-IDENTIFIERB-ID2301171,JE-NL1279032,TJE-NL0168956,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-504.52,-126.13,NaN,504.52,126.13,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3805,GBTICJE,GBTICJE-IDENTIFIERB-ID2301200,JE-NL1279065,TJE-NL0168989,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-33362.69,-8340.67,NaN,33362.69,8340.67,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3806,GBTICJE,GBTICJE-IDENTIFIERB-ID2301201,JE-NL1279066,TJE-NL0168990,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-17131.49,-4282.87,NaN,17131.49,4282.87,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3807,GBTICJE,GBTICJE-IDENTIFIERB-ID2301202,JE-NL1279068,TJE-NL0168992,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-3864.38,-966.10,NaN,3864.38,966.10,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3808,GBTICJE,GBTICJE-IDENTIFIERB-ID2304859,JE-NL1279367,TJE-NL0169291,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-13626.93,-3406.73,NaN,13626.93,3406.73,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3809,GBTICJE,GBTICJE-IDENTIFIERB-ID2304878,JE-NL1279388,TJE-NL0169312,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-2232.54,-558.14,NaN,2232.54,558.14,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3810,GBTICJE,GBTICJE-IDENTIFIERB-ID2304896,JE-NL1279405,TJE-NL0169329,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-1677.03,-419.26,NaN,1677.03,419.26,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3811,GBTICJE,GBTICJE-IDENTIFIERH-ID2305279,JE-NL1279455,TJE-NL0169379,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,3077.97,NaN,769.49,NaN,-3077.97,-769.49,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3812,GBTICJE,GBTICJE-IDENTIFIERH-ID2305297,JE-NL1279473,TJE-NL0169397,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,2064.09,NaN,516.02,NaN,-2064.09,-516.02,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite

In [30]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == "Transactions 0DKK") &
        (vat['Source System'].isin(['Procurement']) &
        (vat['Bill to Country'].isin(['Denmark']))), 'Comments'] = 'Procurement-Denmark 0% VAT'
vat[vat["Comments"] == "Procurement-Denmark 0% VAT"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Maximum of Tax Code (Consolidated),FOP Type,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,VAT reverse charge
0,None,- None -,31298815,BL-DK0409713,,Bill,11/6/2019,Aug-20,Due on receipt,11/6/2019,...,DK-Z,- None -,NaN,-2480.00,NaN,NaN,2480.00,0.0,Procurement-Denmark 0% VAT,
1,None,- None -,31307391,BL-DK0409710,,Bill,11/30/2019,Aug-20,Due on receipt,11/30/2019,...,DK-Z,- None -,NaN,-135.00,NaN,NaN,135.00,0.0,Procurement-Denmark 0% VAT,
2,None,- None -,31315780,BL-DK0409711,,Bill,12/31/2019,Aug-20,Due on receipt,12/31/2019,...,DK-Z,- None -,NaN,-135.00,NaN,NaN,135.00,0.0,Procurement-Denmark 0% VAT,
4,None,- None -,31331755,BL-DK0409712,,Bill,2/29/2020,Aug-20,Due on receipt,2/29/2020,...,DK-Z,- None -,NaN,-90.00,NaN,NaN,90.00,0.0,Procurement-Denmark 0% VAT,
1778,None,- None -,4376945,BL-DK0409816,,Bill,8/18/2020,Aug-20,Net 14,9/1/2020,...,DK-Z,- None -,NaN,-2882.10,NaN,NaN,2882.10,0.0,Procurement-Denmark 0% VAT,
1780,None,- None -,4376947,BL-DK0409818,,Bill,8/18/2020,Aug-20,Net 14,9/1/2020,...,DK-Z,- None -,NaN,-3461.16,NaN,NaN,3461.16,0.0,Procurement-Denmark 0% VAT,
2129,None,- None -,8037338,BL-DK0409844,,Bill,8/20/2020,Aug-20,Net 15,9/4/2020,...,DK-Z,- None -,NaN,-22851.25,NaN,NaN,22851.25,0.0,Procurement-Denmark 0% VAT,

In [31]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == "Transactions 0DKK") &
        (vat['Source System'].isin(['Procurement']) &
        (~vat['Bill to Country'].isin(['Denmark']))), 'Comments'] = 'Procurement-EU/Outside Reverse charge'
vat[vat["Comments"] == "Procurement-EU/Outside Reverse charge"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Maximum of Tax Code (Consolidated),FOP Type,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,VAT reverse charge
24,None,- None -,6710014665,BL-DK0409841,,Bill,7/24/2020,Aug-20,Due on receipt,7/24/2020,...,DK-Z,- None -,NaN,-7950.99,NaN,NaN,7950.99,0.0,Procurement-EU/Outside Reverse charge,
33,None,- None -,508812,BL-DK0409780,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,DK-Z : DK-EZ,- None -,NaN,-17166.21,NaN,NaN,17166.21,0.0,Procurement-EU/Outside Reverse charge,
34,None,- None -,508813,BL-DK0409779,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,DK-Z,- None -,NaN,-7369.55,NaN,NaN,7369.55,0.0,Procurement-EU/Outside Reverse charge,
35,None,- None -,508814,BL-DK0409776,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,DK-Z,- None -,NaN,-9877.43,NaN,NaN,9877.43,0.0,Procurement-EU/Outside Reverse charge,
36,None,- None -,508815,BL-DK0409775,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,DK-Z,- None -,NaN,-1902.68,NaN,NaN,1902.68,0.0,Procurement-EU/Outside Reverse charge,
37,None,- None -,508816,BL-DK0409774,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,DK-Z,- None -,NaN,-61.41,NaN,NaN,61.41,0.0,Procurement-EU/Outside Reverse charge,
38,None,- None -,508817,BL-DK0409778,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,DK-Z,- None -,NaN,-20896.77,NaN,NaN,20896.77,0.0,Procurement-EU/Outside Reverse charge,
39,None,- None -,508818,BL-DK0409777,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,DK-Z,- None -,NaN,-33563.31,NaN,NaN,33563.31,0.0,Procurement-EU/Outside Reverse charge,
42,None,- None -,202008001,BL-DK0409709,,Bill,8/1/2020,Aug-20,NET 8,8/1/2020,...,DK-Z,- None -,NaN,-323741.82,NaN,NaN,323741.82,0.0,Procurement-EU/Outside Reverse charge,
43,None,- None -,202008002,BL-DK0409708,,Bill,8/1/2020,Aug-20,NET 8,8/1/2020,...,DK-Z,- None -,NaN,-64748.36,NaN,NaN,64748.36,0.0,Procurement-EU/Outside Reverse charge,
122,None,- None -,4727,BL-DK0409691,,Bill,8/3/2020,Aug-20,Net 30,9/2/2020,...,DK-Z,- None -,NaN,-5786.41,NaN,NaN,5786.41,0.0,Procurement-EU/Outside Reverse charge,

In [32]:
## DOES NOT WORK IN THIS CASE

# def proc(row):
    
#     check =row[41]
    
#     if check == 'Procurement-EU/Outside Reverse charge':
#         return vat["Sum of Accounts Payable"] * 0.25
#     else:
#         return ''

    
# vat["VAT reverse charge"] = vat["Comments"].apply(proc)

In [33]:
## DOES NOT WORK IN THIS CASE

# def applyFunc(s):
#     if s == "Procurement-EU/Outside Reverse charge":
#         return vat["Sum of Accounts Payable"] * 0.25
    

# vat["VAT reverse charge"] = vat["Comments"].apply(applyFunc)

In [34]:
#This Method worksin this case
vat['VAT reverse charge'] = np.where(vat['Comments'] == 'Procurement-EU/Outside Reverse charge',vat['Sum of Accounts Payable'] * 0.25, vat['VAT reverse charge'])

In [35]:
#tip from internet
#df.loc[df['product']=='a', ['market_penetration_rate', 'success_rate']] * 100

In [36]:
#tip from internet
# df.apply(lambda row: row[['success_rate', 'market_penetration_rate']]*100 if row['product'] == 'a' 
#      else row[['success_rate', 'market_penetration_rate']], axis=1)

In [37]:
vat[vat["Comments"] == "Procurement-EU/Outside Reverse charge"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Maximum of Tax Code (Consolidated),FOP Type,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,VAT reverse charge
24,None,- None -,6710014665,BL-DK0409841,,Bill,7/24/2020,Aug-20,Due on receipt,7/24/2020,...,DK-Z,- None -,NaN,-7950.99,NaN,NaN,7950.99,0.0,Procurement-EU/Outside Reverse charge,-1987.75
33,None,- None -,508812,BL-DK0409780,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,DK-Z : DK-EZ,- None -,NaN,-17166.21,NaN,NaN,17166.21,0.0,Procurement-EU/Outside Reverse charge,-4291.55
34,None,- None -,508813,BL-DK0409779,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,DK-Z,- None -,NaN,-7369.55,NaN,NaN,7369.55,0.0,Procurement-EU/Outside Reverse charge,-1842.39
35,None,- None -,508814,BL-DK0409776,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,DK-Z,- None -,NaN,-9877.43,NaN,NaN,9877.43,0.0,Procurement-EU/Outside Reverse charge,-2469.36
36,None,- None -,508815,BL-DK0409775,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,DK-Z,- None -,NaN,-1902.68,NaN,NaN,1902.68,0.0,Procurement-EU/Outside Reverse charge,-475.67
37,None,- None -,508816,BL-DK0409774,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,DK-Z,- None -,NaN,-61.41,NaN,NaN,61.41,0.0,Procurement-EU/Outside Reverse charge,-15.3525
38,None,- None -,508817,BL-DK0409778,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,DK-Z,- None -,NaN,-20896.77,NaN,NaN,20896.77,0.0,Procurement-EU/Outside Reverse charge,-5224.19
39,None,- None -,508818,BL-DK0409777,,Bill,7/31/2020,Aug-20,Due on receipt,7/31/2020,...,DK-Z,- None -,NaN,-33563.31,NaN,NaN,33563.31,0.0,Procurement-EU/Outside Reverse charge,-8390.83
42,None,- None -,202008001,BL-DK0409709,,Bill,8/1/2020,Aug-20,NET 8,8/1/2020,...,DK-Z,- None -,NaN,-323741.82,NaN,NaN,323741.82,0.0,Procurement-EU/Outside Reverse charge,-80935.5
43,None,- None -,202008002,BL-DK0409708,,Bill,8/1/2020,Aug-20,NET 8,8/1/2020,...,DK-Z,- None -,NaN,-64748.36,NaN,NaN,64748.36,0.0,Procurement-EU/Outside Reverse charge,-16187.1
122,None,- None -,4727,BL-DK0409691,,Bill,8/3/2020,Aug-20,Net 30,9/2/2020,...,DK-Z,- None -,NaN,-5786.41,NaN,NaN,5786.41,0.0,Procurement-EU/Outside Reverse charge,-1446.6

In [38]:
vat.tail(3)

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Maximum of Tax Code (Consolidated),FOP Type,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,VAT reverse charge
3810,GBTICJE,GBTICJE-IDENTIFIERB-ID2304896,JE-NL1279405,TJE-NL0169329,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,NaN,-1677.03,-419.26,NaN,1677.03,419.26,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3811,GBTICJE,GBTICJE-IDENTIFIERH-ID2305279,JE-NL1279455,TJE-NL0169379,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,3077.97,NaN,769.49,NaN,-3077.97,-769.49,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite
3812,GBTICJE,GBTICJE-IDENTIFIERH-ID2305297,JE-NL1279473,TJE-NL0169397,,Journal,8/31/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSP,- None -,2064.09,NaN,516.02,NaN,-2064.09,-516.02,IC reverse charge EU/Outside,Reverse charge booked automatically in Netsuite

In [39]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == "Transactions 0DKK") &
        (vat['Source System'].isin(['NEO'])), 'Comments'] = 'Neo travel expense - no vat'
vat[vat["Comments"] == "Neo travel expense - no vat"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Maximum of Tax Code (Consolidated),FOP Type,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,VAT reverse charge
1058,KDS_Exp_VB_371144,KDS_Exp_VB_371144,371144,BL-DK0409765,,Bill,8/11/2020,Aug-20,Due on receipt,8/11/2020,...,DK-Z,- None -,NaN,-36.25,NaN,NaN,36.25,0.0,Neo travel expense - no vat,
1290,KDS_Exp_VB_371602,KDS_Exp_VB_371602,371602,BL-DK0409771,,Bill,8/13/2020,Aug-20,Due on receipt,8/13/2020,...,DK-Z,- None -,NaN,-649.33,NaN,NaN,649.33,0.0,Neo travel expense - no vat,
2279,KDS_Exp_JE_372176__OOP,KDS_Exp_JE_372176__OOP,JE-DK0301047,TJE-DK0301047,,Journal,8/21/2020,Aug-20,- None -,NaN,...,NaN,- None -,NaN,NaN,-300.00,NaN,300.00,0.0,Neo travel expense - no vat,
2626,KDS_Exp_JE_372557__OOP,KDS_Exp_JE_372557__OOP,JE-DK0301428,TJE-DK0301428,,Journal,8/25/2020,Aug-20,- None -,NaN,...,NaN,- None -,NaN,NaN,-360.00,NaN,360.00,0.0,Neo travel expense - no vat,
2627,KDS_Exp_JE_372583__OOP,KDS_Exp_JE_372583__OOP,JE-DK0301429,TJE-DK0301429,,Journal,8/25/2020,Aug-20,- None -,NaN,...,NaN,- None -,NaN,NaN,-49.69,NaN,49.69,0.0,Neo travel expense - no vat,
2862,KDS_Exp_JE_372743__OOP,KDS_Exp_JE_372743__OOP,JE-DK0301535,TJE-DK0301535,,Journal,8/26/2020,Aug-20,- None -,NaN,...,NaN,- None -,NaN,NaN,-900.00,NaN,900.00,0.0,Neo travel expense - no vat,
3408,KDS_Exp_VB_371755,KDS_Exp_VB_371755,371755,BL-DK0409845,,Bill,8/29/2020,Aug-20,Due on receipt,8/29/2020,...,DK-Z,- None -,NaN,-627.74,NaN,NaN,627.74,0.0,Neo travel expense - no vat,

In [40]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == "Transactions 0DKK") &
        (vat['External name'] == 'GBTICJE') &
        (vat['Maximum of NetSuite Tax Item'].notnull()), 'Comments'] = 'IC Invoice - EU Sales/IC Invoice - Outside EU'
vat[vat["Comments"] == "IC Invoice - EU Sales/IC Invoice - Outside EU"]
#'DK-S : DK-ESSS', 'DK-OS'

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Maximum of Tax Code (Consolidated),FOP Type,Sum of Asset,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,VAT reverse charge
1609,GBTICJE,GBTICJE-IDENTIFIERA-ID2280758,JE-DK0300630,TJE-DK0300630,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,2240.42,NaN,0.0,-2240.42,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1610,GBTICJE,GBTICJE-IDENTIFIERA-ID2280759,JE-DK0300631,TJE-DK0300631,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-OS,- None -,809.04,NaN,0.0,-809.04,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1611,GBTICJE,GBTICJE-IDENTIFIERA-ID2280767,JE-DK0300632,TJE-DK0300632,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-OS,- None -,2707.17,NaN,0.0,-2707.17,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1612,GBTICJE,GBTICJE-IDENTIFIERA-ID2280760,JE-DK0300633,TJE-DK0300633,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,1991.48,NaN,0.0,-1991.48,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1613,GBTICJE,GBTICJE-IDENTIFIERA-ID2280761,JE-DK0300634,TJE-DK0300634,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,217.82,NaN,0.0,-217.82,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1614,GBTICJE,GBTICJE-IDENTIFIERA-ID2280763,JE-DK0300635,TJE-DK0300635,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-OS,- None -,403679.89,NaN,0.0,-403679.89,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1615,GBTICJE,GBTICJE-IDENTIFIERA-ID2280762,JE-DK0300636,TJE-DK0300636,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,116750.71,NaN,0.0,-116750.71,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1616,GBTICJE,GBTICJE-IDENTIFIERA-ID2280764,JE-DK0300637,TJE-DK0300637,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,6285.62,NaN,0.0,-6285.62,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1617,GBTICJE,GBTICJE-IDENTIFIERA-ID2280765,JE-DK0300638,TJE-DK0300638,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-OS,- None -,373.40,NaN,0.0,-373.40,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1618,GBTICJE,GBTICJE-IDENTIFIERA-ID2280766,JE-DK0300639,TJE-DK0300639,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,65283.31,NaN,0.0,-65283.31,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1619,GBTICJE,GBTICJE-IDENTIFIERA-ID2280769,JE-DK0300640,TJE-DK0300640,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-OS,- None -,11139.86,NaN,0.0,-11139.86,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1620,GBTICJE,GBTICJE-IDENTIFIERA-ID2280768,JE-DK0300641,TJE-DK0300641,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,3609.56,NaN,0.0,-3609.56,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1621,GBTICJE,GBTICJE-IDENTIFIERA-ID2280770,JE-DK0300642,TJE-DK0300642,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,11980.02,NaN,0.0,-11980.02,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1622,GBTICJE,GBTICJE-IDENTIFIERA-ID2280771,JE-DK0300643,TJE-DK0300643,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-OS,- None -,27040.61,NaN,0.0,-27040.61,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1623,GBTICJE,GBTICJE-IDENTIFIERA-ID2280772,JE-DK0300644,TJE-DK0300644,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,12602.36,NaN,0.0,-12602.36,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1624,GBTICJE,GBTICJE-IDENTIFIERA-ID2280773,JE-DK0300645,TJE-DK0300645,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,5943.33,NaN,0.0,-5943.33,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1625,GBTICJE,GBTICJE-IDENTIFIERA-ID2280774,JE-DK0300646,TJE-DK0300646,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-OS,- None -,9957.42,NaN,0.0,-9957.42,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1626,GBTICJE,GBTICJE-IDENTIFIERA-ID2280775,JE-DK0300647,TJE-DK0300647,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-OS,- None -,75085.14,NaN,0.0,-75085.14,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1627,GBTICJE,GBTICJE-IDENTIFIERA-ID2280777,JE-DK0300648,TJE-DK0300648,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,59028.81,NaN,0.0,-59028.81,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1628,GBTICJE,GBTICJE-IDENTIFIERA-ID2280778,JE-DK0300649,TJE-DK0300649,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,10486.40,NaN,0.0,-10486.40,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1629,GBTICJE,GBTICJE-IDENTIFIERA-ID2280779,JE-DK0300650,TJE-DK0300650,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,62.23,NaN,0.0,-62.23,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1630,GBTICJE,GBTICJE-IDENTIFIERA-ID2280781,JE-DK0300651,TJE-DK0300651,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,3018.34,NaN,0.0,-3018.34,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1631,GBTICJE,GBTICJE-IDENTIFIERA-ID2280776,JE-DK0300652,TJE-DK0300652,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,4947.59,NaN,0.0,-4947.59,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1632,GBTICJE,GBTICJE-IDENTIFIERA-ID2280782,JE-DK0300653,TJE-DK0300653,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,11980.02,NaN,0.0,-11980.02,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1633,GBTICJE,GBTICJE-IDENTIFIERA-ID2280784,JE-DK0300654,TJE-DK0300654,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,31210.28,NaN,0.0,-31210.28,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1634,GBTICJE,GBTICJE-IDENTIFIERA-ID2280785,JE-DK0300655,TJE-DK0300655,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-OS,- None -,1213.56,NaN,0.0,-1213.56,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1635,GBTICJE,GBTICJE-IDENTIFIERA-ID2280786,JE-DK0300656,TJE-DK0300656,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,1711.43,NaN,0.0,-1711.43,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1636,GBTICJE,GBTICJE-IDENTIFIERA-ID2280780,JE-DK0300657,TJE-DK0300657,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,528.99,NaN,0.0,-528.99,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1637,GBTICJE,GBTICJE-IDENTIFIERA-ID2280788,JE-DK0300658,TJE-DK0300658,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,560.10,NaN,0.0,-560.10,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1638,GBTICJE,GBTICJE-IDENTIFIERA-ID2280789,JE-DK0300659,TJE-DK0300659,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,53676.70,NaN,0.0,-53676.70,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1639,GBTICJE,GBTICJE-IDENTIFIERA-ID2280783,JE-DK0300660,TJE-DK0300660,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,62.23,NaN,0.0,-62.23,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1640,GBTICJE,GBTICJE-IDENTIFIERA-ID2280790,JE-DK0300661,TJE-DK0300661,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-OS,- None -,6472.32,NaN,0.0,-6472.32,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1641,GBTICJE,GBTICJE-IDENTIFIERA-ID2280791,JE-DK0300662,TJE-DK0300662,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-OS,- None -,12789.06,NaN,0.0,-12789.06,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1642,GBTICJE,GBTICJE-IDENTIFIERA-ID2280792,JE-DK0300663,TJE-DK0300663,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,1618.08,NaN,0.0,-1618.08,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1643,GBTICJE,GBTICJE-IDENTIFIERA-ID2280793,JE-DK0300664,TJE-DK0300664,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,41198.81,NaN,0.0,-41198.81,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1644,GBTICJE,GBTICJE-IDENTIFIERA-ID2280794,JE-DK0300665,TJE-DK0300665,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,8526.04,NaN,0.0,-8526.04,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,
1645,GBTICJE,GBTICJE-IDENTIFIERA-ID2280787,JE-DK0300666,TJE-DK0300666,,Journal,8/17/2020,Aug-20,- None -,NaN,...,DK-S : DK-ESSS,- None -,2147.07,NaN,0.0,-2147.07,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,

In [41]:
##Method to convert excel files to Csv files - Use the file from Sales vat
#read_file = pd.read_excel (r'C:\Users\darko\Desktop\pandas\test_sales_march.xlsx')
#read_file.to_csv (r'C:\Users\darko\Desktop\pandas\test_sales_march2.csv', index = None, header=True)

In [42]:
csv=pd.read_csv('test_sales_july2.csv')

In [43]:
#Douplicates are created when matching both csv files, same principle as match in excel
vat = vat.merge(csv[['Sum of Income','Comment 2', 'VAT No', 'Comment 3']].drop_duplicates(), how='left', on='Sum of Income', suffixes=['', ' 3'])

In [44]:
vat[vat['Comments'] == 'IC Invoice - EU Sales/IC Invoice - Outside EU' ]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,VAT reverse charge,Comment 2,VAT No,Comment 3
1574,GBTICJE,GBTICJE-IDENTIFIERA-ID2280758,JE-DK0300630,TJE-DK0300630,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-2240.42,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
1575,GBTICJE,GBTICJE-IDENTIFIERA-ID2280759,JE-DK0300631,TJE-DK0300631,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-809.04,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,FI02152075,IC Invoice - EU Sales
1576,GBTICJE,GBTICJE-IDENTIFIERA-ID2280767,JE-DK0300632,TJE-DK0300632,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-2707.17,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Carlsberg c-out from DK,FI02152075,IC Invoice - EU Sales
1577,GBTICJE,GBTICJE-IDENTIFIERA-ID2280760,JE-DK0300633,TJE-DK0300633,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-1991.48,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,FR 15 304 475 338,IC Invoice - EU Sales
1578,GBTICJE,GBTICJE-IDENTIFIERA-ID2280761,JE-DK0300634,TJE-DK0300634,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-217.82,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,DE254337470,IC Invoice - EU Sales
1579,GBTICJE,GBTICJE-IDENTIFIERA-ID2280763,JE-DK0300635,TJE-DK0300635,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-403679.89,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,NO959209502,IC Invoice - Outside EU
1580,GBTICJE,GBTICJE-IDENTIFIERA-ID2280762,JE-DK0300636,TJE-DK0300636,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-116750.71,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,NL853361757B01,IC Invoice - EU Sales
1581,GBTICJE,GBTICJE-IDENTIFIERA-ID2280764,JE-DK0300637,TJE-DK0300637,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-6285.62,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1582,GBTICJE,GBTICJE-IDENTIFIERA-ID2280765,JE-DK0300638,TJE-DK0300638,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-373.40,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,CHE-300.737.496 MWST,IC Invoice - Outside EU
1583,GBTICJE,GBTICJE-IDENTIFIERA-ID2280766,JE-DK0300639,TJE-DK0300639,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-65283.31,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,GB 177248479,IC Invoice - EU Sales
1584,GBTICJE,GBTICJE-IDENTIFIERA-ID2280769,JE-DK0300640,TJE-DK0300640,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-11139.86,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Carlsberg c-out from DK,NO959209502,IC Invoice - Outside EU
1585,GBTICJE,GBTICJE-IDENTIFIERA-ID2280768,JE-DK0300641,TJE-DK0300641,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-3609.56,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Carlsberg c-out from DK,DE254337470,IC Invoice - EU Sales
1586,GBTICJE,GBTICJE-IDENTIFIERA-ID2280770,JE-DK0300642,TJE-DK0300642,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-11980.02,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Carlsberg c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1587,GBTICJE,GBTICJE-IDENTIFIERA-ID2280771,JE-DK0300643,TJE-DK0300643,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-27040.61,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Carlsberg c-out from DK,CHE-300.737.496 MWST,IC Invoice - Outside EU
1588,GBTICJE,GBTICJE-IDENTIFIERA-ID2280772,JE-DK0300644,TJE-DK0300644,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-12602.36,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Carlsberg c-out from DK,GB 177248479,IC Invoice - EU Sales
1589,GBTICJE,GBTICJE-IDENTIFIERA-ID2280773,JE-DK0300645,TJE-DK0300645,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-5943.33,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Danske Bank c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
1590,GBTICJE,GBTICJE-IDENTIFIERA-ID2280774,JE-DK0300646,TJE-DK0300646,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-9957.42,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Danske Bank c-out from DK,FI02152075,IC Invoice - EU Sales
1591,GBTICJE,GBTICJE-IDENTIFIERA-ID2280775,JE-DK0300647,TJE-DK0300647,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-75085.14,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Danske Bank c-out from DK,NO959209502,IC Invoice - Outside EU
1592,GBTICJE,GBTICJE-IDENTIFIERA-ID2280777,JE-DK0300648,TJE-DK0300648,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-59028.81,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Danske Bank c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1593,GBTICJE,GBTICJE-IDENTIFIERA-ID2280778,JE-DK0300649,TJE-DK0300649,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-10486.40,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Danske Bank c-out from DK,GB 177248479,IC Invoice - EU Sales
1594,GBTICJE,GBTICJE-IDENTIFIERA-ID2280779,JE-DK0300650,TJE-DK0300650,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-62.23,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
1595,GBTICJE,GBTICJE-IDENTIFIERA-ID2280781,JE-DK0300651,TJE-DK0300651,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-3018.34,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,FR 15 304 475 338,IC Invoice - EU Sales
1596,GBTICJE,GBTICJE-IDENTIFIERA-ID2280776,JE-DK0300652,TJE-DK0300652,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-4947.59,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Danske Bank c-out from DK,PL 5252273929,IC Invoice - EU Sales
1597,GBTICJE,GBTICJE-IDENTIFIERA-ID2280782,JE-DK0300653,TJE-DK0300653,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-11980.02,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Carlsberg c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1598,GBTICJE,GBTICJE-IDENTIFIERA-ID2280784,JE-DK0300654,TJE-DK0300654,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-31210.28,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,NL853361757B01,IC Invoice - EU Sales
1599,GBTICJE,GBTICJE-IDENTIFIERA-ID2280785,JE-DK0300655,TJE-DK0300655,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-1213.56,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,NO959209502,IC Invoice - Outside EU
1600,GBTICJE,GBTICJE-IDENTIFIERA-ID2280786,JE-DK0300656,TJE-DK0300656,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-1711.43,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,PL 5252273929,IC Invoice - EU Sales
1601,GBTICJE,GBTICJE-IDENTIFIERA-ID2280780,JE-DK0300657,TJE-DK0300657,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-528.99,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,CZ 02525071,IC Invoice - EU Sales
1602,GBTICJE,GBTICJE-IDENTIFIERA-ID2280788,JE-DK0300658,TJE-DK0300658,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-560.10,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1603,GBTICJE,GBTICJE-IDENTIFIERA-ID2280789,JE-DK0300659,TJE-DK0300659,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-53676.70,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,GB 177248479,IC Invoice - EU Sales
1604,GBTICJE,GBTICJE-IDENTIFIERA-ID2280783,JE-DK0300660,TJE-DK0300660,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-62.23,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
1605,GBTICJE,GBTICJE-IDENTIFIERA-ID2280790,JE-DK0300661,TJE-DK0300661,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-6472.32,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Ramboll c-out from DK,FI02152075,IC Invoice - EU Sales
1606,GBTICJE,GBTICJE-IDENTIFIERA-ID2280791,JE-DK0300662,TJE-DK0300662,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-12789.06,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Ramboll c-out from DK,NO959209502,IC Invoice - Outside EU
1607,GBTICJE,GBTICJE-IDENTIFIERA-ID2280792,JE-DK0300663,TJE-DK0300663,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-1618.08,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Ramboll c-out from DK,DE254337470,IC Invoice - EU Sales
1608,GBTICJE,GBTICJE-IDENTIFIERA-ID2280793,JE-DK0300664,TJE-DK0300664,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-41198.81,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Ramboll c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1609,GBTICJE,GBTICJE-IDENTIFIERA-ID2280794,JE-DK0300665,TJE-DK0300665,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-8526.04,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Ramboll c-out from DK,GB 177248479,IC Invoice - EU Sales
1610,GBTICJE,GBTICJE-IDENTIFIERA-ID2280787,JE-DK0300666,TJE-DK0300666,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-2147.07,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,B85376630,IC Invoice - EU Sales

In [45]:
#Check manually if a new row is added!!!
#vat.at[1270, 'Comment 3']='IC Invoice - EU Sales/IC Invoice - Outside EU'

In [46]:
vat[vat['Comments'] == 'IC Invoice - EU Sales/IC Invoice - Outside EU' ]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,VAT reverse charge,Comment 2,VAT No,Comment 3
1574,GBTICJE,GBTICJE-IDENTIFIERA-ID2280758,JE-DK0300630,TJE-DK0300630,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-2240.42,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
1575,GBTICJE,GBTICJE-IDENTIFIERA-ID2280759,JE-DK0300631,TJE-DK0300631,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-809.04,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,FI02152075,IC Invoice - EU Sales
1576,GBTICJE,GBTICJE-IDENTIFIERA-ID2280767,JE-DK0300632,TJE-DK0300632,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-2707.17,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Carlsberg c-out from DK,FI02152075,IC Invoice - EU Sales
1577,GBTICJE,GBTICJE-IDENTIFIERA-ID2280760,JE-DK0300633,TJE-DK0300633,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-1991.48,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,FR 15 304 475 338,IC Invoice - EU Sales
1578,GBTICJE,GBTICJE-IDENTIFIERA-ID2280761,JE-DK0300634,TJE-DK0300634,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-217.82,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,DE254337470,IC Invoice - EU Sales
1579,GBTICJE,GBTICJE-IDENTIFIERA-ID2280763,JE-DK0300635,TJE-DK0300635,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-403679.89,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,NO959209502,IC Invoice - Outside EU
1580,GBTICJE,GBTICJE-IDENTIFIERA-ID2280762,JE-DK0300636,TJE-DK0300636,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-116750.71,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,NL853361757B01,IC Invoice - EU Sales
1581,GBTICJE,GBTICJE-IDENTIFIERA-ID2280764,JE-DK0300637,TJE-DK0300637,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-6285.62,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1582,GBTICJE,GBTICJE-IDENTIFIERA-ID2280765,JE-DK0300638,TJE-DK0300638,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-373.40,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,CHE-300.737.496 MWST,IC Invoice - Outside EU
1583,GBTICJE,GBTICJE-IDENTIFIERA-ID2280766,JE-DK0300639,TJE-DK0300639,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-65283.31,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,APMM c-out from DK,GB 177248479,IC Invoice - EU Sales
1584,GBTICJE,GBTICJE-IDENTIFIERA-ID2280769,JE-DK0300640,TJE-DK0300640,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-11139.86,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Carlsberg c-out from DK,NO959209502,IC Invoice - Outside EU
1585,GBTICJE,GBTICJE-IDENTIFIERA-ID2280768,JE-DK0300641,TJE-DK0300641,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-3609.56,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Carlsberg c-out from DK,DE254337470,IC Invoice - EU Sales
1586,GBTICJE,GBTICJE-IDENTIFIERA-ID2280770,JE-DK0300642,TJE-DK0300642,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-11980.02,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Carlsberg c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1587,GBTICJE,GBTICJE-IDENTIFIERA-ID2280771,JE-DK0300643,TJE-DK0300643,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-27040.61,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Carlsberg c-out from DK,CHE-300.737.496 MWST,IC Invoice - Outside EU
1588,GBTICJE,GBTICJE-IDENTIFIERA-ID2280772,JE-DK0300644,TJE-DK0300644,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-12602.36,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Carlsberg c-out from DK,GB 177248479,IC Invoice - EU Sales
1589,GBTICJE,GBTICJE-IDENTIFIERA-ID2280773,JE-DK0300645,TJE-DK0300645,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-5943.33,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Danske Bank c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
1590,GBTICJE,GBTICJE-IDENTIFIERA-ID2280774,JE-DK0300646,TJE-DK0300646,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-9957.42,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Danske Bank c-out from DK,FI02152075,IC Invoice - EU Sales
1591,GBTICJE,GBTICJE-IDENTIFIERA-ID2280775,JE-DK0300647,TJE-DK0300647,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-75085.14,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Danske Bank c-out from DK,NO959209502,IC Invoice - Outside EU
1592,GBTICJE,GBTICJE-IDENTIFIERA-ID2280777,JE-DK0300648,TJE-DK0300648,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-59028.81,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Danske Bank c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1593,GBTICJE,GBTICJE-IDENTIFIERA-ID2280778,JE-DK0300649,TJE-DK0300649,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-10486.40,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Danske Bank c-out from DK,GB 177248479,IC Invoice - EU Sales
1594,GBTICJE,GBTICJE-IDENTIFIERA-ID2280779,JE-DK0300650,TJE-DK0300650,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-62.23,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
1595,GBTICJE,GBTICJE-IDENTIFIERA-ID2280781,JE-DK0300651,TJE-DK0300651,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-3018.34,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,FR 15 304 475 338,IC Invoice - EU Sales
1596,GBTICJE,GBTICJE-IDENTIFIERA-ID2280776,JE-DK0300652,TJE-DK0300652,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-4947.59,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Danske Bank c-out from DK,PL 5252273929,IC Invoice - EU Sales
1597,GBTICJE,GBTICJE-IDENTIFIERA-ID2280782,JE-DK0300653,TJE-DK0300653,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-11980.02,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Carlsberg c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1598,GBTICJE,GBTICJE-IDENTIFIERA-ID2280784,JE-DK0300654,TJE-DK0300654,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-31210.28,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,NL853361757B01,IC Invoice - EU Sales
1599,GBTICJE,GBTICJE-IDENTIFIERA-ID2280785,JE-DK0300655,TJE-DK0300655,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-1213.56,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,NO959209502,IC Invoice - Outside EU
1600,GBTICJE,GBTICJE-IDENTIFIERA-ID2280786,JE-DK0300656,TJE-DK0300656,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-1711.43,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,PL 5252273929,IC Invoice - EU Sales
1601,GBTICJE,GBTICJE-IDENTIFIERA-ID2280780,JE-DK0300657,TJE-DK0300657,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-528.99,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,CZ 02525071,IC Invoice - EU Sales
1602,GBTICJE,GBTICJE-IDENTIFIERA-ID2280788,JE-DK0300658,TJE-DK0300658,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-560.10,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1603,GBTICJE,GBTICJE-IDENTIFIERA-ID2280789,JE-DK0300659,TJE-DK0300659,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-53676.70,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,GB 177248479,IC Invoice - EU Sales
1604,GBTICJE,GBTICJE-IDENTIFIERA-ID2280783,JE-DK0300660,TJE-DK0300660,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-62.23,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
1605,GBTICJE,GBTICJE-IDENTIFIERA-ID2280790,JE-DK0300661,TJE-DK0300661,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-6472.32,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Ramboll c-out from DK,FI02152075,IC Invoice - EU Sales
1606,GBTICJE,GBTICJE-IDENTIFIERA-ID2280791,JE-DK0300662,TJE-DK0300662,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-12789.06,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Ramboll c-out from DK,NO959209502,IC Invoice - Outside EU
1607,GBTICJE,GBTICJE-IDENTIFIERA-ID2280792,JE-DK0300663,TJE-DK0300663,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-1618.08,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Ramboll c-out from DK,DE254337470,IC Invoice - EU Sales
1608,GBTICJE,GBTICJE-IDENTIFIERA-ID2280793,JE-DK0300664,TJE-DK0300664,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-41198.81,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Ramboll c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1609,GBTICJE,GBTICJE-IDENTIFIERA-ID2280794,JE-DK0300665,TJE-DK0300665,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-8526.04,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,Ramboll c-out from DK,GB 177248479,IC Invoice - EU Sales
1610,GBTICJE,GBTICJE-IDENTIFIERA-ID2280787,JE-DK0300666,TJE-DK0300666,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-2147.07,NaN,0.0,IC Invoice - EU Sales/IC Invoice - Outside EU,,LEGO c-out from DK,B85376630,IC Invoice - EU Sales

In [47]:
#use na=False to avoid errors when filtering on IC
vat.loc[(vat['Comments'] == 'IC Invoice - EU Sales/IC Invoice - Outside EU'), 'Comments'] = vat['Comment 3']
vat[vat["Comments"].str.contains("IC Invoice", na=False)]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,VAT reverse charge,Comment 2,VAT No,Comment 3
1574,GBTICJE,GBTICJE-IDENTIFIERA-ID2280758,JE-DK0300630,TJE-DK0300630,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-2240.42,NaN,0.0,IC Invoice - EU Sales,,APMM c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
1575,GBTICJE,GBTICJE-IDENTIFIERA-ID2280759,JE-DK0300631,TJE-DK0300631,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-809.04,NaN,0.0,IC Invoice - EU Sales,,APMM c-out from DK,FI02152075,IC Invoice - EU Sales
1576,GBTICJE,GBTICJE-IDENTIFIERA-ID2280767,JE-DK0300632,TJE-DK0300632,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-2707.17,NaN,0.0,IC Invoice - EU Sales,,Carlsberg c-out from DK,FI02152075,IC Invoice - EU Sales
1577,GBTICJE,GBTICJE-IDENTIFIERA-ID2280760,JE-DK0300633,TJE-DK0300633,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-1991.48,NaN,0.0,IC Invoice - EU Sales,,APMM c-out from DK,FR 15 304 475 338,IC Invoice - EU Sales
1578,GBTICJE,GBTICJE-IDENTIFIERA-ID2280761,JE-DK0300634,TJE-DK0300634,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-217.82,NaN,0.0,IC Invoice - EU Sales,,APMM c-out from DK,DE254337470,IC Invoice - EU Sales
1579,GBTICJE,GBTICJE-IDENTIFIERA-ID2280763,JE-DK0300635,TJE-DK0300635,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-403679.89,NaN,0.0,IC Invoice - Outside EU,,APMM c-out from DK,NO959209502,IC Invoice - Outside EU
1580,GBTICJE,GBTICJE-IDENTIFIERA-ID2280762,JE-DK0300636,TJE-DK0300636,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-116750.71,NaN,0.0,IC Invoice - EU Sales,,APMM c-out from DK,NL853361757B01,IC Invoice - EU Sales
1581,GBTICJE,GBTICJE-IDENTIFIERA-ID2280764,JE-DK0300637,TJE-DK0300637,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-6285.62,NaN,0.0,IC Invoice - EU Sales,,APMM c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1582,GBTICJE,GBTICJE-IDENTIFIERA-ID2280765,JE-DK0300638,TJE-DK0300638,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-373.40,NaN,0.0,IC Invoice - Outside EU,,APMM c-out from DK,CHE-300.737.496 MWST,IC Invoice - Outside EU
1583,GBTICJE,GBTICJE-IDENTIFIERA-ID2280766,JE-DK0300639,TJE-DK0300639,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-65283.31,NaN,0.0,IC Invoice - EU Sales,,APMM c-out from DK,GB 177248479,IC Invoice - EU Sales
1584,GBTICJE,GBTICJE-IDENTIFIERA-ID2280769,JE-DK0300640,TJE-DK0300640,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-11139.86,NaN,0.0,IC Invoice - Outside EU,,Carlsberg c-out from DK,NO959209502,IC Invoice - Outside EU
1585,GBTICJE,GBTICJE-IDENTIFIERA-ID2280768,JE-DK0300641,TJE-DK0300641,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-3609.56,NaN,0.0,IC Invoice - EU Sales,,Carlsberg c-out from DK,DE254337470,IC Invoice - EU Sales
1586,GBTICJE,GBTICJE-IDENTIFIERA-ID2280770,JE-DK0300642,TJE-DK0300642,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-11980.02,NaN,0.0,IC Invoice - EU Sales,,Carlsberg c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1587,GBTICJE,GBTICJE-IDENTIFIERA-ID2280771,JE-DK0300643,TJE-DK0300643,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-27040.61,NaN,0.0,IC Invoice - Outside EU,,Carlsberg c-out from DK,CHE-300.737.496 MWST,IC Invoice - Outside EU
1588,GBTICJE,GBTICJE-IDENTIFIERA-ID2280772,JE-DK0300644,TJE-DK0300644,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-12602.36,NaN,0.0,IC Invoice - EU Sales,,Carlsberg c-out from DK,GB 177248479,IC Invoice - EU Sales
1589,GBTICJE,GBTICJE-IDENTIFIERA-ID2280773,JE-DK0300645,TJE-DK0300645,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-5943.33,NaN,0.0,IC Invoice - EU Sales,,Danske Bank c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
1590,GBTICJE,GBTICJE-IDENTIFIERA-ID2280774,JE-DK0300646,TJE-DK0300646,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-9957.42,NaN,0.0,IC Invoice - EU Sales,,Danske Bank c-out from DK,FI02152075,IC Invoice - EU Sales
1591,GBTICJE,GBTICJE-IDENTIFIERA-ID2280775,JE-DK0300647,TJE-DK0300647,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-75085.14,NaN,0.0,IC Invoice - Outside EU,,Danske Bank c-out from DK,NO959209502,IC Invoice - Outside EU
1592,GBTICJE,GBTICJE-IDENTIFIERA-ID2280777,JE-DK0300648,TJE-DK0300648,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-59028.81,NaN,0.0,IC Invoice - EU Sales,,Danske Bank c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1593,GBTICJE,GBTICJE-IDENTIFIERA-ID2280778,JE-DK0300649,TJE-DK0300649,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-10486.40,NaN,0.0,IC Invoice - EU Sales,,Danske Bank c-out from DK,GB 177248479,IC Invoice - EU Sales
1594,GBTICJE,GBTICJE-IDENTIFIERA-ID2280779,JE-DK0300650,TJE-DK0300650,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-62.23,NaN,0.0,IC Invoice - EU Sales,,LEGO c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
1595,GBTICJE,GBTICJE-IDENTIFIERA-ID2280781,JE-DK0300651,TJE-DK0300651,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-3018.34,NaN,0.0,IC Invoice - EU Sales,,LEGO c-out from DK,FR 15 304 475 338,IC Invoice - EU Sales
1596,GBTICJE,GBTICJE-IDENTIFIERA-ID2280776,JE-DK0300652,TJE-DK0300652,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-4947.59,NaN,0.0,IC Invoice - EU Sales,,Danske Bank c-out from DK,PL 5252273929,IC Invoice - EU Sales
1597,GBTICJE,GBTICJE-IDENTIFIERA-ID2280782,JE-DK0300653,TJE-DK0300653,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-11980.02,NaN,0.0,IC Invoice - EU Sales,,Carlsberg c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1598,GBTICJE,GBTICJE-IDENTIFIERA-ID2280784,JE-DK0300654,TJE-DK0300654,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-31210.28,NaN,0.0,IC Invoice - EU Sales,,LEGO c-out from DK,NL853361757B01,IC Invoice - EU Sales
1599,GBTICJE,GBTICJE-IDENTIFIERA-ID2280785,JE-DK0300655,TJE-DK0300655,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-1213.56,NaN,0.0,IC Invoice - Outside EU,,LEGO c-out from DK,NO959209502,IC Invoice - Outside EU
1600,GBTICJE,GBTICJE-IDENTIFIERA-ID2280786,JE-DK0300656,TJE-DK0300656,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-1711.43,NaN,0.0,IC Invoice - EU Sales,,LEGO c-out from DK,PL 5252273929,IC Invoice - EU Sales
1601,GBTICJE,GBTICJE-IDENTIFIERA-ID2280780,JE-DK0300657,TJE-DK0300657,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-528.99,NaN,0.0,IC Invoice - EU Sales,,LEGO c-out from DK,CZ 02525071,IC Invoice - EU Sales
1602,GBTICJE,GBTICJE-IDENTIFIERA-ID2280788,JE-DK0300658,TJE-DK0300658,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-560.10,NaN,0.0,IC Invoice - EU Sales,,LEGO c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1603,GBTICJE,GBTICJE-IDENTIFIERA-ID2280789,JE-DK0300659,TJE-DK0300659,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-53676.70,NaN,0.0,IC Invoice - EU Sales,,LEGO c-out from DK,GB 177248479,IC Invoice - EU Sales
1604,GBTICJE,GBTICJE-IDENTIFIERA-ID2280783,JE-DK0300660,TJE-DK0300660,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-62.23,NaN,0.0,IC Invoice - EU Sales,,LEGO c-out from DK,BE 0463 685 338,IC Invoice - EU Sales
1605,GBTICJE,GBTICJE-IDENTIFIERA-ID2280790,JE-DK0300661,TJE-DK0300661,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-6472.32,NaN,0.0,IC Invoice - EU Sales,,Ramboll c-out from DK,FI02152075,IC Invoice - EU Sales
1606,GBTICJE,GBTICJE-IDENTIFIERA-ID2280791,JE-DK0300662,TJE-DK0300662,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-12789.06,NaN,0.0,IC Invoice - Outside EU,,Ramboll c-out from DK,NO959209502,IC Invoice - Outside EU
1607,GBTICJE,GBTICJE-IDENTIFIERA-ID2280792,JE-DK0300663,TJE-DK0300663,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-1618.08,NaN,0.0,IC Invoice - EU Sales,,Ramboll c-out from DK,DE254337470,IC Invoice - EU Sales
1608,GBTICJE,GBTICJE-IDENTIFIERA-ID2280793,JE-DK0300664,TJE-DK0300664,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-41198.81,NaN,0.0,IC Invoice - EU Sales,,Ramboll c-out from DK,SE 556 051 442 301,IC Invoice - EU Sales
1609,GBTICJE,GBTICJE-IDENTIFIERA-ID2280794,JE-DK0300665,TJE-DK0300665,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-8526.04,NaN,0.0,IC Invoice - EU Sales,,Ramboll c-out from DK,GB 177248479,IC Invoice - EU Sales
1610,GBTICJE,GBTICJE-IDENTIFIERA-ID2280787,JE-DK0300666,TJE-DK0300666,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,0.0,-2147.07,NaN,0.0,IC Invoice - EU Sales,,LEGO c-out from DK,B85376630,IC Invoice - EU Sales

In [48]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == "Transactions 0DKK") &
        (vat['External name'] == 'GBTICJE') &
        (vat['Maximum of NetSuite Tax Item'].isnull()), 'Comments'] = 'Intercompany no IC invoice'
vat[vat["Comments"] == "Intercompany no IC invoice"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,VAT reverse charge,Comment 2,VAT No,Comment 3
71,GBTICJE,GBTICJE-IDENTIFIERH-ID2270896,JE-NL1276238,TJE-NL0166162,,Journal,8/1/2020,Aug-20,- None -,NaN,...,NaN,NaN,-347653.12,NaN,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
72,GBTICJE,GBTICJE-IDENTIFIERB-ID2270895,JE-NL1276239,TJE-NL0166163,,Journal,8/1/2020,Aug-20,- None -,NaN,...,-386281.24,NaN,386281.24,NaN,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
1541,GBTICJE,GBTICJE-IDENTIFIERH-ID2290961,JE-NL1277402,TJE-NL0167326,,Journal,8/15/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,-151.94,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
1736,GBTICJE,GBTICJE-IDENTIFIERH-ID2281056,JE-NL1277042,TJE-NL0166966,,Journal,8/17/2020,Aug-20,- None -,NaN,...,NaN,-113.3,NaN,NaN,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3416,GBTICJE,GBTICJE-IDENTIFIERA-ID2306485,JE-DK0303434,TJE-DK0303434,,Journal,8/30/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,-29858.59,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3417,GBTICJE,GBTICJE-IDENTIFIERB-ID2287460,JE-NL1277252,TJE-NL0167176,,Journal,8/30/2020,Aug-20,- None -,NaN,...,-1772.89,NaN,NaN,1772.89,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3418,GBTICJE,GBTICJE-IDENTIFIERB-ID2287486,JE-NL1277277,TJE-NL0167201,,Journal,8/30/2020,Aug-20,- None -,NaN,...,-1911.82,NaN,NaN,1911.82,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3419,GBTICJE,GBTICJE-IDENTIFIERB-ID2295766,JE-NL1278038,TJE-NL0167962,,Journal,8/30/2020,Aug-20,- None -,NaN,...,-464.28,NaN,NaN,464.28,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3711,GBTICJE,GBTICJE-IDENTIFIERB-ID2291763,JE-NL1277575,TJE-NL0167499,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-27255.75,NaN,NaN,27255.75,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3712,GBTICJE,GBTICJE-IDENTIFIERB-ID2292068,JE-NL1277602,TJE-NL0167526,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-3360.65,NaN,NaN,3360.65,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3713,GBTICJE,GBTICJE-IDENTIFIERH-ID2292091,JE-NL1277627,TJE-NL0167551,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,-388.12,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3714,GBTICJE,GBTICJE-IDENTIFIERB-ID2294354,JE-NL1277874,TJE-NL0167798,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-1358.56,NaN,NaN,1358.56,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3715,GBTICJE,GBTICJE-IDENTIFIERB-ID2294457,JE-NL1277900,TJE-NL0167824,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-10478.00,NaN,NaN,10478.00,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3716,GBTICJE,GBTICJE-IDENTIFIERB-ID2294563,JE-NL1277911,TJE-NL0167835,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-2422.08,NaN,NaN,2422.08,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3720,GBTICJE,GBTICJE-IDENTIFIERH-ID2299558,JE-NL1278690,TJE-NL0168614,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,-512263.72,NaN,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3721,GBTICJE,GBTICJE-IDENTIFIERB-ID2299554,JE-NL1278693,TJE-NL0168617,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-461037.36,NaN,461037.36,NaN,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3722,GBTICJE,GBTICJE-IDENTIFIERH-ID2301063,JE-NL1278952,TJE-NL0168876,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3723,GBTICJE,GBTICJE-IDENTIFIERH-ID2301059,JE-NL1278953,TJE-NL0168877,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3724,GBTICJE,GBTICJE-IDENTIFIERH-ID2301062,JE-NL1278954,TJE-NL0168878,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3725,GBTICJE,GBTICJE-IDENTIFIERH-ID2301060,JE-NL1278955,TJE-NL0168879,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3726,GBTICJE,GBTICJE-IDENTIFIERH-ID2301055,JE-NL1278956,TJE-NL0168880,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3727,GBTICJE,GBTICJE-IDENTIFIERH-ID2301054,JE-NL1278957,TJE-NL0168881,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3728,GBTICJE,GBTICJE-IDENTIFIERH-ID2301061,JE-NL1278958,TJE-NL0168882,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3729,GBTICJE,GBTICJE-IDENTIFIERH-ID2301057,JE-NL1278959,TJE-NL0168883,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3730,GBTICJE,GBTICJE-IDENTIFIERH-ID2301056,JE-NL1278960,TJE-NL0168884,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3731,GBTICJE,GBTICJE-IDENTIFIERH-ID2301058,JE-NL1278961,TJE-NL0168885,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3732,GBTICJE,GBTICJE-IDENTIFIERH-ID2301064,JE-NL1278962,TJE-NL0168886,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,0.0,Intercompany no IC invoice,,NaN,NaN,NaN
3733,GBTICJE,GBTICJE-IDENTIFIERH-ID2301065,JE-NL1278963,TJE-NL0168887,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,NaN,0.0,Intercompany no IC invoice,,NaN,NaN,NaN

In [49]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == "Transactions 0DKK") &
        (vat['Type'].isin(['Journal'])), 'Comments'] = 'JE-transactions no vat'
vat[vat["Comments"] == "JE-transactions no vat"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,VAT reverse charge,Comment 2,VAT No,Comment 3
13,ID,21538_ID-549901_COGSADJ,JE-DK0303432,TJE-DK0303432,,Journal,6/26/2020,Aug-20,- None -,NaN,...,NaN,71.74,-71.74,NaN,0.0,JE-transactions no vat,,NaN,NaN,NaN
18,HC,HC-OPF-1115-2020-7-17 Fee Adj,JE-DK0300362,TJE-DK0300362,,Journal,7/17/2020,Aug-20,- None -,NaN,...,NaN,NaN,-3461.18,3461.18,0.0,JE-transactions no vat,,NaN,NaN,NaN
19,HCTransient_thenry7_Reclass,20200717_HCTransient_thenry7_Reclass Onyx Fee_...,JE-DK0300363,TJE-DK0300363,,Journal,7/17/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,0.00,0.0,JE-transactions no vat,,NaN,NaN,NaN
21,HC,HC-OPF-1115-2020-7-22 Fee Adj,JE-DK0300361,TJE-DK0300361,,Journal,7/22/2020,Aug-20,- None -,NaN,...,NaN,NaN,-537.32,537.32,0.0,JE-transactions no vat,,NaN,NaN,NaN
22,HCTransient_thenry7_Reclass,20200722_HCTransient_thenry7_Reclass Onyx Fee_...,JE-DK0300364,TJE-DK0300364,,Journal,7/22/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,0.00,0.0,JE-transactions no vat,,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3702,FST_shatfield_DK_1115_1,20200831_FST_shatfield_DK_1115_1,JE-DK0302992,TJE-DK0302992,,Journal,8/31/2020,Aug-20,- None -,NaN,...,57743.50,NaN,NaN,NaN,0.0,JE-transactions no vat,,NaN,NaN,NaN
3703,RLFO_Vmarrahi_KDS,20200831_RLFO_Vmarrahi_KDS mkts allocation1115,JE-DK0303433,TJE-DK0303433,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,NaN,0.00,0.0,JE-transactions no vat,,NaN,NaN,NaN
3704,RCL102AUGUST2020,RCL102AUGUST2020 1004,JE-DK0303483,TJE-DK0303483,,Journal,8/31/2020,Aug-20,- None -,NaN,...,0.00,NaN,NaN,NaN,0.0,JE-transactions no vat,,NaN,NaN,NaN
3705,AugHRG_DNK_TB_Movement,2020AugHRG_DNK_TB_Movement,JE-DK0303586,TJE-DK0303586,,Journal,8/31/2020,Aug-20,- None -,NaN,...,-66728.62,253965.14,-117971.57,12275.19,0.0,JE-transactions no vat,,NaN,NaN,NaN
3706,AugHRG_DNK_TB_movement_Sales,2020AugHRG_DNK_TB_movement_Sales,JE-DK0303587,TJE-DK0303587,,Journal,8/31/2020,Aug-20,- None -,NaN,...,NaN,NaN,0.00,NaN,0.0,JE-transactions no vat,,NaN,NaN,NaN

In [50]:
## REMEMBER TO CHECK THAT ALL OF THE SPACES IN THE BLANK CELLS IN THE CSV FILE ARE REMOVED AS WELL!!!use isin([np.nan, ' '])

vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == 'Transactions 0DKK') &
        (vat['Type'].isin(['Bill','Bill Credit'])) &
        (~vat['Maximum of Linked Invoice'].isin([np.nan, ' '])), 'Comments'] = 'Linked invoice'
vat[vat["Comments"] == "Linked invoice"]

Empty DataFrame
Columns: [External name, External ID, Document Number, Transaction Number, Maximum of Linked Invoice, Type, Date, Period, Terms, Maximum of Due Date/Receive By, Vendor Category, Vendor Name, Vendor Number, Company Name, Vendor VAT Registration Number, Vendor Billing Address, Vendor Billing Country, Bill to City, Bill to State, Bill to Country, Bill to Zip, Source System, Source System Identifier, City, State/Province, Country, Zip, Currency, Memo (Main), Maximum of GMAX Tax Code, Maximum of NetSuite Tax Item, Maximum of Coupa Tax Code, Maximum of External System Tax Code, Maximum of Tax Code (Consolidated), FOP Type, Sum of Asset, Sum of Accounts Payable, Sum of Other Liabilities, Sum of Income, Sum of Expense, Sum of VAT, Comments, VAT reverse charge, Comment 2, VAT No, Comment 3]
Index: []

[0 rows x 46 columns]

In [51]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == 'Transactions 0DKK') &
        (~vat['Memo (Main)'].isin(['- None -'])), 'Comments'] = 'Travel Bill'
vat[vat["Comments"] == "Travel Bill"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,VAT reverse charge,Comment 2,VAT No,Comment 3
210,None,- None -,1006172918,BL-DK0409697,,Bill,8/4/2020,Aug-20,Net 7,8/11/2020,...,-456.00,456.00,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN
211,None,- None -,1451-VPAY-July- 2020,BL-DK0409695,,Bill,8/4/2020,Aug-20,- None -,7/31/2020,...,-2966.81,NaN,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN
212,None,- None -,2800047416 3800047417,BL-DK0409694,,Bill,8/4/2020,Aug-20,Due on receipt,8/4/2020,...,-420035.20,NaN,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN
213,None,- None -,2800047452 3800047453,BL-DK0409696,,Bill,8/4/2020,Aug-20,Due on receipt,8/4/2020,...,-547471.66,NaN,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN
218,None,- None -,4750-VPAY-Jun-2020,BL-DK0409701,,Bill,8/4/2020,Aug-20,- None -,8/4/2020,...,-200.81,NaN,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2572,None,- None -,2010109656,BL-DK0409837,,Bill,8/25/2020,Aug-20,Net 60,10/24/2020,...,-596.00,NaN,NaN,596.0,0.0,Travel Bill,,NaN,NaN,NaN
2808,None,- None -,2800047678,BL-DK0409839,,Bill,8/26/2020,Aug-20,Due on receipt,9/10/2020,...,-177781.35,NaN,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN
3350,None,- None -,refund aug0828,BC-DK0126202,,Bill Credit,8/28/2020,Aug-20,- None -,NaN,...,55498.00,-55498.00,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN
3351,None,- None -,refund0828,BC-DK0126203,,Bill Credit,8/28/2020,Aug-20,- None -,NaN,...,67242.61,-67242.61,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN
3420,None,- None -,87302732,BL-DK0409846,,Bill,8/31/2020,Aug-20,Due on receipt,8/31/2020,...,-2624.00,2624.00,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN

In [52]:
vat.loc[(vat['Sum of VAT'].isin([np.nan, 0])) &
        (vat['Comments'] == 'Transactions 0DKK'), 'Comments'] = 'Travel Bill'
vat[vat["Comments"] == "Travel Bill"]

,External name,External ID,Document Number,Transaction Number,Maximum of Linked Invoice,Type,Date,Period,Terms,Maximum of Due Date/Receive By,...,Sum of Accounts Payable,Sum of Other Liabilities,Sum of Income,Sum of Expense,Sum of VAT,Comments,VAT reverse charge,Comment 2,VAT No,Comment 3
210,None,- None -,1006172918,BL-DK0409697,,Bill,8/4/2020,Aug-20,Net 7,8/11/2020,...,-456.00,456.00,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN
211,None,- None -,1451-VPAY-July- 2020,BL-DK0409695,,Bill,8/4/2020,Aug-20,- None -,7/31/2020,...,-2966.81,NaN,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN
212,None,- None -,2800047416 3800047417,BL-DK0409694,,Bill,8/4/2020,Aug-20,Due on receipt,8/4/2020,...,-420035.20,NaN,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN
213,None,- None -,2800047452 3800047453,BL-DK0409696,,Bill,8/4/2020,Aug-20,Due on receipt,8/4/2020,...,-547471.66,NaN,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN
218,None,- None -,4750-VPAY-Jun-2020,BL-DK0409701,,Bill,8/4/2020,Aug-20,- None -,8/4/2020,...,-200.81,NaN,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2573,KDS_Exp_VB_5046988,KDS_Exp_VB_5046988.2020-08-25-1,5046988.2020-08-25-1,BL-DK0409838,,Bill,8/25/2020,Aug-20,Due on receipt,8/25/2020,...,-22061.69,22061.69,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN
2808,None,- None -,2800047678,BL-DK0409839,,Bill,8/26/2020,Aug-20,Due on receipt,9/10/2020,...,-177781.35,NaN,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN
3350,None,- None -,refund aug0828,BC-DK0126202,,Bill Credit,8/28/2020,Aug-20,- None -,NaN,...,55498.00,-55498.00,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN
3351,None,- None -,refund0828,BC-DK0126203,,Bill Credit,8/28/2020,Aug-20,- None -,NaN,...,67242.61,-67242.61,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN
3420,None,- None -,87302732,BL-DK0409846,,Bill,8/31/2020,Aug-20,Due on receipt,8/31/2020,...,-2624.00,2624.00,NaN,NaN,0.0,Travel Bill,,NaN,NaN,NaN

In [53]:
vat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3744 entries, 0 to 3743
Data columns (total 46 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   External name                        3744 non-null   object
 1   External ID                          3744 non-null   object
 2   Document Number                      3744 non-null   object
 3   Transaction Number                   3744 non-null   object
 4   Maximum of Linked Invoice            3744 non-null   object
 5   Type                                 3744 non-null   object
 6   Date                                 3744 non-null   object
 7   Period                               3744 non-null   object
 8   Terms                                3744 non-null   object
 9   Maximum of Due Date/Receive By       147 non-null    object
 10  Vendor Category                      3744 non-null   object
 11  Vendor Name                          3744 non-null   object
 12  Vendor Number                        0 non-null      float64
 13  Company Name                         3744 non-null   object
 14  Vendor VAT Registration Number       3744 non-null   object
 15  Vendor Billing Address               3744 non-null   object
 16  Vendor Billing Country               3744 non-null   object
 17  Bill to City                         3744 non-null   object
 18  Bill to State                        3744 non-null   object
 19  Bill to Country                      3744 non-null   object
 20  Bill to Zip                          3744 non-null   object
 21  Source System                        3744 non-null   object
 22  Source System Identifier             3744 non-null   object
 23  City                                 3744 non-null   object
 24  State/Province                       3744 non-null   object
 25  Country                              3744 non-null   object
 26  Zip                                  3744 non-null   object
 27  Currency                             3744 non-null   object
 28  Memo (Main)                          3744 non-null   object
 29  Maximum of GMAX Tax Code             0 non-null      float64
 30  Maximum of NetSuite Tax Item         2504 non-null   object
 31  Maximum of Coupa Tax Code            0 non-null      float64
 32  Maximum of External System Tax Code  0 non-null      float64
 33  Maximum of Tax Code (Consolidated)   2504 non-null   object
 34  FOP Type                             3744 non-null   object
 35  Sum of Asset                         2882 non-null   float64
 36  Sum of Accounts Payable              229 non-null    float64
 37  Sum of Other Liabilities             2566 non-null   float64
 38  Sum of Income                        2956 non-null   float64
 39  Sum of Expense                       219 non-null    float64
 40  Sum of VAT                           3744 non-null   float64
 41  Comments                             3744 non-null   object
 42  VAT reverse charge                   3744 non-null   object
 43  Comment 2                            37 non-null     object
 44  VAT No                               37 non-null     object
 45  Comment 3                            37 non-null     object
dtypes: float64(10), object(36)
memory usage: 1.5+ MB

In [54]:
#Change position of columns
col = vat.columns.tolist() # list the columns in the df
col.insert(42, col.pop(col.index('Comments'))) # Assign new position (i.e. 42) for "Comments" 
vat = vat.reindex(columns= col) # Now move 'F' to ist new position

In [55]:
vat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3744 entries, 0 to 3743
Data columns (total 46 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   External name                        3744 non-null   object
 1   External ID                          3744 non-null   object
 2   Document Number                      3744 non-null   object
 3   Transaction Number                   3744 non-null   object
 4   Maximum of Linked Invoice            3744 non-null   object
 5   Type                                 3744 non-null   object
 6   Date                                 3744 non-null   object
 7   Period                               3744 non-null   object
 8   Terms                                3744 non-null   object
 9   Maximum of Due Date/Receive By       147 non-null    object
 10  Vendor Category                      3744 non-null   object
 11  Vendor Name                          3744 non-null   object
 12  Vendor Number                        0 non-null      float64
 13  Company Name                         3744 non-null   object
 14  Vendor VAT Registration Number       3744 non-null   object
 15  Vendor Billing Address               3744 non-null   object
 16  Vendor Billing Country               3744 non-null   object
 17  Bill to City                         3744 non-null   object
 18  Bill to State                        3744 non-null   object
 19  Bill to Country                      3744 non-null   object
 20  Bill to Zip                          3744 non-null   object
 21  Source System                        3744 non-null   object
 22  Source System Identifier             3744 non-null   object
 23  City                                 3744 non-null   object
 24  State/Province                       3744 non-null   object
 25  Country                              3744 non-null   object
 26  Zip                                  3744 non-null   object
 27  Currency                             3744 non-null   object
 28  Memo (Main)                          3744 non-null   object
 29  Maximum of GMAX Tax Code             0 non-null      float64
 30  Maximum of NetSuite Tax Item         2504 non-null   object
 31  Maximum of Coupa Tax Code            0 non-null      float64
 32  Maximum of External System Tax Code  0 non-null      float64
 33  Maximum of Tax Code (Consolidated)   2504 non-null   object
 34  FOP Type                             3744 non-null   object
 35  Sum of Asset                         2882 non-null   float64
 36  Sum of Accounts Payable              229 non-null    float64
 37  Sum of Other Liabilities             2566 non-null   float64
 38  Sum of Income                        2956 non-null   float64
 39  Sum of Expense                       219 non-null    float64
 40  Sum of VAT                           3744 non-null   float64
 41  VAT reverse charge                   3744 non-null   object
 42  Comments                             3744 non-null   object
 43  Comment 2                            37 non-null     object
 44  VAT No                               37 non-null     object
 45  Comment 3                            37 non-null     object
dtypes: float64(10), object(36)
memory usage: 1.5+ MB

In [56]:
#VAT reverse charge can't work with sum due to containing strings
pvt= vat.pivot_table(index='Comments', values=['Sum of Accounts Payable', 'Sum of Expense', 'Sum of VAT'], aggfunc='sum', margins=True, margins_name= 'Grand total')

In [57]:
pvt

,Sum of Accounts Payable,Sum of Expense,Sum of VAT
Comments,,,
IC Invoice - EU Sales,0.00,0.00,0.00
IC Invoice - Outside EU,0.00,0.00,0.00
IC reverse charge EU/Outside,-261781.97,256639.91,64159.99
Intercompany no IC invoice,-896342.63,18625.38,0.00
JE-transactions no vat,3489032.97,8485081.23,0.00
Neo travel expense - no vat,-1313.32,2923.01,0.00
Procurement-Denmark 0% VAT,-32034.51,32034.51,0.00
Procurement-EU/Outside Reverse charge,-493064.94,493064.94,0.00
Travel Bill,-5250767.04,45404.38,0.00
VAT,-542420.92,365243.74,103803.66
Grand total,-4951632.61,2026622.80,155133.22

In [58]:
pvt.loc[('Grand total'),:] = pvt.iloc[:(pvt.shape[0]-1), :].sum()

In [59]:
#thousand separator
pd.options.display.float_format = '{:,}'.format
pvt.round(0)

#use this if you want to display integer values
#pvt.round(0).astype(int)

,Sum of Accounts Payable,Sum of Expense,Sum of VAT
Comments,,,
IC Invoice - EU Sales,0.0,0.0,0.0
IC Invoice - Outside EU,0.0,0.0,0.0
IC reverse charge EU/Outside,"-261,782.0","256,640.0","64,160.0"
Intercompany no IC invoice,"-896,343.0","18,625.0",0.0
JE-transactions no vat,"3,489,033.0","8,485,081.0",0.0
Neo travel expense - no vat,"-1,313.0","2,923.0",0.0
Procurement-Denmark 0% VAT,"-32,035.0","32,035.0",0.0
Procurement-EU/Outside Reverse charge,"-493,065.0","493,065.0",0.0
Travel Bill,"-5,250,767.0","45,404.0",0.0
VAT,"-542,421.0","365,244.0","103,804.0"
Grand total,"-3,988,692.0","9,699,017.0","167,964.0"

In [61]:
# excel_file = pd.ExcelWriter("Darko_VAT_purchase_202008.xlsx")

# vat.to_excel(excel_file, sheet_name = "vat", index = False)

# excel_file.save()